### ISSUE TITLE
Analytics: cannot find symbol variable xml

### ISSUE THREAD

**Issue by SleeplessByte** [googlesamples/google-services#1]
The sample is not complete. You can't build the Analytics project from "scratch"-clone.

The guides below give different information:
- https://developers.google.com/analytics/devguides/collection/android/v4/app
- https://developers.google.com/analytics/devguides/collection/android/v4/

**Comment by ianbarber** [comment]
Thanks for the issue! The sample needs you to grab a config file from https:/developers.google.com/mobile/add (as it true for them all in this repo actually!). 

We need to signal that better - in a previous version of the plugin it was emitting build failure if that was missing, but the current version just warns, so we fail on the build error.

**Comment by SleeplessByte** [comment]
Understood. What about the differences between the guides for - clearly - the same library?

**Comment by ianbarber** [comment]
Good point - we're looking at that at the moment. Clarifying and simplifying the documentation in general is our goal, but its quite a long road!

**Comment by SleeplessByte** [comment]
:+1:

**Comment by briancaw** [comment]
@ianbarber Did something change in the documentation recently?  https:/developers.google.com/mobile/add generates a google-services.json file but the samples expect a global_tracker.xml file.  I can't seem to find any official v4 docs about this file, but then I hunted around a bit and found https://developers.google.com/analytics/devguides/collection/android/v3/#analytics-xml which is deprecated?  

It seems to still be required functionality, so should it be on https://developers.google.com/analytics/devguides/collection/android/v4/ somewhere? 

Thanks, and apologies if I'm missing something simple.

**Comment by ianbarber** [comment]
The xml should be generated from the JSON. There is a bug in the documentation (may have been fixed recently) where the package name is wrong, which I suspect you're hitting. Check that the JSON you have generated to see if the package name matches the package name in the manifest - if not, you should just be able to create a new client ID in the same project, and get a new json file.

**Comment by talhakosen** [comment]
@ianbarber thanks it saved my day :+1:
