### ISSUE TITLE
Flavor/build type support in google-services gradle plugin

### ISSUE THREAD

**Issue by ajfclark** [googlesamples/google-services#100]
I'm not sure where is best to raise this issue.

The current location of the google-services.json file in the project tree means that without some fancy fiddling with files in gradle, it is not possible to customise something like your Google Analytics configuration based on flavor or build type. It seems the point of the google-services.json file is to make integrating google services simple, which makes needing complicated gradle configs seems a backwards step.

I would've thought it made the most sense for the google-services.json file to be in the [module]/src/[flavor] directory rather than the module root. That way it'd be trivial to change the google services profile based on flavor and/or build type.

**Comment by samtstern** [comment]
Thanks for this report.  This is a request I have heard before, I will look into it.

**Comment by renanferrari** [comment]
+1

**Comment by ianbarber** [comment]
I think we should track this in #54
