### ISSUE TITLE
iOS Manual Install Instructions should include "Link Only" not "Embed" Clarification

### ISSUE THREAD

**Issue by aventurella** [googlesamples/google-services#101]
The instructions for manually installing do not mention you should only "Link" the `GoogleSignIn.framework` and NOT "Embed" it. Embedding the SDK causes a "Cannot Inspect" Error at runtime on the device.

Preferably here:
https://developers.google.com/identity/sign-in/ios/sdk/?hl=en

**Comment by ianbarber** [comment]
Agreed, will update.

**Comment by gguuss** [comment]
The instructions have been updated.
