### ISSUE TITLE
iOS Manual Install Instructions should include that the GoogleSignIn.bundle should be included in resources

### ISSUE THREAD

**Issue by aventurella** [googlesamples/google-services#103]
https://developers.google.com/identity/sign-in/ios/sdk/?hl=en

Should explicitly state that the downloaded `GoogleSignIn.bundle` should be added as a resource into the built app. AKA It should be present in the **Copy Bundle Resources** Build Phase.

**Comment by gguuss** [comment]
Thanks for the report, I'll see about getting the docs updated.

**Comment by gguuss** [comment]
This page should now have the updates:

https://developers.google.com/identity/sign-in/ios/sdk/index#add_the_sdk_your_xcode_project
