### ISSUE TITLE
Android app crashes on signout in google sign-in

### ISSUE THREAD

**Issue by droidster** [googlesamples/google-services#104]
The documentation states that you must confirm that GoogleApiClient.onConnected has been called before you call signOut. But in the sample code, googleApiClient.connect() is never called and it crashes on signOut. Where should the connect method be called?

**Comment by samtstern** [comment]
This means you called signOut before you were signed in (which should be apparent via the status text on the screen).

When using `enableAutoManage` with `GoogleApiClient` you don't have to call `connect` or `disconnect`, they are automatically called when your Activity starts and stops.

**Comment by droidster** [comment]
First of all, the sample is working fine. Sorry about the confusion but I don't know where else to post.

I'm moving from google plus sign in to the new sign in with google. It's the same code as the sample. I'm able to log in the user, get the user details and verify the id token on the server, but I can't sign out the user because googleApiClient is not connected, which is being auto managed. So how can i login the user without a connected googleApiClient? I have checked at various points during the lifecycle of the activity that the googleApiClient is not connected. 

I'm using location as well but that's being handled but a different googleApiClient which is being managed manually.

**Comment by samtstern** [comment]
Sorry for closing so quickly, thought you were talking about the sample.  Can you show me the code where you create your GoogleApiClient?  And also the code where you are checking if the user is signed in?

**Comment by droidster** [comment]
No problem. I'm creating the googleApiClient in onCreate.

```java

GoogleSignInOptions gso = new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
					.requestEmail()
					.requestIdToken(my_web_client_id_here)
					.build();

mGoogleApiClientPlus = new GoogleApiClient.Builder(this)
		.enableAutoManage(this /* FragmentActivity */, this /* OnConnectionFailedListener */)
		.addApi(Auth.GOOGLE_SIGN_IN_API, gso)
		.build();

```

Silent Sign-in in onStart

``` java
OptionalPendingResult<GoogleSignInResult> opr = Auth.GoogleSignInApi.silentSignIn(mGoogleApiClientPlus);
			if (opr.isDone()) {
				Timber.d("Got cached sign-in");
				GoogleSignInResult result = opr.get();
				handleSignInResult(result, true);
			} else {
				opr.setResultCallback(new ResultCallback<GoogleSignInResult>() {
					@Override
					public void onResult(GoogleSignInResult googleSignInResult) {
						handleSignInResult(googleSignInResult, true);
					}
				});
			}

			if (mGoogleApiClientPlus.isConnected()){
				Timber.d("sign in client connected");
			} else{
// 
				Timber.d("sign in client not connected");
			}

**Comment by samtstern** [comment]
So where you currently are checking `isConnected` I would expect it to always be false, since `connect()` is called for you some time in `onStart()` and it is asychronous.

If you want to detect when the GoogleApiClient is connected so that you can enable your sign-out button, you can still do `.addConnectionCallbacks()` and implement `GoogleApiClient.ConnectionCallbacks`, you just no longer have to do anything in `onConnected` that is related to sign-in since you are using the new sign-in API.

**Comment by droidster** [comment]
Thank you! This helped me figure it out. Should've just implemented the callbacks.

I was signing out the user just as the activity started again after onActivityResult was getting called. That's when the client has not re-connected since the log out button is in a different activity and client disconnects in onStop.
