### ISSUE TITLE
Plus.PeopleApi.getCurrentPerson();  always returns null in 8.3.0

### ISSUE THREAD

**Issue by karthik-logs** [googlesamples/google-services#106]
Since I got everything working fine in Google services version 8.1.1, but after updating it to 8.3.0, I got this issue. Google SignIn works perfectly. The only problem is with PeopleAPI.

**Comment by samtstern** [comment]
Are you using PeopleApi with the new Sign in sample code?  If so, can you
get the information you need from the GoogleSignInAccount object instead?
That is the preferred method.

If you think that Play Services 8.3.0 broke your old sign-in code, try
clearing data on your app and on Google Play Services.

**Comment by karthik-logs** [comment]
Yes, I am using the new Google Sign in Options. But I am trying to get profile info as well, so I am trying to integrate PeopleAPI. 

Now the issue is solved.

Steps I did.
1. Created new API key in google credentials.
2. Uninstalled the app and reinstalled it.
Not sure which solved the problem.

**Comment by samtstern** [comment]
Hmm ok well that is odd but glad it is working now!

In general you should not have to use PeopleApi anymore, but I'll close this for now since it's working for you.
