### ISSUE TITLE
Maven cannot find com.google.android.gms:play-services:8.3.0.

### ISSUE THREAD

**Issue by mrgren** [googlesamples/google-services#107]
Hi, 
I try to use play-services:8.3.0.
so  on app/build.gradle
dependencies {
   ......
    compile 'com.google.android.gms:play-services:8.3.0'
  ....
}
when gradle try to download it with maven it got 404 error like this : 
Could not find com.google.android.gms:play-services:8.3.0.
https://repo1.maven.org/maven2/com/google/android/gms/play-services/8.3.0/play-services-8.3.0.pom
https://repo1.maven.org/maven2/com/google/android/gms/play-services/8.3.0/play-services-8.3.0.jar

any help

**Comment by samtstern** [comment]
Play Services is distrusted through the Android SDK manager.  If you open
the SDK manager you should have the update available in the extras
category.

**Comment by samtstern** [comment]
Distributed* not distrusted (mobile phone typo)

**Comment by samtstern** [comment]
http://developer.android.com/sdk/installing/adding-packages.html

**Comment by yogeshksraj** [comment]
Hey I have updated my Google Play Services but still I'm facing same issue, if any one have idea behind this please share

**Comment by PaulRashidi** [comment]
Make sure you've used the SDK manager to install the "Android Support Repository." That is a locally installed maven repo that contains the Google Play services, the support libraries and some of the dependencies thereof.

**Comment by yogeshksraj** [comment]
Thanks Paul, I have updated my Google Play Services, Android Support Library, Android Support Repository and finally Google Repository and and restart my IDE now its work for me :+1:
