### ISSUE TITLE
iOS: GIDSignIn Crash when reentering app while offline

### ISSUE THREAD

**Issue by VrasidasP** [googlesamples/google-services#108]
In my iOS app I'm getting a user with GIDSignIn.
I need to refresh the user details whenever the app resumes from the background.

For this I'm using silent sign in when the app changes state, but I've found an error that results in crashes.

This is the code of the object that handles the login, this works ok when online:

`[GIDSignIn sharedInstance].clientID = google_client_id;`
`[GIDSignIn sharedInstance].uiDelegate = self;`
`[GIDSignIn sharedInstance].delegate = self;`
        `if(silently) {`
            `[[GIDSignIn sharedInstance] signInSilently];`
        `}`
        `else {`
            `[[GIDSignIn sharedInstance] signIn];`
        `}`

The error that comes up after the "signInSilently" call (or in "signIn" in tests):
-[__NSCFString fetcherWithRequest:]: unrecognized selector sent to instance 0x177e7930

(Other times the NSCString is NSArrayF, but the call is fetcherWithRequest always)

Any ideas? Am I using this library incorrectly?

**Comment by gguuss** [comment]
Can you reproduce it in the simulator (by disabling networking on your Mac)?  When I try to reproduce the issue on my own machine, I either am redirected to the Sign-in page (which doesn't load because no network); or, SSO succeeds and I'm returned a user object.

A key difference in the example app and your example is that the example sets up its iOS API client using [the flow outlined here](https://developers.google.com/mobile/add)

**Comment by VrasidasP** [comment]
Thanks for your answer!

Yes, the same happens in the simulator as well. 
Open the app, leave the app (Home button or openURL to safari), return to the app -> EXC_BAD_ACCESS at the line of signInSilently.

I have used the flow to get the plist and it's working fine.

The only difference is that I'm not using the pod, because there were problems installing it with some swift pod frameworks. 
But I've added manually the latest version (# 2015-10-26 -- v2.4.0) and I get the same problem.

**Comment by gguuss** [comment]
The approach used in the Google Services sample is different than how you are manually configuring your client. In Swift, the following code configures Sign-in:

    func application(application: UIApplication,
      didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        // Initialize sign-in
        var configureError: NSError?
        GGLContext.sharedInstance().configureWithError(&configureError)
        assert(configureError == nil, "Error configuring Google services: \(configureError)")

        GIDSignIn.sharedInstance().delegate = self

        return true
    }

Can you try to reproduce the issue using the [Google Services Sign-in Quickstart](https://github.com/googlesamples/google-services/tree/master/ios/signin)

**Comment by VrasidasP** [comment]
I'm not using GGLContext, maybe I will transition my code to use that.
Good news is I've found a solution for my problem where I added `[[GIDSignIn sharedInstance] signOut];` before the calls to signIn, and now my scenario does not crash.

So I will close this issue for now, if I find the time I will try to reproduce this problem as you said and come back to it.

Thank you for your help! :)

**Comment by chiart** [comment]
For future seekers.
I do not use pod too and have the similar problem with different fetcherWithRequest receivers and crashes.
My problem was solved by calling signin from main thread (calls from other threads crash).

**Comment by joonhocho** [comment]
I am having the same issue. @chiart 's solution fixed it, tho.
