### ISSUE TITLE
iOS Dynamic Framework support

### ISSUE THREAD

**Issue by piercifani** [googlesamples/google-services#110]
Hello all

It's impossible to integrate any of the Google Pods using an all-Swift application, since it's bundled and packaged as static library instead of a dynamic framework.

This is a huge problem, specially with Swift adoption ever increasing.

Ideally, I should be able to integrate any pod using the `use_frameworks!` flag in my Podfile.

All the best!

**Comment by ianbarber** [comment]
You can use a static library with a Swift application. What is the error you're running into?

**Comment by ianbarber** [comment]
Closing - please reopen if you have an update!
