### ISSUE TITLE
Unable to retrieve IdToken and server auth code

### ISSUE THREAD

**Issue by vivekkiran** [googlesamples/google-services#111]
I have gone through the documentation thoroughly, and got my OAuth Client Id and configured it in the sample app and when I try to get get Id token or server auth code, I am getting null.
Kindly help me with this issue.

**Comment by samtstern** [comment]
Is this on Android?

**Comment by hustwht** [comment]
I have the same problem on Android

**Comment by samtstern** [comment]
Without much to go on here, I would guess that you have put an incorrect server client Id into the application.  It should be a **Web** Client ID, not an Android Client ID.

**Comment by samtstern** [comment]
Closing this issue due to old age.  Re-open if you still need assistance.
