### ISSUE TITLE
GCMExampleswift not receiving user notifications but silent notifications.

### ISSUE THREAD

**Issue by madnik** [googlesamples/google-services#114]
My App doesn't receive notifications while app stays in the background. But it does receive when the app comes to foreground. Then I tried the example provided. GCMExampleSwift its the same.

**Comment by ianbarber** [comment]
Check that you uploaded the right APNS certificate for the mode you're testing with (sandbox or production). Foreground delivery is done via a connection to GCM, but the background is over APNS.

**Comment by JolinTeoh88** [comment]
i have same issue as @madnik.

**Comment by ianbarber** [comment]
Did you verify the environment/cert match up?

**Comment by silvolu** [comment]
If environment/cert match up, the other thing to consider is priority: to conserve the battery on the receiving devices, GCM sends the messages with default priority set to normal, which means that the messages is sent at a time that conserves power on the device receiving it. You can explicitly set the priority to *high*, but that will impact the battery life of the receiving device, and should be used only for messages that require realtime interaction from the user. You can find a description of the GCM priority parameter [in this table](https://developers.google.com/cloud-messaging/http-server-ref#table1) and APNs priority [here](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/CommunicatingWIthAPS.html).

**Comment by madnik** [comment]
Yup. So its the priority for me. Setting priority to high made it notified immediately. Would be great if the iOS push demo server project get an update highlighting this priority concern to avoid confusion. I'm closing issue. @JolinTeoh88 does setting priority solved this for you?

**Comment by JolinTeoh88** [comment]
Allow me to describe my current situation. The website is done by using wordpress, and it installed the GCM plugin. For android site that is no problem. But for iOS site, i try to use GCM, for foreground it able to receive the notification alert but when i go to notification list page, there is nothing there. the list was empty. besides that, when the app in background that is nothing at all.

**Comment by madnik** [comment]
Check ur wordpress plugin how to set priority option to high.
