### ISSUE TITLE
iOS: Google SignIn through other Google apps (eg. GooglePlus, Youtube) not working?

### ISSUE THREAD

**Issue by VrasidasP** [googlesamples/google-services#115]
Hello, I'm having trouble making the sign in work smoothly with other Google apps.

I've recently updated Cocoapods and can now install GoogleSignIn via the pod (previously I couldn't because I use use_frameworks! in my Podfile).

I've followed all the steps in the guide, but when I tap the login with Google button, I'm always taken to the webview login, even though I have Youtube and GooglePlus and I'm logged in those.

The login through other Google apps was working in my app previously, although it's been a while since I had tested it.

I've seen posts in stackoverflow (http://stackoverflow.com/questions/31506865/google-sign-in-crashes-on-ios-9-attempting-to-call-canopenurl/31708157#31708157) that point out that we should add LSApplicationQueriesSchemes to the app's plist, but there is no mention about that in the SignIn documentation.

Can we clear this up please? Thanks!

**Comment by ianbarber** [comment]
App switching for sign in is not a recommended process by Apple, so the library is now handling sign in without going to other apps.

**Comment by VrasidasP** [comment]
I see... It was useful that the user didn't have to re-enter the login information... Oh well.
Thank you for your response!
