### ISSUE TITLE
Question: How did you get Safari View Controller to work with authentication in SignIn

### ISSUE THREAD

**Issue by bknope** [googlesamples/google-services#116]
I am working on an application that needs to authenticate the user with their Google account. When I present a SFSafariViewController and the user taps the button to login, the user gets stuck on a white page upon logging in.

However, when I use the Google SignIn library, SFSafariViewController is dismissed properly and the user is not stuck on a white page.

I would like to keep the user in the browser upon logging in (mainly in a WKWebView) but am having problems with the redirect upon authentication.

If I could get some insight into how you are achieving this it would be greatly appreciated

**Comment by ianbarber** [comment]
Why not just use the GIDSignIn library for sign in if you're accessing a Google account?

**Comment by bknope** [comment]
I would love to, but the client I am working for wants to present their website in a web view in app so users aren't forced to go into Safari.

After GIDSignIn successfully logs in, it dismisses the web view or SafariViewController. When then presenting the website in a new view, the user's credentials are not carried over.

Otherwise, inside a WKWebView, when the user tries to login to their account, after they accept the permission screen, they are sent to either a blank page or one that says something along the lines of "Close this window". It is not redirecting back to the website that prompted their login

**Comment by ianbarber** [comment]
Closing: no further comment on implementation details, but good luck with the project!
