### ISSUE TITLE
Displaying Error: "Unfortunately Sign-in Quickstart has stopped"

### ISSUE THREAD

**Issue by murthyvsvn** [googlesamples/google-services#12]
Hi, 

I have followed the steps of integrating the signin sample code to my testing android app and once it starts running i am getting the error: "Unfortunately Sign-in Quickstart has stopped". Screenshot attached for reference.  

Please guide why this error is coming and how it could be fixed. 

Thanks
Narasimha
![screen shot 2015-06-12 at 11 55 35](https://cloud.githubusercontent.com/assets/4513914/8124500/ca8aa94c-10f9-11e5-82a1-9c1dacf406dc.png)

**Comment by mnemonicflow** [comment]
@murthyvsvn Without a strack trace it is impossible to know what might be the cause, so please provide one. http://imgur.com/jacoj

**Comment by ianbarber** [comment]
+1, please add the trace from the log output

**Comment by murthyvsvn** [comment]
Hi Ian,

I really appreciate your attention and for the reminder.

I got the solution today morning with the help of a friend.  If still any
issue pops out, I will definitely share the log output.

Thanks once again,
Narasimha
