### ISSUE TITLE
Category isn't showing in notificaion

### ISSUE THREAD

**Issue by washaq** [googlesamples/google-services#120]
Hi
I am trying to show notification with UIMutableUserNotificationCategory in IOS but it only show default cross button not showing other buttons then i add in Category. It should be showing like this bellow. Is it possible or its not possible with GCM. This is how i add category in application didfinishlaunching
how can i pass category in gcm notificaion { "aps": { "badge": 1, "alert": "Hello world!", “category”: “SHARE_CATEGORY” } }
// Category
        let releaseRoomCategory = UIMutableUserNotificationCategory()
        releaseRoomCategory.identifier = categoryID
        
        releaseRoomCategory.setActions([yesAction, noAction],
            forContext: UIUserNotificationActionContext.Minimal)
        releaseRoomCategory.setActions([yesAction, noAction], forContext: .Default)
        
        let settings: UIUserNotificationSettings =
        UIUserNotificationSettings(forTypes: [.Alert, .Badge, .Sound], categories:  NSSet(object: releaseRoomCategory) as? Set<UIUserNotificationCategory>)
        application.registerUserNotificationSettings(settings)
        application.registerForRemoteNotifications()

this is how it suppose to show
<img width="835" alt="screen shot 2015-12-09 at 12 17 52 pm" src="https://cloud.githubusercontent.com/assets/10823286/11679009/fa7e01d2-9e6e-11e5-9d2c-4c7086be7dd5.png">

**Comment by silvolu** [comment]
Hi,

You need to set **click-action** to the value you want for category, so for example if you have in your payload:

    {"to": <reg_token>, "notification": {"body": "Hello from GCM", "click-action": "SHARE"}}

It will be delivered as:

    {"aps": {"alert": "Hello from GCM", "category": "SHARE"}}

**Comment by washaq** [comment]
Thanks Silvolu,
Actually i need that urgently did find it before anywhere so i switch back to apns.
Thanks again it will help me in future
