### ISSUE TITLE
Error:Execution failed for task ':app:processDebugGoogleServices'. > File google-services.json is missing from module root folder. The Google Services Plugin cannot function without it.

### ISSUE THREAD

**Issue by Arunkarthicknallasami** [googlesamples/google-services#121]
I have got this issue while importing signin project. I resolved it by replacing play services version 1.5.0 with 1.3.1. If its a wrong solution kindly help on this case

**Comment by samtstern** [comment]
I don't think you actually resolved the issue, it may just be that the older version (1.3.1) does not crash when it can't find the `google-services.json` file.

Go to developers.google.com/mobile/add and follow the instructions to download a google-services.json file for your app, and then put it into the `app/` folder.

**Comment by Arunkarthicknallasami** [comment]
Thank u I will do that                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Sam SternSent: Thursday 10 December 2015 5:49 AMTo: googlesamples/google-servicesReply To: googlesamples/google-servicesCc: ArunkarthickSubject: Re: [google-services] Error:Execution failed for task ':app:processDebugGoogleServices'. > File google-services.json is missing from module root folder. The Google Services Plugin cannot function without it. (#121)I don't think you actually resolved the issue, it may just be that the older version (1.3.1) does not crash when it can't find the google-services.json file.

Go to developers.google.com/mobile/add and follow the instructions to download a google-services.json file for your app, and then put it into the app/ folder.

—Reply to this email directly or view it on GitHub.

**Comment by IgorGanapolsky** [comment]
Is there an updated solution to this problem?  I am facing it now, I placed google-services.json file in my /app module directory.  Still getting this error!

**Comment by abdularshad06** [comment]
is there any update i am facing same issue.

**Comment by Pckua** [comment]
I have this problem help: Error: Execution failed for task ': app: processDebugGoogleServices'.
> Malformed root json

**Comment by Harika511** [comment]
Am facing same problem, I have already added file under suggested patha

**Comment by prudhvir3ddy** [comment]
@Pckua got any fix ?

**Comment by rnagar3434** [comment]
I am also facing same problem, how can you fix it? 

Google-services.json this file I paste in project /app folder
But still getting this error

**Comment by BawarX** [comment]
I've faced this problem, and I've only changed the json file name 
before: google-services (1).json 
after: google-services.json
