### ISSUE TITLE
google-services.json for different productFlavors

### ISSUE THREAD

**Issue by SteveMobile** [googlesamples/google-services#123]
Help!!!
my problem is I have different productFlavors with different applicationId/packageName and different GCM Project Id. The 'google-services.json' have to be put at the /app/google-services.json not the flavors folder.

http://stackoverflow.com/questions/30772201/google-services-json-for-different-productflavors

**Comment by samtstern** [comment]
Duplicate of #54, please discuss there.

**Comment by samtstern** [comment]
See #54 for an update.
