### ISSUE TITLE
Get User Data from GPGManager and GIDSignIn

### ISSUE THREAD

**Issue by adrianha** [googlesamples/google-services#124]
Is it possible to get user data from GPGManager class since it doesnt has any methods or properties that related to user data?
I can get the user data If i used GIDSignIn's delegate for Signing In but when i invoke [GPGManager SharedInstance].isSignedIn the result is always NO.
Any solutions to fix this problem?
Thanks

**Comment by ianbarber** [comment]
@gguuss any ideas? I've not tried the games SDK recently.

**Comment by mychaelgo** [comment]
+1

**Comment by gguuss** [comment]
@adrianha / @mychaelgo - you might want to try starting from the Play Games Services samples here:

https://github.com/playgameservices/ios-basic-samples

The simplest example is ButtonClicker.  After you have signed the user in, you can use SSO to retrieve the user.
