### ISSUE TITLE
Can't to import Google/SignIn into bridge file

### ISSUE THREAD

**Issue by Samback** [googlesamples/google-services#125]
Hi,
I have faced with an issue that when I try to make 
```#import <Google/SignIn.h>```
<img width="519" alt="screen shot 2015-12-16 at 5 52 33 pm" src="https://cloud.githubusercontent.com/assets/768673/11845713/d228f9c6-a41d-11e5-96a0-f975d4399dcf.png">
and can't to figure out how to resolve it. 
I have installed it via cocoa pods
pod 'Google/SignIn'

**Comment by ianbarber** [comment]
Are you opening the the xcworkspace file, and does the Google pod appear in the pods project?

**Comment by groschovskiy** [comment]
Update pod in Google SignIn folder and try again. If problem repeat try clean project "Product -> Clean".

**Comment by Samback** [comment]
It was automatically fixed after I had update my cocoa pods (gem install cocoapods)
