### ISSUE TITLE
How can we switch dev google-services.json to google-services.json when they exsits different flavour?

### ISSUE THREAD

**Issue by nickgao1986** [googlesamples/google-services#127]
help,How can we switch dev google-services.json to google-services.json when they exsits different flavour? We only have one goolge-services.json file in our project

**Comment by samtstern** [comment]
Check out #54 for some information on how to use build flavors.  Official documentation coming soon.

Summary: the `google-services.json` contains information for all build flavors and if you put a copy of the file in each `app/src/<flavor>` directory, the plugin will be smart enough to read the right section of the file.

**Comment by samtstern** [comment]
Note that you have to go through the developers.google.com/mobile/add flow once for each flavor.  Each time the `google-services.json` file you get will contain the information from previous runs of the wizard flow, so you'll want to always only keep the most recent copy.
