### ISSUE TITLE
Google sigin in :: gives error code 8 and message null when using signed apk

### ISSUE THREAD

**Issue by ikartiks** [googlesamples/google-services#129]
my play services.json is proper and i provided sha1 key and tested on moto G 2 phone with signed apk,still it gives me error code 8 when i do result.getStatus().getStatusCode() and result.getStatus().getStatusMessage() is null

**Comment by samtstern** [comment]
[CommonStatusCodes.INTERNAL_ERROR](https://developers.google.com/android/reference/com/google/android/gms/common/api/CommonStatusCodes) has value 8.  Did you sideload Google Play Services onto this device?

**Comment by ikartiks** [comment]
Sorry , looks like error when refracting package name , it didn't update in id section of build.gradle   .Once that was fixed and updated Google-services.json issue was resolved
