### ISSUE TITLE
White Bar appears before Account chooser dialog in Android

### ISSUE THREAD

**Issue by srinuch1981** [googlesamples/google-services#130]
Hi , 

In Android signin application when we click on SignIn button white bar appears in screen before Account chooser dialog. Please correct it

**Comment by samtstern** [comment]
@srinuch1981 I have never seen this ... could you capture a screenshot and post it here?

**Comment by niteshgoel** [comment]
I am getting the same bar over my progress dialog. I am showing my custom progress dialog. Screen shot:
![img_0517](https://cloud.githubusercontent.com/assets/1326929/12448825/afd4c8ea-bf9e-11e5-9f2e-eaae3f4ecaa8.JPG)

**Comment by samtstern** [comment]
Thank you for the photograph.  I will report this to the proper team.  Could you try to provide more information such as:

  * Device make and model
  * Android OS version and Google Play Services version
  * Logcat output from before/after the bar shows
  * Steps to reproduce (if you know how)

**Comment by niteshgoel** [comment]
I am getting on all devices on which i am testing. google play service is 8.3. 
[Archive.zip](https://github.com/googlesamples/google-services/files/97711/Archive.zip)

**Comment by niteshgoel** [comment]
Any update on this??

**Comment by samtstern** [comment]
@niteshgoel we are investigating it.  Unfortunately I can't offer a short time frame on a possible fix.  This would be an issue in the Google Play Services system APK (if it is an issue) and that APK has a ~months release cycle.

**Comment by bdipak** [comment]
Hi. Is there any update on this ? I am also facing the same issue. Please confirm if the issue is root caused or we need to provide any information.

**Comment by samtstern** [comment]
Haven't seen any reports in ~9 months.  I once reproduced this but can't remember how any more.  Since I am cleaning up old issues I am going to close this, if anyone still sees this and knows how to make it happen I am happy to investigate.
