### ISSUE TITLE
google-services.json

### ISSUE THREAD

**Issue by twinone** [googlesamples/google-services#133]
I've been trying to implement gcm in an app, following the guide [here](https://developers.google.com/cloud-messaging/android/start), which has a big blue button that says GET A CONFIGURATION FILE, and redirects [here](https://developers.google.com/mobile/add?platform=android&cntapi=gcm&cntapp=Default%20Demo%20App&cntpkg=gcm.play.android.samples.com.gcmquickstart&cnturl=https:%2F%2Fdevelopers.google.com%2Fcloud-messaging%2Fandroid%2Fstart%3Fconfigured%3Dtrue&cntlbl=Continue%20with%20Try%20Cloud%20Messaging)

That page gets stuck trying to load the json.

**Comment by samtstern** [comment]
@twinone sorry to hear you're having an issue.  We haven't received other reports of this, are you still seeing this issue?  If so, could you try to see if there are any errors appearing in the Chrome Developer Console when the page "gets stuck".

If you need help working with the Chrome console, I can provide instructions.

**Comment by twinone** [comment]
I get the following errors in the console:
about:blank:1
Refused to display 'https://accounts.google.com/ServiceLogin?service=cloudconsole&osid=1&passiv…%26cntlbl%3DContinue%2Bwith%2BTry%2BCloud%2BMessaging%26cntapi%3Dgcm&hl=en' in a frame because it set 'X-Frame-Options' to 'DENY'.

And then:
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://console.developers.google.com') does not match the recipient window's origin ('null').
(anonymous function)	@	script_foot.js:348
n.event.dispatch	@	jquery.min.js:3
r.handle	@	jquery.min.js:3

Thanks!

**Comment by samtstern** [comment]
Filed a bug about this, thanks for the information so far!

**Comment by samtstern** [comment]
@twinone we're having some trouble reproducing the situation, could you provide the following info:

1) What browser are you using?
2) When you say "got stuck", which page did you end up on? A screenshot will be helpful.
3) Does this still happen to you in an Incognito Chrome window?

**Comment by twinone** [comment]
I'm on Chrome.
On incognito mode it redirects me to the google accounts page to sign in, after signing in, it gets to the same situation. I've tried this with two accounts, one is associated with a google play developer account, the other not.

Here's the screenshot:
![Screenshot](https://cloud.githubusercontent.com/assets/4309591/12101820/12604e0e-b337-11e5-9d63-55b9019039e4.png)

**Comment by jonas-koeritz** [comment]
Same here.

**Comment by samtstern** [comment]
I believe there is a fix for this issue going out today, thanks for your
help in identifying it.  Please reply back to this thread if you can't get
it working by the end of the day.

**Comment by samtstern** [comment]
The backend team has informed me that the fix for this issue is deployed, and I can no longer reproduce the issue.  Please re-open if you experience this again, and thanks again for the report.

**Comment by twinone** [comment]
Just to confirm, it works now. Thanks for the quick fix!
