### ISSUE TITLE
How to get dob,gender,location from GoogleSignInResult

### ISSUE THREAD

**Issue by tuhin10** [googlesamples/google-services#135]
How can I get dob,gender,location from GoogleSignInResult ? So far I am able to get id,Name,prof pic id.
I am using the latest build 8.4.0

**Comment by samtstern** [comment]
That information is not contained in GoogleSignInResult and does not fall under the basic "profile" scope.  If you need that information, you will either have to prompt the user or request the Google+ Profile scope and use the `getCurrentPerson
