### ISSUE TITLE
GoogleUser.getAuthResponse() doesn't contains access_token

### ISSUE THREAD

**Issue by swapnilmishra** [googlesamples/google-services#136]
Referring to the api doc at https://developers.google.com/identity/sign-in/web/reference#googleauthsignin.
We are using google plus JS library.

Post login GoogleUser.getAuthResponse() doesn't contain *access_token* so we have to access internal object to get the *access_token*. Now the problem is names of the internal objects keep changing resulting in broken gplus login many times.

Is there a reliable way to get the *access_token* without accessing internal objects ?

**Comment by samtstern** [comment]
@swapnilmishra sorry this repo only deals with Android and iOS samples.  Please post this question on StackOverflow for maximum exposure/beneifit.
