### ISSUE TITLE
Google sign in is not working in android m

### ISSUE THREAD

**Issue by Prashanthlkv** [googlesamples/google-services#138]
Google sign in is not working in android m, but works for lower versions

**Comment by samtstern** [comment]
Are you running the sample app provided here, or your own application?  Can you describe in what way it does not work on Android M?

**Comment by Prashanthlkv** [comment]
I am creating my own application. 
1. Created project in google console and enabled the  Google+ API.
2. Added the configuration file in my project generated by using google consloe.
3. Added below dependencies 
        'com.google.android.gms:play-services-plus:8.4.0'
        'com.google.android.gms:play-services-auth:8.4.0'

4. Followed all the steps, still it's not working only in Android M.

**Comment by samtstern** [comment]
Can you try running the sample from this repository on your Android M device and confirm that it works?  It's hard to debug your own app, which may have different error cases.

**Comment by Prashanthlkv** [comment]
I created new project id in google console and now its working fine. Thanks for your valuable feedback and quick response.
