### ISSUE TITLE
Help GCM is unstable in China

### ISSUE THREAD

**Issue by nickgao1986** [googlesamples/google-services#139]
Hi,I integrate gcm in our app, but sometimes we can't receive gcm message, Is there a way to solve this problem?

**Comment by ianbarber** [comment]
On the server side you should be able to check for message receipts, and resend after a certain amount of time if messages weren't delivered. 

You'll need to use the XMPP based connection, but then you should be able to detect whether there have been receive failures, and resend them. https://developers.google.com/cloud-messaging/ccs#receipts

**Comment by ianbarber** [comment]
There is also some diagnostic information in the Play Console which may help: https://developers.google.com/cloud-messaging/diagnostics - if you get any more specifics back about the errors, please reopen and we can investigate further.
