### ISSUE TITLE
compilation issue for GCM code

### ISSUE THREAD

**Issue by pashtika** [googlesamples/google-services#14]
When I import this source code, I get the following error. Please help me how to solve this error

`A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find any version that matches com.google.android.gms:play-services-gcm:7.5.+.
     Searched in the following locations:
         https://jcenter.bintray.com/com/google/android/gms/play-services-gcm/maven-metadata.xml
         https://jcenter.bintray.com/com/google/android/gms/play-services-gcm/
     Required by:
         gcm:app:unspecified
   > Could not find com.android.support:appcompat-v7:22.1.1.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/appcompat-v7/22.1.1/appcompat-v7-22.1.1.pom
         https://jcenter.bintray.com/com/android/support/appcompat-v7/22.1.1/appcompat-v7-22.1.1.jar
     Required by:
         gcm:app:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.`

**Comment by kroikie** [comment]
It looks like you need to update the libraries in the SDK manager. Once updated the versions of play-services and appcompat should be available.
