### ISSUE TITLE
Google App Invites For Android SMS OK Email Not Sent After Play Services 8.3 Update

### ISSUE THREAD

**Issue by qaiserhabib** [googlesamples/google-services#143]
My app is in closed alpha. I tested release & debug keys and the app invite accepts emails tells me invites were sent but I don't receive the emails. SMS work ok.

This was working fine but I had to update android studio 2.0 preview and play services 8.3 and it stopped working. 

I tested on Genymotion, Nexus 5 and Galaxy s6. Same issue. 

I tested the app invites sample and that works fine on all devices.

I deleted and recreated my API keys hoping that would be an issue, no luck.

Is there a way to diagnose such issues? I don't see any error messages in logcat. I'm suspecting there's some message on your end that is not propagated. Can you guys please take a look?

Package: com.fitzo.android

**Comment by samtstern** [comment]
@qaiserhabib so in the `onActivityResuly

**Comment by samtstern** [comment]
You can enable debug logging with 
`adb shell setprop log.tag.AppInviteAgent VERBOSE`

Then you will see more information in your `logcat`.  Also try sending to a variety of email addresses to make sure the emails are not being caught in the spam filter.

**Comment by ianbarber** [comment]
Closing as AppInvites has now moved to Firebase
