### ISSUE TITLE
Google sigin in :: gives error code 8 and message null on Nexus 5

### ISSUE THREAD

**Issue by niteshgoel** [googlesamples/google-services#144]
I have added services.json and i provided sha1 key and tested on samsung s3 phone, still it gives me error code 8 when i do result.getStatus().getStatusCode() and result.getStatus().getStatusMessage() is null on Nexus 5 running marshmallows.

**Comment by samtstern** [comment]
@niteshgoel are you saying that you only see this issue on the Nexus 5, or you see it on both the Nexus and the Samsung Galaxy S3 devices?

**Comment by niteshgoel** [comment]
Only on Nexus 5 and on one of my system only. hey i have already attached my code in another question (showing bar on login.)

**Comment by samtstern** [comment]
What is the version of Google Play Services on each device?  Did you install Google Play Services manually via apkmirror or similar? 

Code 8 is `CommonStatusCodes.INTERNAL_ERROR` so it's hard to diagnose when it is device specific.

**Comment by niteshgoel** [comment]
How to get the Google play service version on device. On Studio it is 8.3.
no i have not install Google Play Services manually.

**Comment by samtstern** [comment]
You can go to Settings > Apps > Google Play Services to get the version.

**Comment by niteshgoel** [comment]
Google Play Services version on s3  and and nexus 5 is : 8.4.89

**Comment by 1step** [comment]
I have same problem, it's working very well on my note 2 (Android 4.4.4), but always get INTERNAL_ERROR on my Note 5 (Android 5.0.2)

**Comment by jamilex** [comment]
Same thing happens here. It gives me error code 8 on Moto G only, the code works on other devices.

**Comment by samtstern** [comment]
@niteshgoel a few questions so we can debug this:

**Comment by niteshgoel** [comment]
@samtstern : answers
1. Which adb log you are talking about.The one which I have attached in another question was from s3.
2. Yes.
3. I can not tell you the name. How i can test on a users phone about "Auto-sync data" from my code.
4. After this i am getting 12501 error code from (googleSignInResult.getStatus().getStatusCode()) in handleSignInResult(GoogleSignInResult result) function.

 NOTE : Now I have tested on few more devices with different account and I am getting the same error. Please help me asap as I need to launch my application And with this bug i can not.

**Comment by niteshgoel** [comment]
@samtstern please tell me if we can have a live conversation to debug this.

**Comment by samtstern** [comment]
@niteshgoel have you ever gotten a successful sign in on this device?  Also could you provide a [full `adb bugreport`](http://stackoverflow.com/questions/26789107/how-to-write-an-android-bug-report-to-a-file-via-adb) for a situation where you get the 12501 response?  Email it to samstern@google.com and we will analyze it.

**Comment by niteshgoel** [comment]
@samtstern: I have mailed you all the details.

**Comment by samtstern** [comment]
For all who are getting this error, make sure you have registered **ALL** of your signing keystores in the developers.google.com/mobile/add flow.  Failing to register one of your keystores (such as your production keystore) will result in INTERNAL_ERROR if you ask for the default `GoogleSignInOptions` configuration.

**Comment by niteshgoel** [comment]
@samtstern : Yes there was one keystore missing but From another keystore which was already added,  it is working on one device but not on nexus5 as i am building from the same machine.

**Comment by isaisachen** [comment]
@niteshgoel Could you double check the version on Nexus 5? 

There's an easy way for you to tell whether it's registered correctly. Change your GoogleSignInOptions to be:
GoogleSignInOptions gso = 
        new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                .requestEmail()
                .requestScopes(Scopes.DRIVE_APPFOLDER)
                .build();

If your version isn't registered correctly (package name + sha1 key), you will see one row saying  "Unregistered Android application" on consent dialog. See attached screenshot.
<img width="327" alt="screen shot 2016-01-27 at 11 18 06 pm" src="https://cloud.githubusercontent.com/assets/16887501/12637715/48843c76-c54c-11e5-8941-571189bf4888.png">

**Comment by 1step** [comment]
@samtstern FYI;
I just build & run the sample code of yours, and it's working very well without getting INTERNAL_ERROR @ device:
* Samsung S4 (Android Jelly Bean 4.2.2)
* Samsung Note 2 (Android Kit Kat 4.4.2)
* Samsung Mega 5.8 (Android Jelly Bean 4.2.2)

but get INTERNAL_ERROR @ device:
* Samsung Note 5 (Android 5.1.1)
* Samsung J7 (Android 5.1.1)
* Xiaomi Mi4i (MIUI 7.1 Android 5.0.2)


GoogleSignInOptions gso = new GoogleSignInOptions.Builder()
                .requestEmail()
                .build();
There is no error when i using this code, but I only can get the email data. I think I already registered ALL of my signing keystores. Thanks.

**Comment by samtstern** [comment]
@1step are you running the exact same APK on each device? Can you try diagnosing possible registration errors by using the method @isaisachen suggested?

**Comment by samtstern** [comment]
https://drive.google.com/file/d/0B3sKMOzQgrmwUXdnNFV5U0NEbWc/view?usp=sharing

That is a link to an APK I just built from source, signed with my own debug keystore.  The SignIn and SignInWithDrive activities should work.

Please load that APK onto your devices (`adb install -r -d`) and then test.  If you still get an error then we can continue to debug.  If you do not get an error with my APK, then it is almost certain that your keystores are not properly registered.

**Comment by 1step** [comment]
@samtstern ok, your it's working very well. but i still don't understand, why my keystore doesn't work with android os >= 5. let me check it again. Thanks again mate.

**Comment by isaisachen** [comment]
@1step Any chance you have multiple key stores? If you unzip your built-out apk, in META\INF folder, you can find a CERT.DSA (or CERT.RSA) file, run below command to find out the exact SHA1 of the cert you used to sign your apk:
keytool -printcert -file <path to your CERT.DSA or CERT.RSA>

**Comment by niteshgoel** [comment]
@samtstern @isaisachen : Hi again, As you mention previously ... I have added all the key story properly.Though the issue was resolved on many devices except one but I ignored it that time and put my application on play store. However, I have added google analytics. And I can tell you that I have received 3 unique events of  error code: 8 and one unique event of error code: 12501 within one day around 100 installs. Please guide me what to do next.

**Comment by niteshgoel** [comment]
the count is now 12.
error code 8 : 5
error code 12501 :7

**Comment by isaisachen** [comment]
@niteshgoel 12501 is [SIGN_IN_CANCELLED](https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInStatusCodes.html#SIGN_IN_CANCELLED) and probably because your user clicked away from the account chooser.

8 is INTERNAL_ERROR and not expected here. Two questions:
1. Is your app only published in Google Play store? (e.g. not through Amazon app store etc)
2. Could you share your latest code w/ Analytics logging? I saw signOut/revoke code in your attached source code (in another thread like you mentioned). These are not necessary for the sign-in process and I just want to make sure the errors don't come from those calls (even though it's not expected to have INTERNAL_ERROR for those calls either).

**Comment by niteshgoel** [comment]
Yes, my app published only in Google play store.

I have added signout/revoke code because on activity stop I am revoking the access as I do not need it any longer.PFA the code.
[GPlusUtilNew.java.zip](https://github.com/googlesamples/google-services/files/122662/GPlusUtilNew.java.zip)

**Comment by samtstern** [comment]
Revoking access is not a lightweight operation and shouldn't be done on
every Activity stop.  You should only do it when the user explicitly asks
to sign out and revoke access.

**Comment by niteshgoel** [comment]
this is todays screenshot. Got 2 times errorcode:8

![20160209_160243](https://cloud.githubusercontent.com/assets/1326929/12915997/06a9c20e-cf55-11e5-8975-7c9ac45e47a5.jpg)

**Comment by samtstern** [comment]
@niteshgoel it has been a while since there has been an update in this thread, I am going to close the issue as I am doing some cleanup.  If you are still having trouble with this issue feel free to re-open.

**Comment by scostira** [comment]
I to all
 I have the same problem and i can´t understand what happen with my project. My app work verry nice with android <5 but with androdid >5.Do not work. My key are registery and my apk have the key correcty. 

> public class SignInActivity extends AppCompatActivity implements
>         GoogleApiClient.OnConnectionFailedListener,
>         View.OnClickListener {
> 
>     private static final String TAG = "SignInActivity";
>     private static final int RC_SIGN_IN = 9001;
> 
>     private GoogleApiClient mGoogleApiClient;
>     private TextView mStatusTextView;
>     private ProgressDialog mProgressDialog;
> 
>     @Override
>     protected void onCreate(Bundle savedInstanceState) {
>         super.onCreate(savedInstanceState);
>         setContentView(activity_main_signin);
> 
>         // Views
>         mStatusTextView = (TextView) findViewById(R.id.status);
> 
>         // Button listeners
>         findViewById(R.id.sign_in_button).setOnClickListener(this);
>         findViewById(R.id.sign_out_button).setOnClickListener(this);
>         findViewById(R.id.disconnect_button).setOnClickListener(this);
> 
>         // [START configure_signin]
>         // Configure sign-in to request the user's ID, email address, and basic
>         // profile. ID and basic profile are included in DEFAULT_SIGN_IN.
>         GoogleSignInOptions gso = new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
>                /* .requestScopes(new Scope(Scopes.EMAIL))*/
>                 .requestIdToken("199774985284-ok51195p6vik9579hr9rmde1jkhfmo1s.apps.googleusercontent.com")
>                 .requestScopes(new Scope(Scopes.DRIVE_APPFOLDER))
>                 .requestEmail()
> 
>                  /*.requestEmail()
>                   .requestScopes(new Scope(Scopes.EMAIL))
>                   .requestScopes(new Scope(Scopes.DRIVE_APPFOLDER))*/
>                 .build();
> 
>         Log.d(TAG,"GSO STARTUP"+ gso.toString());
>         // [END configure_signin]
> 
>         // [START build_client]
>         // Build a GoogleApiClient with access to the Google Sign-In API and the
>         // options specified by gso.
>         // ATTENTION: This "addApi(AppIndex.API)"was auto-generated to implement the App Indexing API.
>         // See https://g.co/AppIndexing/AndroidStudio for more information.
>         mGoogleApiClient = new GoogleApiClient.Builder(this)
>                 .enableAutoManage(this /* FragmentActivity */, this /* OnConnectionFailedListener */)
>                 .addApi(Auth.GOOGLE_SIGN_IN_API, gso)
>                 .addApi(AppIndex.API).build();
>         // [END build_client]
>         Log.d(TAG, "GSO "+ gso.getAccount() + " "+ mGoogleApiClient.isConnecting());
> 
>         // [START customize_button]
>         // Customize sign-in button. The sign-in button can be displayed in
>         // multiple sizes and color schemes. It can also be contextually
>         // rendered based on the requested scopes. For example. a red button may
>         // be displayed when Google+ scopes are requested, but a white button
>         // may be displayed when only basic profile is requested. Try adding the
>         // Scopes.PLUS_LOGIN scope to the GoogleSignInOptions to see the
>         // difference.
>         SignInButton signInButton = (SignInButton) findViewById(R.id.sign_in_button);
>         signInButton.setSize(SignInButton.SIZE_STANDARD);
>         signInButton.setScopes(gso.getScopeArray());
>         // [END customize_button]
>     }
> 
>     @Override
>     public void onStart() {
>         super.onStart();// ATTENTION: This was auto-generated to implement the App Indexing API.
> // See https://g.co/AppIndexing/AndroidStudio for more information.
>         mGoogleApiClient.connect();
> 
>         OptionalPendingResult<GoogleSignInResult> opr = Auth.GoogleSignInApi.silentSignIn(mGoogleApiClient);
>         if (opr.isDone()) {
>             // If the user's cached credentials are valid, the OptionalPendingResult will be "done"
>             // and the GoogleSignInResult will be available instantly.
>             Log.d(TAG, "Got cached sign-in");
>             GoogleSignInResult result = opr.get();
>             handleSignInResult(result);
>         } else {
>             // If the user has not previously signed in on this device or the sign-in has expired,
>             // this asynchronous branch will attempt to sign in the user silently.  Cross-device
>             // single sign-on will occur in this branch.
>             showProgressDialog();
>             opr.setResultCallback(new ResultCallback<GoogleSignInResult>() {
>                 @Override
>                 public void onResult(GoogleSignInResult googleSignInResult) {
>                     hideProgressDialog();
>                     handleSignInResult(googleSignInResult);
>                 }
>             });
>         }
>         // ATTENTION: This was auto-generated to implement the App Indexing API.
>         // See https://g.co/AppIndexing/AndroidStudio for more information.
>         AppIndex.AppIndexApi.start(mGoogleApiClient, getIndexApiAction());
>     }
> 
>     // [START onActivityResult]
>     @Override
>     public void onActivityResult(int requestCode, int resultCode, Intent data) {
>         super.onActivityResult(requestCode, resultCode, data);
>         Log.d(TAG, "Requestcode "+ requestCode + " resultcode="+ resultCode + " data="+ data.getBundleExtra("Email"));
>         // Result returned from launching the Intent from GoogleSignInApi.getSignInIntent(...);
>         if (requestCode == RC_SIGN_IN) {
>             GoogleSignInResult result = Auth.GoogleSignInApi.getSignInResultFromIntent(data);
>             handleSignInResult(result);
>         }
>     }
>     // [END onActivityResult]
> 
>     // [START handleSignInResult]
>     private void handleSignInResult(GoogleSignInResult result) {
>         Log.d(TAG, "handleSignInResult:" + result.getStatus().getStatusCode());
>         if (result.isSuccess()) {
>             // Signed in successfully, show authenticated UI.
>             GoogleSignInAccount acct = result.getSignInAccount();
>             String email = (String) acct.getEmail();
>             String[] part= email.split("@");
>             if( part[1].equals("mydomain")){
>                
>                 // If the user is valid
>                 Intent logado = new Intent(this,RecursosBVActivity.class);
>                 logado.putExtra("user",part[0]);
>                 logado.putExtra("token",acct.getIdToken());
>                 startActivity(logado);
>                 updateUI(true);
> 
>             }else{
>                   signOut();
>                 updateUI(false);
>             }
>         } else {
>             // Signed out, show unauthenticated UI.
>             signOut();
>             updateUI(false);
>         }
>     }
>     // [END handleSignInResult]
> 
>     // [START signIn]
>     private void signIn() {
>         Intent signInIntent = Auth.GoogleSignInApi.getSignInIntent(mGoogleApiClient);
>         startActivityForResult(signInIntent, RC_SIGN_IN);
>     }
>     // [END signIn]
> 
>     // [START signOut]
>     private void signOut() {
>         Auth.GoogleSignInApi.signOut(mGoogleApiClient).setResultCallback(
>                 new ResultCallback<Status>() {
>                     @Override
>                     public void onResult(Status status) {
>                         // [START_EXCLUDE]
>                         updateUI(false);
>                         // [END_EXCLUDE]
>                     }
>                 });
>     }
>     // [END signOut]
> 
>     // [START revokeAccess]
>     private void revokeAccess() {
>         Auth.GoogleSignInApi.revokeAccess(mGoogleApiClient).setResultCallback(
>                 new ResultCallback<Status>() {
>                     @Override
>                     public void onResult(Status status) {
>                         // [START_EXCLUDE]
>                         updateUI(false);
>                         // [END_EXCLUDE]
>                     }
>                 });
>     }
>     // [END revokeAccess]
> 
>     @Override
>     public void onConnectionFailed(ConnectionResult connectionResult) {
>         // An unresolvable error has occurred and Google APIs (including Sign-In) will not
>         // be available.
>         Log.d(TAG, "onConnectionFailed:" + connectionResult);
>     }
> 
>     private void showProgressDialog() {
>         if (mProgressDialog == null) {
>             mProgressDialog = new ProgressDialog(this);
>             mProgressDialog.setMessage(getString(R.string.loading));
>             mProgressDialog.setIndeterminate(true);
>         }
> 
>         mProgressDialog.show();
>     }
> 
>     private void hideProgressDialog() {
>         if (mProgressDialog != null && mProgressDialog.isShowing()) {
>             mProgressDialog.hide();
>         }
>     }
> 
>     private void updateUI(boolean signedIn) {
>         if (signedIn) {
>             findViewById(R.id.sign_in_button).setVisibility(View.GONE);
>             findViewById(R.id.sign_out_and_disconnect).setVisibility(View.VISIBLE);
>         } else {
>             mStatusTextView.setText(R.string.signed_out);
> 
>             findViewById(R.id.sign_in_button).setVisibility(View.VISIBLE);
>             findViewById(R.id.sign_out_and_disconnect).setVisibility(View.GONE);
>         }
>     }
> 
>     @Override
>     public void onClick(View v) {
>         switch (v.getId()) {
>             case R.id.sign_in_button:
>                 signIn();
>                 break;
>             case R.id.sign_out_button:
>                 signOut();
>                 break;
>             case R.id.disconnect_button:
>                 revokeAccess();
>                 break;
>         }
>     }
> 
>     /**
>      * ATTENTION: This was auto-generated to implement the App Indexing API.
>      * See https://g.co/AppIndexing/AndroidStudio for more information.
>      */
>     public Action getIndexApiAction() {
>         Thing object = new Thing.Builder()
>                 .setName("SignIn Page") // TODO: Define a title for the content shown.
>                 // TODO: Make sure this auto-generated URL is correct.
>                 .setUrl(Uri.parse("http://[ENTER-YOUR-URL-HERE]"))
>                 .build();
>         return new Action.Builder(Action.TYPE_VIEW)
>                 .setObject(object)
>                 .setActionStatus(Action.STATUS_TYPE_COMPLETED)
>                 .build();
>     }
> 
>     @Override
>     public void onStop() {
>         super.onStop();
> 
>         // ATTENTION: This was auto-generated to implement the App Indexing API.
>         // See https://g.co/AppIndexing/AndroidStudio for more information.
>         AppIndex.AppIndexApi.end(mGoogleApiClient, getIndexApiAction());
>         mGoogleApiClient.disconnect();
>     }
> }

Please some one help me.

**Comment by niteshgoel** [comment]
@samtstern samtstern The issue is still there and it is keep on getting worst. Here is the latest report from google analytics from last month.

![screen shot 2016-11-06 at 12 18 15](https://cloud.githubusercontent.com/assets/1326929/20035857/5982ca84-a41b-11e6-8ec1-de86e7340fad.png)

**Comment by niteshgoel** [comment]
I am not able to reopen this issue. Please do so.

**Comment by isaisachen** [comment]
@niteshgoel 12501 is SIGN_IN_CANCELLED. If user gives up sign-in with Google, e.g. click away or cancelling the consent dialog, you will get 12501. You can try yourself. So it's not a issue if you have 12501 logged?

**Comment by isaisachen** [comment]
@scostira  "My app work very nice with android <5 but with androdid =>5.Do not work" - From log? Or you can repro? What version of Google Play services SDK are you using?

**Comment by niteshgoel** [comment]
@isaisachen I understand about 12501 but what about error code 8?

**Comment by isaisachen** [comment]
@niteshgoel 8 is INTERNAL_ERROR. One case we should have returned a more precise error that we didn't is: if Play Store / Google Play services is not available (or too old version), you could still get a sign-in intent, but the sign-in intent would fail (onActivityResult code path) and you would get INTERNAL_ERROR.

Based on another Github discussion, you did get some Xiaomi users. Do you distribute your app outside of Google Play?

**Comment by igorregis** [comment]
I am experiencing the same error with my App. It's available throught play store only and some of my users get this error:

Result content = Error code: 8 - Error message: null - Resolution: null

As you can see the image from my Crashlytics report, this error has happened 94 times for the past 90 days. I already placed a message directing the user to use Facebook Login when the error occurs but not all of the are willing to do so.

![errorlogingoogle](https://cloud.githubusercontent.com/assets/6870496/22488991/402a7526-e7fc-11e6-8c3e-ea6e8e45fb24.png)

This problem happens with devices from various brands but not allways. A outdated playservices could be the source of all this this?

@samtstern and @isaisachen  Could you reopen the issue?

**Comment by ianlintner-wf** [comment]
So I have seen issues with business/gsuite/sso accounts.

e.g. I sign in with my personal account into my app it works perfectly. I sign in with my corporate gsuite account and it throws 12501. I am guessing if I used web client id/android client id from the api console that was created by my company it would work.

I am going to talk to the account administrator to work out this out and maybe contact Google support if we can't figure out the permissions.

**Comment by RameshRavone** [comment]
Well, code=8 is INTERNAL_ERROR, so this is little tough to figure things out but I'll look into it.

**Comment by rohan20** [comment]
Anybody made any progress on this? I followed the exact google sign in tutorial [here](https://firebase.google.com/docs/auth/android/google-signin) but I keep getting status code 8 error.

**Comment by leonardomontes** [comment]
I get error 8 (INTERNAL_ERROR) the first time I add a Google Account. If I try again, it works. Where could I look for more details?

**Comment by sauce-chili** [comment]
Good day. I ran into a similar problem and spent 1.5 days solving it.
Tips to help you:
1) First check valid the package name and fingerprint SHA1.
2) If your application did not pass verification and was not released, then make sure that the user to be authorized is in the list of testers (this can be checked in APIs & Service -> OAuth consent sreen -> Test users)
3 *) There is a suspicion that all letters in the package name in android studio should be lowercase.

In my case, it helped to create a new project, transfer old files to it, and create a new OAuth Client IDs.
