### ISSUE TITLE
Android Google App Invite sample is not sending email and message,What i am doing wrong?

### ISSUE THREAD

**Issue by gajraj-hinkhoj** [googlesamples/google-services#145]
I am using Android Google App invite sample and following all guidelines but it is not sending any message and email, giving message "Message Failed to Send" and in logs i am getting onActivityResult: requestCode=0, resultCode=3 and getInvitation:onResult:Status{statusCode=CANCELED, resolution=null}

Please help what i am doing wrong?

**Comment by samtstern** [comment]
Make sure you have properly followed the steps at developers.google.com/mobile/add and chosen the correct package name and keystore.  Otherwise you will get errors.

**Comment by ianbarber** [comment]
Closing as AppInvites has now moved to Firebase

**Comment by Rahulrsannidhi** [comment]
I am using the fire base app invite but it always showing the message failed in the log  getting like this
06-24 12:20:53.990 13592-13810/sample.firebase.com.firbaseappshare W/InstanceID/Rpc: Found 10013
06-24 12:20:54.733 13592-13592/sample.firebase.com.firbaseappshare W/PathParser: Points are too far apart 4.000000596046461
06-24 12:21:29.316 13592-13592/sample.firebase.com.firbaseappshare D/MainActivity: onActivityResult: requestCode=0, resultCode=3 please help on this.

**Comment by kosik** [comment]
Having the same issue but the resultCode=13. And i did not mange find anywhere description what does it means.

**Comment by turmanauli** [comment]
**about resultCode=13** 
It is because your have to 

- Go To Google Play Console and copy 4 fingerprints (2 SHA-1s and 2 SHA-256s) then add it to firebase console (your project).
