### ISSUE TITLE
Can't get token id for user

### ISSUE THREAD

**Issue by mzelzoghbi** [googlesamples/google-services#149]
I am trying to retrieve `ID Token` for a user using the sample app in `google-services/android/signin/app` but it always ends up with `access token` not `jwt token`.

Can anyone helps me to figure out what am i doing wrong ?!

**Comment by samtstern** [comment]
What makes you think you have an access token and not a JWT token?  And if you do have an access token, where are you getting it from?

**Comment by mzelzoghbi** [comment]
we are making login/register using cross-auth . Using google sdk we get `ID TOKEN` to send it to the backend which uses it to do the login/register process. it is working fine using google login sdk on `ios` which generates a code like this `4/4x0Hh1acrl7OPyzAYtuziNCX5dmsj5ewclRIuWN0qxg` which the backend takes and complete the process. but on android i got an access token like this `eyJhbGciOiJSUzI1NiIsImtpZCI6ImIyY2ZiZDIxOGNmYzIyNGYyODQ2Y2ViNzE0MDNkMDVmMTc1ZDJiM2MifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhdWQiOiI1MjI3MzQ0NDI4MC1zZTlnZ3ZnYjU4MWs2aDYzNDZlZWliOXNlcWYwOWFkMS5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInN1YiI6IjExNjE4NTUxNjA2Nzc0MDk4MDU5OCIsImF6cCI6IjUyMjczNDQ0MjgwLWVmbmxqYjhmdmFuN3MwcnNzZGFvMjNma2I3aWZmZmRlLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiaWF0IjoxNDUzNzU1MTM1LCJleHAiOjE0NTM3NTg3MzUsIm5hbWUiOiJNb2hhbWVkIFpha2FyaWEgRWwtWm9naGJpIiwicGljdHVyZSI6Imh0dHBzOi8vbGg2Lmdvb2dsZXVzZXJjb250ZW50LmNvbS8tWDBSZG12cXNNR0EvQUFBQUFBQUFBQUkvQUFBQUFBQUFYNGMvUmNYWXpPbFo4VlUvczk2LWMvcGhvdG8uanBnIiwiZ2l2ZW5fbmFtZSI6Ik1vaGFtZWQiLCJmYW1pbHlfbmFtZSI6Ilpha2FyaWEgRWwtWm9naGJpIiwibG9jYWxlIjoiZW4ifQ.TA_mzwqdGIqZwm7pbVRhN764-CCIYRsYcY537X3hrfO3dHMuhq_GPceJlXBNeD-5PK8bL6sG-V4onZD0k4Mss-GW7OPtfSqY7uqdVC_yfIMpEDMV_rPvHsw02ecdYmWXDMm7ccnTn5SEGSjCuXotTBTnDivONTYrwn15vW9GcaOoA_ihywbwgUpnxNPFmHZ-No596VsfUz34bQBIuQbamf93lGAtHulWEusytHASDSN3XHnifYnEkJ8vbiAIdGL13WnRmf7EfDrBOcEBmv4PjFIp3K4dq6j8Rcsij66e-Wm4noiDlHqgO3DDsIMeO2dwSe5errRR1c2FkHB5YLgHBQ` which the backend don't accept !

**Comment by mzelzoghbi** [comment]
I solved that, this short code is called `serverAuthCode` :)
