### ISSUE TITLE
It does not show notification, when the application is closed 

### ISSUE THREAD

**Issue by PrathmK** [googlesamples/google-services#153]
When the app is in background it works , but once i terminate the app from recent app list, it wont receive any notification(just to clear out not telling about the force close of app) .

**Comment by samtstern** [comment]
Are you referring to the GCM sample?  What kind of device are you using?

**Comment by PrathmK** [comment]
Yes GCM Sample application , device is ASUS zenphone 2 , os version 5.0.2

**Comment by alexodus** [comment]
I have the same problem with my ASUS Zenphone2...Now my phone does not work, but I saw in the logs that the notification arrives but there was no receiver for it.

**Comment by alexodus** [comment]
now i see that on stackoverflow:
http://stackoverflow.com/questions/35131236/gcm-background-service-enable-application-automattically-in-asus-s-zenfone-2-au

**Comment by PrathmK** [comment]
i tried the solution for ASUS is worked, but few days back i found same issue with MI phone, i tried the new intent flags , it doesn't  work out...any other known solution.

**Comment by samtstern** [comment]
@alexodus @PrathmK this is a very old issue, going to close it as part of some cleanup.

If you want to discuss FCM in the background, I'd suggest checking out https://github.com/firebase/quickstart-android/issues/4 or https://github.com/firebase/quickstart-android/issues/89
