### ISSUE TITLE
App Invites Play Store Box placeholder

### ISSUE THREAD

**Issue by Maragues** [googlesamples/google-services#155]
*I don't know where to suggest an enhancement, please redirect me to the proper place if this is not it.*

Goal: Do not force to choose between showing the nice layout auto generated or create our own html, which is likely to look worse.

The [setEmailHtmlContent documentation] (https://developers.google.com/android/reference/com/google/android/gms/appinvite/AppInviteInvitation.IntentBuilder.html#setEmailHtmlContent(java.lang.String)) already lists a pattern (*%%APPINVITE_LINK_PLACEHOLDER%%*) that'll be replaced by a link to Play Store/App Store. It would be great if we could have another pattern for the whole box, something like *%%APPINVITE_BOX_PLACEHOLDER%%*

The result would look like this

```java
Intent intent = new AppInviteInvitation.IntentBuilder("Send Invitations for XYZ app")
         ...
         .setEmailHtmlContent("<html><body>"
             + "<p>John thought you'd find this interesting</p>"
             + "%%APPINVITE_BOX_PLACEHOLDER%%"
             + "<p>Feel free to contact us at info@example.com</p>"
             + "</body></html>")
         .setEmailSubject("XYZ Offer")
         ...
         .build();
```

I opened an [issue in Android tracker](https://code.google.com/p/android/issues/detail?id=200181), but they played the wrongForum card

**Comment by samtstern** [comment]
@Maragues thanks for this feedback.  I will file this with the product team, I am going to close this issue since there is nothing I can do in the context of this sample repository.

**Comment by Maragues** [comment]
Thanks @samtstern! Tell them to set up an issue/suggestions system! Since invites is in Beta, I guess they'd like to hear from us.
