### ISSUE TITLE
How can i update notification count.

### ISSUE THREAD

**Issue by alphaDroid89** [googlesamples/google-services#157]
Hi,

I used this GCM receiver class in my application, i was struggled while receiving multiple notification messages, I'm facing the following
1. I'm using static notification id - new message replace the existing one.
2. I used TaskStackBuilder to grouping the message, so i used the following code,

```
NotificationCompat.Builder mBuilder = new NotificationCompat.Builder(this);
mBuilder.setContentTitle("Updated Notification");
mBuilder.setContentText("You've got updated Notification.");
mBuilder.setTicker("Updated Notification Alert!");
mBuilder.setAutoCancel(true);
mBuilder.setSmallIcon(R.drawable.ic_tag_logo);
mBuilder.setNumber(++totalMessages);
Intent resultIntent = new Intent(this, NotificationClass.class);
TaskStackBuilder stackBuilder = TaskStackBuilder.create(this);
stackBuilder.addParentStack(NotificationClass.class);
stackBuilder.addNextIntent(resultIntent);
PendingIntent resultPendingIntent = stackBuilder.getPendingIntent(0,
PendingIntent.FLAG_UPDATE_CURRENT);
mBuilder.setContentIntent(resultPendingIntent);
mNotificationManager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
mNotificationManager.notify(notificationID, mBuilder.build());
```

Each time i receive notification the count will remains same, ie count not incremented.

**Comment by ianbarber** [comment]
Do the other fields of the notification update (e.g. for a test, if you try replacing the title with message count, does that update)?

**Comment by SkyNite** [comment]
@ianbarber , if i use static id for notification - Title, message..etc are updated  ie the old message is replaced by new one.

**Comment by samtstern** [comment]
@alphaDroid89 I am doing some cleanup and this is a very old issue so I am going to close it.  If you are still having this issue please re-open and we can continue to discuss.
