### ISSUE TITLE
Apply GMS gradle plugin only for specific flavor

### ISSUE THREAD

**Issue by dvdh** [googlesamples/google-services#160]
Google Analytics documentation https://developers.google.com/analytics/devguides/collection/android/v4/

requires the use of this gradle plugin
apply plugin: 'com.google.gms.google-services'

However it is not clear how to apply this plugin only for specific flavors.

Example use case:
I have a free app flavor with google analytics, a paid version without analytics.

Can you please provide an example on how to achieve this?

Thanks,
David.

**Comment by samtstern** [comment]
Please see the discussion on #54 which I think will contain the details you are looking for.

**Comment by dvdh** [comment]
Thanks @samtstern, exactly it.
