### ISSUE TITLE
User Info Is not carried when it sign in.

### ISSUE THREAD

**Issue by matheuztavarez** [googlesamples/google-services#165]
It seems that after the user sign in, the app don't run the sign in function in the appDelegate, idk if it should, but its not saving the user info (token, etc) as well... I installed it manually, and everything is working as it should, besides this.

**Comment by ianbarber** [comment]
Make sure you are setting the delegate on GIDSignIn sharedInstance early enough: if you handle the callback before the delegate is attached, the user will get signed up, but you just wont be notified. 

If that's OK, check that you're calling signInSilently - that should refresh the authentication (if it can) and call the delegate method.

**Comment by ianbarber** [comment]
Any more info on this? If you've got a minimal version we can try and reproduce the issue?

**Comment by samtstern** [comment]
@matheuztavarez this is a very old issue and I'm doing some cleanup so I am going to close it.  If you're still having this problem please re-open it and we can continue to discuss.
