### ISSUE TITLE
GCM not working in production (testflight) even with kGGLInstanceIDAPNSServerTypeSandboxOption@No

### ISSUE THREAD

**Issue by soufianeEssabbane** [googlesamples/google-services#168]
Hi, i'm having big troubles with setting up GCM for production environment (24 hours on the same problem) tried everything, with development environment it works fine like a charm I receive notifications in all application states (even closed). provisioning profil and apn production certification is ok too ... is there any case I have to check ?

**Comment by ianbarber** [comment]
Can you confirm you uploaded both prod and debug certificates in https://developers.google.com/mobile/add ?

**Comment by soufianeEssabbane** [comment]
Yes sir, and it's been like two days no sleep trying to figure out what i'm missing. it works like a charm in the development environment i'm using https://gcm-http.googleapis.com/gcm/send for testing. but once I move to production and try to test it give me unregistered ... BUT there's a little error message that I don't get, just before it retrieve a registration token it displays this message (it doesn't seems to affect the reception of notifications in dev mode or the retrieving of the registration token) 
GCM | Invalid key in checkin plist: GMSInstanceIDDeviceDataVersion

Is this about the configuration GoogleService-Info.plist ?
thanks

**Comment by soufianeEssabbane** [comment]
Any idea ? anyone ? ^^'

**Comment by soufianeEssabbane** [comment]
Hi, it seems that this have a relation with the expiration of  the Apple world wide Developer relations certification authority which happened yesterday 14 February. regenerating push certifications and what goes with may solve this problem, i'm actually uploading to test production environment, and i'll let you know. thanks

**Comment by soufianeEssabbane** [comment]
now it work.

**Comment by AhmAbdallah** [comment]
Firstly check you Production certificate 
after it do:-
Set `"priority": "high"`

```
{
      "to": "gcm_device_token",
      "priority": "high",
      "content_available": false,
      "notification": {
        "sound": "default",
        "badge": "1",
        "title": "Push Title",
        "body": "Push Body"
      }
    }
```
Here's the code to use for production environment :

```
_registrationOptions = @{kGGLInstanceIDRegisterAPNSOption:deviceToken,
                         kGGLInstanceIDAPNSServerTypeSandboxOption:@NO};
```
Here's the code to use for development environment :

```
_registrationOptions = @{kGGLInstanceIDRegisterAPNSOption:deviceToken,
                         kGGLInstanceIDAPNSServerTypeSandboxOption:@YES};
```
