### ISSUE TITLE
AppInvite Quota ?

### ISSUE THREAD

**Issue by mosqueiro** [googlesamples/google-services#173]
I have an application on Google Play and we're using the Google App Invite.
But I noticed that our users can not send more than 10,000 invites per day. In a few hours user receives an error and can not send the invitations, but then everything back to normal.
So I wonder if there is quota for each app ?

**Comment by ianbarber** [comment]
Hi! I looks like you were indeed hitting a quota: we're looking at getting that raised and will let you know.

**Comment by ianbarber** [comment]
I think this is being addressed out of band with you, so will close here, thanks!
