### ISSUE TITLE
Unable to get access token

### ISSUE THREAD

**Issue by yatinsingla** [googlesamples/google-services#178]
I am able to receive username, email, profile pic etc using SignInActivity.java but unable to receive any access token when using IdTokenActivity.java. When i create a configuration file with SHA-1 of my keystore, OAuth2.0 client id's(android and web application) and API key are automatically generated. And with both these client id's I get IdToken as null.
Is this desired behavior, a bug or am I doing something wrong?

**Comment by ianbarber** [comment]
The ID token you should pass is that ID token if where you actually want to send it - though I appreciate that is somewhat confusing. Generate a client ID for your server (in the same project) and use that as the value, and it should work.

**Comment by sebastianleecn** [comment]
same problem with me
i can't understand what you mean?
no id token? should I pass the "client ID" to my server?
what a mess~
