### ISSUE TITLE
iOS no authorization with GoogleSignIn on App Invites for iOS

### ISSUE THREAD

**Issue by sebasx** [googlesamples/google-services#18]
my app have some problem with autoricate. I build project from here https://developers.google.com/app-invites/ios/guides/start?configured and it's work fine when I use Bundle ID com.google.samples.quickstart. AppInvitesExample. When I trying to use my own Bundle ID, authorization is not finish always. I haven't any complilation errors, GoogleService-Info.plist is new for new Bundle, I remember also about changes on URL types - all looks prepared fine.

http://postimg.org/gallery/fyp9itq6/2a4c6447/

I have "step1" screen (choose user)

but I haven't "step2" screen (confirm app)

Anybody know reason? Maybe app must be on AppStore?

**Comment by ianbarber** [comment]
What happens when you choose the user - does it just return you to the app right away?

**Comment by sebasx** [comment]
Yes, and on console I have "Wystąpił błąd, który prawdopodobnie można naprawić. Spróbuj ponownie." which mean "An error occurred that probably can be repaired. Try again.", once I get "The operation couldn’t be completed. (com.google.HTTPStatus error 400.)"

**Comment by sebasx** [comment]
I am authorized by YouTube app installed on my device. When I delete YouTube app from my device, authentication is performed by WebView inside the app and them it's successfully

**Comment by sebasx** [comment]
anybody know reason? My project can not be carried forward, problem is on iOS7 and iOS8 on "real devices" (not on simulator)

**Comment by ianbarber** [comment]
Which version of the youtube app do you have on the device?

**Comment by sebasx** [comment]
I have latest version of YouTube, 10.22.1614 but it also doeasn't work with GMail app.

error Error Domain=com.google.GIDSignIn Code=-1 "Wystąpił błąd, który prawdopodobnie można naprawić. Spróbuj ponownie." UserInfo=0x16622ea0 {NSLocalizedDescription=Wystąpił błąd, który prawdopodobnie można naprawić. Spróbuj ponownie.}

**Comment by sebasx** [comment]
My client ID is 41894651830-vlh6ttdgb1ogolr1un6erpvoog6bsvrj.apps.googleusercontent.com, app ID "c  o m . n e x t i s g r e a t . 6 i x" without spaces

**Comment by sebasx** [comment]
I am not alone with that problem: http://stackoverflow.com/questions/30864202/iosgidsignin-not-fetch-google-user-when-handle-sign-in-with-another-google-a

**Comment by sebasx** [comment]
Hey,

We know propably reason, here

https://developers.google.com/mobile/add?platform=ios&cntapi=appinvite&cnturl=https:%2F%2Fdevelopers.google.com%2Fapp-invites%2Fios%2Fguides%2Fapp%3Fconfigured%3Dtrue&cntlbl=Continue%20Adding%20App%20Invites

we can't add bundle "com.nextisgreat.6ix" (it is correct form for our iOS app)
We have "com.nextisgreat.six" but must be "com.nextisgreat.6ix" which is not accepted

http://awesomescreenshot.com/02050jf757

**Comment by ianbarber** [comment]
oh interesting! that does sound like that is the issue.

**Comment by sebasx** [comment]
Hey, what is the progress? Can You tell me when "com.nextisgreat.6ix" as bundle ID will be acceptable?

**Comment by ianbarber** [comment]
Its being looked at. As a work around, you should be able to enter the right bundle ID via https://console.developers.google.com

**Comment by mjgaylord** [comment]
Has there been any progress on this issue? My bundle ID has a dash in it, would this possibly trigger this problem?

**Comment by jiangwei1221** [comment]
Hey, I'm a developer of the workflow. Bundle IDs like "com.nextisgreat.6ix" or with dashes should be allowed to add to your project now.

**Comment by samtstern** [comment]
I am going to close this issue now since @jiangwei1221 's reponse addresses some of this and there has not been any activity in months.  Please re-open if you need further guidance.
