### ISSUE TITLE
Google Sign In is flashing a small empty white box

### ISSUE THREAD

**Issue by Proximator** [googlesamples/google-services#184]
Hi

I was testing the SignInActivity, it seems to display a small white empty box before and after I select an google account to login with. It is the exact same issue as: http://stackoverflow.com/questions/34599990/android-google-sign-in-is-flashing-a-small-empty-white-box-while-signing-in-a-us

Does anyone knows why ? and how can we fix it ?

**Comment by samtstern** [comment]
I believe this is the same issue as #130.  I am going to close this copy, let's discuss there.
