### ISSUE TITLE
GCM ISSUE :  "Could not find tools.jar" AND "java.io.IOException: SERVICE_NOT_AVAILABLE at  ~./RegistrationIntentService.onHandleIntent"

### ISSUE THREAD

**Issue by puneet-kr-sh** [googlesamples/google-services#188]
Android(on Window OS) GCM ISSUE : 
When I run [.\gradlew.bat run -Pmsg="my message"] command on android @ Window OS, got Build failed with message "Could not find tools.jar"

/**
 * C:\Users\Android\Downloads\google-services-master\android\gcm>.\gradlew.bat run -Pmsg="my message"
 * Incremental java compilation is an incubating feature.
 * :gcmsender:compileJava FAILED
 * FAILURE: Build failed with an exception.
 * What went wrong:
 * Execution failed for task ':gcmsender:compileJava'. 
 * > Could not find tools.jar
 * Try:
 * Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
 * BUILD FAILED
 * Total time: 4.442 secs
 * C:\Users\Android\Downloads\google-services-master\android\gcm>
 * */

/**
 * java.io.IOException: SERVICE_NOT_AVAILABLE
 * at com.google.android.gms.iid.zzc.zzb(Unknown Source)
 * at com.google.android.gms.iid.zzc.zza(Unknown Source)
 * at com.google.android.gms.iid.InstanceID.zzc(Unknown Source)
 * at com.google.android.gms.iid.InstanceID.getToken(Unknown Source)
 * at gcm.play.android.samples.com.gcmquickstart.RegistrationIntentService.onHandleIntent(RegistrationIntentService.java:53)
 * at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
 * at android.os.Handler.dispatchMessage(Handler.java:102)
 * at android.os.Looper.loop(Looper.java:135)
 * at android.os.HandlerThread.run(HandlerThread.java:61)
 * */

**Comment by ianbarber** [comment]
SERVICE_NOT_AVAILABLE is interesting - what version of Google Play Services did you have on your device?

**Comment by samtstern** [comment]
@puneet-kr-sh I am closing this issue as the last response was by @ianbarber a few months ago.  Please re-open if you have more information and are still experiencing this issue.

**Comment by basmasrour** [comment]
I need to know the solution
