### ISSUE TITLE
SignInActivity is darkened and does not respond to Sign in button clicks after restart.

### ISSUE THREAD

**Issue by andrewsdv** [googlesamples/google-services#192]
Steps to reproduce:
1. Open the sample app and launch SignInActivity
2. Tap the "Sign in" button
3. Tap on some account so that you become signed in
4. Tap the "Disconnect" button
5. Tap the "Sign in" button
6. Tap "Home" right after the tap on some account. Sometimes "Unfortunately, Google Play Services has stopped" toast is shown after this action.
7. Return back to the SignInActivity by choosing it from the recently used
8. SignInActivity is darkened and does not respond to Sign in button clicks (see the screenshot). Besides, on some devices, it's possible to notice the empty frame bug reported in https://github.com/googlesamples/google-services/issues/130

It might probably be needed to repeat the steps 4-8 for several times to catch the bug as the actions should be done quickly.

Tested on several devices with different APIs (issue was reproduced on any of them). Google Play Service version: 8.7.03

From my quick research the onActivityResult() isn't called after a restart. Auth.GoogleSignInApi.silentSignIn(mGoogleApiClient).isDone() returns false.

![screenshot_2016-03-25-12-20-17](https://cloud.githubusercontent.com/assets/11175924/14043051/e57e41d4-f288-11e5-8d32-ef29103a9829.png)

**Comment by ianbarber** [comment]
@samtstern FYI. There may be a Google Play Services bug, as it shouldn't be crashing if the handler disappears.

**Comment by samtstern** [comment]
@andrewsdv thanks for this very detailed report, I will report this to platform team and see if we can find a fix.

**Comment by ianbarber** [comment]
Closing - believe should be fixed in recent versions, please reopen if not.
