### ISSUE TITLE
duplicate symbol for architecture x86_64 _GSDK_GTMNSDataZLibExportToSuppressLibToolWarning

### ISSUE THREAD

**Issue by tusharbhatta** [googlesamples/google-services#193]
Getting this error after updating cocoapods for new google ios sdk 2.0.3
My podFile is :

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
pod 'Google/SignIn'
pod 'GoogleMaps'
pod 'Google/Analytics'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'

Please help.

**Comment by ianbarber** [comment]
I just tried a blank project with that podspec, and I don't get the build error. Can you make sure you've run pod update (and maybe post the versions of all pods youre getting?)

**Comment by halcyonmobiledev** [comment]
I'm getting the same error when I try to build my project after re-installing the pods. 
The interesting thing is that if I do this with a completely new project, then everything builds as expected. 

A temporary solution that I made (until I find out the real cause of the issue) was to remove manually the force loading of libGTM_NSData+zlib_external.a from the xcconfig file. 

This worked but I really don't want to keep this "solution". I just can't find out what makes my old project to fail and the empty project with the same podfile to work. A not-so-obvious build setting maybe?

The output of the pod install looks like this (if it helps):

Installing AFNetworking (3.0.4)
Installing Bolts (1.6.0)
Installing Branch (0.11.18)
Installing Crashlytics (3.7.0)
Installing FBSDKCoreKit (4.10.1)
Installing FBSDKLoginKit (4.10.1)
Installing FXPageControl (1.4)
Installing Fabric (1.6.7)
Installing Flurry-iOS-SDK (7.5.2)
Installing Google (2.0.3)
Installing GoogleAppUtilities (1.1.0)
Installing GoogleAuthUtilities (2.0.0)
Installing GoogleInterchangeUtilities (1.2.0)
Installing GoogleNetworkingUtilities (1.2.0)
Installing GoogleSignIn (3.0.0)
Installing GoogleSymbolUtilities (1.1.0)
Installing GoogleUtilities (1.2.0)
Installing HLMFoundation (1.4.0)
Installing Harpy (3.4.7)
Installing SDWebImage (3.7.5)

**Comment by ianbarber** [comment]
Hmm, I wonder if its a force load from a previous version that didn't go away. If you're on pods 1.0.0, could you try pod deintegrate, then pod update, and see if that cleans up the problem?

**Comment by weibel** [comment]
I had the same issue. 
Pinning GoogleUtilities on version 1.1.0 in my podfile solved the problem. 
I'm not on Cocoapods 1.0.0

**Comment by aksswami** [comment]
I am having same issue. 

```
duplicate symbol _GSDK_GTMNSDataZLibExportToSuppressLibToolWarning in:
    /Users/XXX/Developer/YYY/ZZZ/XXXX/../Pods/GoogleUtilities/Libraries/libGTM_NSData+zlib_external.a(GTMNSData+zlib.o)
    /Users/XXX/Developer/YYY/ZZZ/Pods/GoogleUtilities/Libraries/libGTM_NSData+zlib_external.a(GTMNSData+zlib.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

In a new project everything works fine but when I try to add it to a existing project for GCM, getting this error.

**Comment by zntfdr** [comment]
Thank you @weibel for the temporary solution 👍

**Comment by halcyonmobiledev** [comment]
It seems that the build error is present only if I am building my project for an iPhone Simulator. If I build for an actual device, connected to the laptop, there are no build issues at all.

**Comment by aksswami** [comment]
I cleaned my pods and tried @weibel 's solution and It worked. Thanks @weibel . But I have to do some changes to `Pods-XXX-debug.xconfig` and `Pods-XXX-release.xconfig`. As it was pointing to `GoogleUtilities/Libraries/libGTM_NSData+zlib_external.a`, but in 1.1.0 version we have GoogleUtilities/Libraries/libGTM_NSData+zlib_.a`. Hope this helps someone.

**Comment by tusharbhatta** [comment]
Yes, it worked by following the combined solution of @weibel and @aksswami. Thanks for the information guys.
Here are the steps as it might help someone :

1. Update the "PodFile" by adding:  'GoogleUtilities', '1.1.0'    (the latest version 1.2.0 that comes with Google sdk 2.0.3 didn't work )
2. If your project uses swift, then add :  use_frameworks!   (after the platform support version) 
3. run : pod update (from terminal, which will install compatible pods for the above version)
3. Open Xcode and search for the text "libGTM_NSData", it will list two xcode config files (debug, and a release). Replace the text named "libGTM_NSData+zlib_external.a" to "libGTM_NSData+zlib.a"  (becauseithe lib name changed in new Google SDK, can be found under ..Pods/GoogleUtilities/Libraries/)
4. Clean and Rebuild the project. It should build successfully. 
 

Thanks,
- Tushar

**Comment by ianbarber** [comment]
We have updates for various pods that should resolve these issues - please try updating to the latest versions across the board and let us know if you have further problems!

**Comment by zntfdr** [comment]
@ianbarber works perfectly fine here. Both on simulator and actual devices. 

Thanks!

**Comment by aksswami** [comment]
After update I am getting these errors :- 
```
ld: library not found for -lGSDK_Overload
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This lib was added in `other linker flags`. I looked for the file and this was not present in installed pod. Instead `libGSDK_Overload_external.a` was present. Even if I remove this file from `other linker flag`, I get this error for other files.

**Comment by ianbarber** [comment]
@aksswami - can you paste in your Podfile.lock so we can see the versions involved (and include your xcode and Cocoapods versions if possible!)

**Comment by ivanmolina65** [comment]
@ianbarber Im getting the same issue as @aksswami -lGSDK_Overload_external

**Comment by havocked** [comment]
@ianbarber Same issue as @ivanmolina65 :

 `ld: library not found for -lGSDK_Overload_external
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Here is my Podfile.lock:

```
PODS:
  - Alamofire (3.3.1)
  - AlamofireImage (2.4.0):
    - Alamofire (~> 3.3)
  - Appz (1.5.0)
  - Bolts (1.7.0):
    - Bolts/AppLinks (= 1.7.0)
    - Bolts/Tasks (= 1.7.0)
  - Bolts/AppLinks (1.7.0):
    - Bolts/Tasks
  - Bolts/Tasks (1.7.0)
  - CardIO (5.3.2)
  - CircleProgressView (1.0.10)
  - Crashlytics (3.7.0):
    - Fabric (~> 1.6.3)
  - Fabric (1.6.7)
  - FBSDKCoreKit (4.11.0):
    - Bolts (~> 1.7)
  - FBSDKLoginKit (4.11.0):
    - FBSDKCoreKit
  - GGLInstanceID (1.2.1)
  - Google/CloudMessaging (1.1.0):
    - GGLInstanceID (~> 1.0)
    - Google/Core
    - GoogleCloudMessaging (~> 1.0)
  - Google/Core (1.1.0):
    - GoogleInterchangeUtilities (~> 1.0)
    - GoogleNetworkingUtilities (~> 1.0)
    - GoogleSymbolUtilities (~> 1.0)
    - GoogleUtilities (~> 1.1)
  - GoogleCloudMessaging (1.2.0):
    - GoogleInterchangeUtilities (~> 1.0)
    - GoogleIPhoneUtilities (~> 1.0)
    - GoogleSymbolUtilities (~> 1.0)
  - GoogleInterchangeUtilities (1.2.0):
    - GoogleSymbolUtilities (~> 1.0)
  - GoogleIPhoneUtilities (1.2.0):
    - GoogleSymbolUtilities (~> 1.0)
    - GoogleUtilities (~> 1.0)
  - GoogleNetworkingUtilities (1.2.0):
    - GoogleSymbolUtilities (~> 1.0)
  - GoogleSymbolUtilities (1.0.3)
  - GoogleUtilities (1.1.0):
    - GoogleSymbolUtilities (~> 1.0.0)
  - iHeartRating (0.1.5)
  - JGProgressHUD (1.3.1)
  - JKNotificationPanel (0.2.0)
  - Material (1.39.17)
  - MySamSharedFiles (0.43.0):
    - Alamofire
    - AlamofireImage (~> 2.0)
    - CircleProgressView
    - JGProgressHUD
    - Material
    - Proposer (~> 0.7.1)
    - RealmSwift
    - SwiftyJSON
  - Proposer (0.7.1)
  - Realm (0.99.0):
    - Realm/Headers (= 0.99.0)
  - Realm/Headers (0.99.0)
  - RealmSwift (0.99.0):
    - Realm (= 0.99.0)
  - Stripe (6.2.0):
    - Stripe/Core (= 6.2.0)
  - Stripe/Core (6.2.0)
  - SwiftyJSON (2.3.2)

DEPENDENCIES:
  - Appz (from `https://github.com/appstud/Appz.git`)
  - CardIO
  - Crashlytics
  - Fabric
  - FBSDKCoreKit
  - FBSDKLoginKit
  - Google/CloudMessaging (<= 1.1.0)
  - GoogleUtilities (<= 1.1.0)
  - iHeartRating (from `https://github.com/appstud/iHeartRating.git`)
  - JKNotificationPanel
  - Material (from `https://github.com/CosmicMind/Material.git`)
  - MySamSharedFiles (from `./MySamSharedFiles`)
  - Stripe

EXTERNAL SOURCES:
  Appz:
    :git: https://github.com/appstud/Appz.git
  iHeartRating:
    :git: https://github.com/appstud/iHeartRating.git
  Material:
    :git: https://github.com/CosmicMind/Material.git
  MySamSharedFiles:
    :path: "./MySamSharedFiles"

CHECKOUT OPTIONS:
  Appz:
    :commit: 3ac0433f8d07583a74f7a72ebab628b5f5f93b64
    :git: https://github.com/appstud/Appz.git
  iHeartRating:
    :commit: ce8f00c0927974fcb9627c3a905a27f53d03e48c
    :git: https://github.com/appstud/iHeartRating.git
  Material:
    :commit: a8c2438b244544866251b54e4e36a5dfdc9becb8
    :git: https://github.com/CosmicMind/Material.git

SPEC CHECKSUMS:
  Alamofire: 369bc67b6f5ac33ded3648d7bd21c5bfb91c2ecc
  AlamofireImage: 87408b652e0f5ae5fe364035f15aea8b9b24c77e
  Appz: d517c7cfb0ee193698edab4410fd1a073c1464a0
  Bolts: a0058fa3b331c5a1e4402d534f2dae36dbff31e4
  CardIO: 92c45caef0d986c4a303a7afba0c9b76ff2b1f6e
  CircleProgressView: 5116fc2d3be792d755e6979d7f7309648de79d11
  Crashlytics: c3a2333dea9e2733d2777f730910321fc9e25c0d
  Fabric: caf7580c725e64db144f610ac65cd60956911dc7
  FBSDKCoreKit: 686ac982723a14ec9ddb85e2f81235d7706c891b
  FBSDKLoginKit: bade9fc78277764149ccc5bfaadbf13c83175c6a
  GGLInstanceID: 4a317044f744281b82cd03015f379899f277cad3
  Google: ec6c7729037b9579e52a4880ba06eb38ddb1de68
  GoogleCloudMessaging: f37ea14dd0f41d4d889c10b5559dd35bbfd9ac26
  GoogleInterchangeUtilities: 427382e42d8a340038bec37c6fdfd316e14b5fa2
  GoogleIPhoneUtilities: 1c2996078f079d2fc54453dbd13eaf5523666550
  GoogleNetworkingUtilities: ec1e9911aca811eb18b7144394fee6168b607785
  GoogleSymbolUtilities: 82ad9f93d3615244b3f4ce440f5ab2515e8b4f56
  GoogleUtilities: 8ed9134debe11719097881711464752900668f10
  iHeartRating: ac411844f462a9c59386e974b52c7078c6b70e63
  JGProgressHUD: 153053a21d81208cb5f659691996bcefce6a9885
  JKNotificationPanel: c45f60e6548cda03752d35b4bf479f44c12886c1
  Material: eccc5afdac89e10aa7a635ad34d6c3564387bfd3
  MySamSharedFiles: f017c3843dd69a24dfe06778088602f111662d95
  Proposer: e9759ad71a6702fd94315a0bff1f8c116edf6f07
  Realm: cf275f109b94e5399896960c90285a043edb3d56
  RealmSwift: f40e5634bbc74f063163561d02acc4aa040d40a5
  Stripe: 275524137e6c4cc1058f6d32ece248adf30a21f9
  SwiftyJSON: 04ccea08915aa0109039157c7974cf0298da292a

COCOAPODS: 0.39.0
```

**Comment by ianbarber** [comment]
This should be fixed in the latest version. However, please: 

1) Use CocoaPods 1.0 or greater
2) Run pod deintegrate before pod update to ensure you have a clear project.

**Comment by IvanAndrosenko** [comment]
is that fixed already? i still have it

**Comment by tusharbhatta** [comment]
Yes, it seems to be fixed. Follow the latest comments above to fix it.
