### ISSUE TITLE
File not found libGTM_NSData+zlib.a for Google Sign-in 3.0.0

### ISSUE THREAD

**Issue by mrigo** [googlesamples/google-services#194]
Hello,
I'm using the pod `pod 'Google/SignIn'` to use it in my App.
With the version 2.4.0 there's no problem, but now with the version 3.0.0 I've the error

```
ld: file not found: /Users/Mattia/projectsignin/Pods/GoogleUtilities/Libraries/libGTM_NSData+zlib.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

according to this [question on stackoverflow](http://stackoverflow.com/questions/36168692/google-signin-for-ios-fails-to-build-because-its-looking-for-a-file-that-doesn) the problem is related to the library `GoogleUtilities`.

There's a way to fix it?

Thanks
\m

**Comment by ianbarber** [comment]
Can you try running `pod update` to get the latest version of everything?

**Comment by ianbarber** [comment]
Answered on SO as well - I think the issue is GSI doesn't specify its minimum versions, so when you pod install, its not grabbing the latest version of utilities - pod update should update everything.

**Comment by ianbarber** [comment]
We have updates for various pods that should resolve these issues - please try updating to the latest versions across the board and let us know if you have further problems!

**Comment by mrigo** [comment]
Hi! Sorry for the super late response!
Using the last pod version the bug is fixed!

Thanks man!
\m
