### ISSUE TITLE
Can't pod install google SignIn ios example

### ISSUE THREAD

**Issue by mrigo** [googlesamples/google-services#195]
Hello,
I've downloaded the ios example of google signin but I can't install the pods because of this error:

```
Invalid `Podfile` file: [!] The specification of `link_with` in the Podfile is now unsupported, please use target blocks instead
```

can you fix the pod file?

Thanks
\m

**Comment by ianbarber** [comment]
The pod specs are for pods 0.39, which is the stable version. We had a back and forth about this, but there's no way to support both stable and the 1.0.0 beta. 

If you open the Podfile you'll see there are the 'target' lines - if you uncomment those, and comment out link_with, it should work on 1.0.0.
