### ISSUE TITLE
silentSignIn Android can't detect app access revocation

### ISSUE THREAD

**Issue by javerd** [googlesamples/google-services#196]
In Android version,
when a user is logged in on the application and the application access is revoked in the user "Apps connected to your account" page, you can close the app and reopen it and the user is still logged in.
When the app invoke silentSignIn the result is success, you can even ask for an IdToken and loggin to a backend web site.
On device settings --> Google --> Connected apps--> <logged account> the app is removed as expected.

We have tried on different devices, with our own app and with this sample, and we always see this behaviour.

Thanks in advice

**Comment by javerd** [comment]
Problem update:
After a certain number of hours, silentSignIn return a false. If you try to logon again, the lgin components jumps directly to the permission validation page of last user, you can only accept or cancel the process.

If you accept, you are logged in again without enter the password....
If you cancel, you cancel the login process.

**Comment by samtstern** [comment]
@javerd you are seeing the intended behavior in this case.  `silentSignIn

**Comment by javerd** [comment]
Our first test shows that the cache expires in 1 hour, but sometimes `silentSignIn `returns `true `even 8 hour later.
The problem is that when the cache expires, the next call to the signIn intent shows directly the permission page of previous user without asking for user password as I have described above.

There's something I can post to help?

Thanks for your advice...

**Comment by albertojimenez** [comment]
Any news about this problem? I have noticed the same behavior

**Comment by samtstern** [comment]
@javerd I think the behavior you are seeing is correct.  Unless you call signOut, subsequent calls to the sign in Intent will not ask the user to choose an account  or enter a password again,

**Comment by javerd** [comment]
Thanks Sam for your interest, as you say calls to the sign in Intent don't ask for a new login process while the user grants access to the application with his account.
But a user can revoke o remove this permission on his profile using this [page](https://security.google.com/settings/security/permissions) .
The problem that I'm trying to explain is that when a user revoke that permission and the application detects it (when silentSignin returns false), the sign in Intent don't ask for a new account. It jumps to the page to confirm access rights and you can confirm the login without prompting for user an password. After that, IdToken are correct and include the info of the user....

**Comment by samtstern** [comment]
@javerd as I understand it a password should never be required on Android when doing an OAuth consent as long as the account is linked to the device and the account password has not changed.

When you revoke access from the connected apps page what that does is invalidate OAuth tokens granted to that app, but to get new tokens that app only has to show you the permissions screen again and does not require that you type in your Google account password anywhere.

**Comment by javerd** [comment]
Thanks you very much. 
Now I understand why this work different between iOS and Android versions.

**Comment by rakesh1988** [comment]
@javerd 
> Our first test shows that the cache expires in 1 hour, but sometimes silentSignInreturns trueeven 8 hour later.
How did you handle this in your app? don't you think the user expects that when he revoked the permission, he expects the app to stop working? How can we achieve this use case?

**Comment by MrD0llaro** [comment]
Hi have the same issue, exist a workaround to determine if the user revoke the grant ?

**Comment by GuyZengo** [comment]
Same issue here. I almost can't believe it hasn't been fixed.
Am I missing something?
