### ISSUE TITLE
Program terminating when i click button, Help me

### ISSUE THREAD

**Issue by axelkefas** [googlesamples/google-services#199]
2016-04-09 02:00:21.775 coffeeclub[3242:402502] Unknown class _TtC10coffeeclub14ViewController in Interface Builder file.
2016-04-09 02:00:22.447 coffeeclub[3242:] <GMR/INFO> App measurement v.2003000 started
2016-04-09 02:00:22.447 coffeeclub[3242:] <GMR/INFO> To enable debug logging set the following application argument: -GMRDebugEnabled (see http://goo.gl/Y0Yjwu)
2016-04-09 02:00:23.822 coffeeclub[3242:402502] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x7fafd1c4c2e0 'buttonHeight - auto generated by GIDSignInButton' V:[GIDSignInButton(48)]   (Names: GIDSignInButton:0x7fafd1ddb3d0 )>",
    "<NSIBPrototypingLayoutConstraint:0x7fafd1c87690 'IB auto generated at build time for view with fixed frame' V:[GIDSignInButton(44)]   (Names: GIDSignInButton:0x7fafd1ddb3d0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fafd1c4c2e0 'buttonHeight - auto generated by GIDSignInButton' V:[GIDSignInButton(48)]   (Names: GIDSignInButton:0x7fafd1ddb3d0 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2016-04-09 02:00:24.293 coffeeclub[3242:] <GMR/INFO> App measurement enabled
2016-04-09 02:00:32.295 coffeeclub[3242:402502] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'uiDelegate must either be a |UIViewController| or implement the |signIn:presentViewController:| and |signIn:dismissViewController:| methods from |GIDSignInUIDelegate|.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001084a2d85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010b0e4deb objc_exception_throw + 48
	2   CoreFoundation                      0x00000001084a2cbd +[NSException raise:format:] + 205
	3   coffeeclub                          0x0000000107ee7845 -[GIDSignIn signInWithOptions:] + 85
	4   coffeeclub                          0x0000000107eeb6fa -[GIDSignInButton pressed] + 242
	5   UIKit                               0x0000000109b32a8d -[UIApplication sendAction:to:from:forEvent:] + 92
	6   UIKit                               0x0000000109ca5e67 -[UIControl sendAction:to:forEvent:] + 67
	7   UIKit                               0x0000000109ca6143 -[UIControl _sendActionsForEvents:withEvent:] + 327
	8   UIKit                               0x0000000109ca5263 -[UIControl touchesEnded:withEvent:] + 601
	9   UIKit                               0x0000000109ba599f -[UIWindow _sendTouchesForEvent:] + 835
	10  UIKit                               0x0000000109ba66d4 -[UIWindow sendEvent:] + 865
	11  UIKit                               0x0000000109b51dc6 -[UIApplication sendEvent:] + 263
	12  UIKit                               0x0000000109b2b553 _UIApplicationHandleEventQueue + 6660
	13  CoreFoundation                      0x00000001083c8301 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	14  CoreFoundation                      0x00000001083be22c __CFRunLoopDoSources0 + 556
	15  CoreFoundation                      0x00000001083bd6e3 __CFRunLoopRun + 867
	16  CoreFoundation                      0x00000001083bd0f8 CFRunLoopRunSpecific + 488
	17  GraphicsServices                    0x000000010cd85ad2 GSEventRunModal + 161
	18  UIKit                               0x0000000109b30f09 UIApplicationMain + 171
	19  coffeeclub                          0x0000000107e4d902 main + 114
	20  libdyld.dylib                       0x000000010bba892d start + 1
	21  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by ianbarber** [comment]
You need to set `[GIDSignIn sharedInstace].uiDelegate` as well as the regular delegate.
