### ISSUE TITLE
Google/SignIn.h file not found

### ISSUE THREAD

**Issue by muhasturk** [googlesamples/google-services#202]
Try to launch iOS SignIn service

**Comment by ianbarber** [comment]
We'll need a few more details! Have you tried running pod update to make sure you're on the latest version? Can you see the SignIn.h file in the Google pod? Can you paste in your Podfile.lock so we can see which versions you are dealing with?

I presume you're calling `#import <Google/SignIn.h>`

**Comment by damilolah** [comment]
yes, i have similar issue. I'm using this tutorial http://www.appcoda.com/google-sign-in-how-to/ to implement google sign in to my ios app but it errors out - in GSignIn-Bridging_header class -

#import <GoogleSignIn/GoogleSignIn.h>
It gives two errors:
unable to import GSignIn_bridging-header and GoogleSignIn.h file not found

Please help

**Comment by ianbarber** [comment]
You should be able to use modules with GSI now - try just `import GoogleSignIn`

**Comment by samtstern** [comment]
@damilolah closing this issue as @ianbarber has offered the ideal solution, please re-open if that does not work.

**Comment by wieblinger1** [comment]
Try integrating the SDK manually (here instructions: https://developers.google.com/identity/sign-in/ios/sdk/ ). Then use #import "GoogleSignIn/GoogleSignIn.h" instead of #import "TransitionController.h"
