### ISSUE TITLE
Cannot use Binary Code

### ISSUE THREAD

**Issue by cytryn** [googlesamples/google-services#204]
This is a big issue for my team because the app grows in size more than 40% if I don't use binary code.

Another thing is please get rid of the damn .plist

Would be easier if we could just setup properties on the code.

**Comment by jimmaye** [comment]
Hi

Would be awesome with a status regarding the full Bitcode support (which is what I think @cytryn refers to with the term "Binary Code"?).

**Comment by cytryn** [comment]
@jimmaye exactly!

**Comment by ianbarber** [comment]
Full bitcode support should now be available!
