### ISSUE TITLE
Google Sign-In crash on ios7

### ISSUE THREAD

**Issue by piotrros** [googlesamples/google-services#206]
Hi, I've followed documentation and successfully implemented google sign-in in my app. However I'm getting following exception:
`-[__NSCFString containsString:]: unrecognized selector sent to instance`

when trying to call 
`[[GIDSignIn sharedInstance] signIn];`

on iOS7. 

As I found out it's a problem with missing containsString method on iOS7: http://stackoverflow.com/questions/26410420/nsstring-containsstring-crashes

It seems easy to fix, but of course it's "inside" google sign-in library. For now I can't use google sign-in on ios7. It's working on iOS8+ though.

**Comment by ianbarber** [comment]
Closing - believe this should not be happening in recent versions, but please reopen if it is!
