### ISSUE TITLE
Could not connect to GCM: The operation couldn’t be completed. (com.google.gcm error 501.)

### ISSUE THREAD

**Issue by gadonski** [googlesamples/google-services#211]
The same problem of issue #205 is happing to me.

```
2016-04-27 10:55:11.190 GcmExampleSwift[4831:] <GMR/INFO> App measurement v.2003000 started
2016-04-27 10:55:11.191 GcmExampleSwift[4831:] <GMR/INFO> To enable debug logging set the following application argument: -GMRDebugEnabled (see http://goo.gl/Y0Yjwu)
2016-04-27 10:55:11.227: GCM | GCM library version 1.1.4
2016-04-27 10:55:11.290: GCM | GCM registration is not ready with auth credentials
Could not connect to GCM: The operation couldn\342\200’t be completed. (com.google.gcm error 501.)
2016-04-27 10:55:11.354 GcmExampleSwift[4831:] <GMR/INFO> App measurement enabled
```

Any ideia?

**Comment by jamescaruso** [comment]
Same problem for me.

**Comment by earlyfai** [comment]
same here, completely no idea what's wrong.

**Comment by gadonski** [comment]
@earlyfai try to make a new certificate, identifier and provisioning profile on Apple. Check if your device has the new provisioning profile. 

For me after repeat the steps above, this issue was solved.

**Comment by alexszilagyi** [comment]
@gadonski : Do you have any idea how many times you've tried? I've already tried at least three or four times and still facing this issue.

**Comment by gadonski** [comment]
@alexszilagyi omg wtf .... i have tried one time only dude. Have checked the provisioning profile on your device? Or check this on xcode:
preferences -> accounts -> select your acocunt -> select your team -> view details -> download all provisioning profiles

**Comment by alexszilagyi** [comment]
@gadonski : yeah. Will do that one more time 😄  Thanks +1!

**Comment by alexszilagyi** [comment]
@gadonski : it proved that I needed to specify explicitly the developer account & provisioning profile on Code signing section of the target.

**Comment by alaa-alshamy** [comment]
@alexszilagyi  can u explain what u did more clearly please ?

**Comment by alexszilagyi** [comment]
@alaa-alshamy : Have you tried what I was mentioning [here](https://github.com/googlesamples/google-services/issues/205#issuecomment-219522036) or [@mohitsharma0690](https://github.com/googlesamples/google-services/issues/205#issuecomment-228569641)'s comment.

**Comment by alaa-alshamy** [comment]
@alexszilagyi ok i will give it a try , thanks for ur reply
