### ISSUE TITLE
Google App Invites For Android - Emails sent to none gmail addresses are rejected.

### ISSUE THREAD

**Issue by positivelymade** [googlesamples/google-services#212]
I'm testing Google App Invite beta.

```
Emails sent to gmail addresses work fine.
Emails sent to a none gmail addresses are rejected (go daddy emails).
```

**Is this suppose to happen?**

Below is the response I received:

> Delivery to the following recipient failed permanently:
> 
> ```
>  contact@philipherbert.com
> ```
> 
> Technical details of permanent failure:
> Google tried to deliver your message, but it was rejected by the server for the recipient domain philipherbert.com by smtp.secureserver.net. [72.167.238.29].
> 
> The error that the other server returned was:
> 552 5.2.0 qrks1s0150u9tuR01 - qrks1s0150u9tuR01rktpH This message has been rejected due to content judged to be spam by the internet community IB212 - If you feel this is in error, please submit a request using the following page. https://checkspam.secureserver.net/?sid=qrks1s0150u9tuR01&mid=qrks1s0150u9tuR01rktpH
> 
> ----- Original message -----
> 
> X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
>         d=1e100.net; s=20130820;
>         h=x-original-authentication-results:x-gm-message-state:delivered-to
>          :mime-version:date:reply-to:list-unsubscribe:message-id:subject:from
>          :to;
>         bh=guMsU9dqsO3QSz0x4H4G+f375XseppG/TehoPIHr7FM=;
>         b=ROQZUxVuNiS5hpgzG9GBTPPst1n/i6I9Wv1taE+HCBaUROW+ljisw0UwIHsENGjPpa
>          jUq29ZG7gjqI4u/BwgyPTf0I7rhwqoTNnQcD3/BvWdN5RwKfbWlaPvSuy/7Amt3kgIX5
>          pp1uud2nejrme8uw1Z1FM9u7e/VucFPu2irforak1hCSJZzR96QFrw4oi7PMpTdrzbH4
>          8GXXOOuQoXGuuuMaNzuXCJQXvyDC2S8Y8Q3eijtTvlPHouCn+SC9RExix+uEEaQpM0/s
>          q2iYw04v7qDa+FyDgI+coTQI69VSLM5qyDpc1YRmDhjw32X4HyLD1ktYpTqXYqIgSdol
>          hvKA==
> X-Original-Authentication-Results: mx.google.com;       spf=pass (google.com: domain of 3MRMsVwkJCcY6otuym5mmsymux.o0y6otuym5mmsymux.o0y@unified-notifications.bounces.google.com designates 209.85.223.197 as permitted sender) smtp.mailfrom=3MRMsVwkJCcY6otuym5mmsymux.o0y6otuym5mmsymux.o0y@unified-notifications.bounces.google.com;       dmarc=fail (p=NONE dis=NONE) header.from=gmail.com
> X-Gm-Message-State: AOPr4FXH4kIQiDT4c9BIkoy4zBrVnVk7Bk16cyVDIJpzNVmElYZUcf1hnZEmQwHX5ik7cs6W3W1l7QjFIpgoPN2UDsyCkkQ=
> X-Received: by 10.25.22.86 with SMTP id m83mr8743750lfi.66.1462506292418;
>         Thu, 05 May 2016 20:44:52 -0700 (PDT)
> X-Forwarded-To: contact@philipherbert.com
> X-Forwarded-For: uchimataa@gmail.com contact@philipherbert.com
> Delivered-To: uchimataa@gmail.com
> Received: by 10.25.159.211 with SMTP id i202csp68031lfe;
>         Thu, 5 May 2016 20:44:50 -0700 (PDT)
> X-Received: by 10.50.88.36 with SMTP id bd4mr7645937igb.23.1462506290181;
>         Thu, 05 May 2016 20:44:50 -0700 (PDT)
> Return-Path: 3MRMsVwkJCcY6otuym5mmsymux.o0y6otuym5mmsymux.o0y@unified-notifications.bounces.google.com
> Received: from mail-io0-f197.google.com (mail-io0-f197.google.com. [209.85.223.197])
>         by mx.google.com with ESMTPS id e67si13899575ioa.110.2016.05.05.20.44.49
>         for uchimataa@gmail.com
>         (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
>         Thu, 05 May 2016 20:44:50 -0700 (PDT)
> Received-SPF: pass (google.com: domain of 3MRMsVwkJCcY6otuym5mmsymux.o0y6otuym5mmsymux.o0y@unified-notifications.bounces.google.com designates 209.85.223.197 as permitted sender) client-ip=209.85.223.197;
> Authentication-Results: mx.google.com;
>        spf=pass (google.com: domain of 3MRMsVwkJCcY6otuym5mmsymux.o0y6otuym5mmsymux.o0y@unified-notifications.bounces.google.com designates 209.85.223.197 as permitted sender) smtp.mailfrom=3MRMsVwkJCcY6otuym5mmsymux.o0y6otuym5mmsymux.o0y@unified-notifications.bounces.google.com;
>        dmarc=fail (p=NONE dis=NONE) header.from=gmail.com
> Received: by mail-io0-f197.google.com with SMTP id k129so223346735iof.0
>         for uchimataa@gmail.com; Thu, 05 May 2016 20:44:49 -0700 (PDT)
> MIME-Version: 1.0
> X-Received: by 10.157.61.117 with SMTP id a108mr11541850otc.5.1462506289902;
>  Thu, 05 May 2016 20:44:49 -0700 (PDT)
> Date: Thu, 05 May 2016 20:44:49 -0700 (PDT)
> X-Notifications: XEAAAAAnPuHwxYetAAB6ztMSJ5vo
> Reply-To: uchimataa@gmail.com
> List-Unsubscribe: https://notifications.google.com/unsubscribe/AJ7SsMkJA27udJsCqzLD5EfeAFxxeZAEiLXoM7ZQ_06qwJoB346fw4CJI3u6MsnT2-cctn2yIIY752NaxhY9xnkaFj8JGOIN8mOUb-zTazCsOY0fyxkNmou_l_ZhrKLTJgaK5tQxtwo1a0iRai66D3Bo89Pr_l-Xnw
> Message-ID: E69zs-XklVp5h3IXdEfDeQ@notifications.google.com
> Subject: Hello World
> From: uchimataa@gmail.com
> To: uchimataa@gmail.com
> Content-Type: multipart/alternative; boundary=001a11c13fc8e4427e0532244748
> 
> Install this application via
> https://uj57m.app.goo.gl/i/725028426433-675cf350-37a0-4624-b204-b983a2c1c829

**Comment by samtstern** [comment]
@positivelymade where exactly do you see this large error response?

**Comment by positivelymade** [comment]
That is the response returned to the gmail address that Google App Invites is sending the invites through/from.

I sent the invite to uchimataa@gmail.com(gmail address) and contact@philipherbert.com(go daddy address).

Trying sending to contact@philipherbert.com and your gmail address; and you will see the response above.

**Comment by samtstern** [comment]
It looks like the GoDaddy email server is rejecting the message as spam.  Unfortunately this is something that may be very hard to fix on our side.  I will report it to the proper engineering folks and see what can be done.  Thanks for the interesting report!

**Comment by positivelymade** [comment]
Not everyone uses Gmail as there main email provider. If this problem occurs with go daddy, chances are that it is/will occur with other providers. 

In my case, I am developing an internal company app for a telecommunications company, a key feature would be app invites. If invitations are rejected, that would render Google App Invites pointless.

Please try to fix this, and keep me posted. I will have to omit Google App Invites until this issue is resolved, and I do understand that GAI is in beta.

Thanks.

**Comment by ianbarber** [comment]
Closing - Google App Invites has been replaced by Firebase Invites.
