### ISSUE TITLE
unsubscribe from all topics with regular expression?

### ISSUE THREAD

**Issue by travoux** [googlesamples/google-services#219]
I am receiving INVALID_PARAMETERS when calling GcmPubSub.unsubscribe with regular expression as topic eg:- /topics/[.]{1,}

Is it not allowed to use regular expression to unsubscribe?
https://developers.google.com/cloud-messaging/ios/api/gcm/interface_g_c_m_pub_sub#instance-method-summary

If not, how do I unsubscribe from all the topics a particular device is subscribed to?

**Comment by ianbarber** [comment]
You just have to unsubscribe from them individually unforunately! Keep them as a list and iterate over is the recommended approach, sorry!
