### ISSUE TITLE
cant install GCM

### ISSUE THREAD

**Issue by mirzadelic** [googlesamples/google-services#22]
Hi,
i am getting error when installing gcm from pod file.
I tried without use_framework, and still same error.

Any solution?

![screen shot 2015-06-28 at 17 13 30](https://cloud.githubusercontent.com/assets/1878794/8396872/07e371ea-1db9-11e5-8126-9320220201ab.png)

**Comment by silvolu** [comment]
Thanks for reporting this; the problem is discussed in [this CocoaPods issue](https://github.com/CocoaPods/CocoaPods/issues/3194). We're working on a fix, but at this moment I don't know when it will be available.
I will update this issue as soon as I know more.

**Comment by mirzadelic** [comment]
Thanks, please write here when there will be version with use_framework.

**Comment by alibasta** [comment]
Same here. Thanks for working on it @silvolu !

**Comment by patricks** [comment]
+1

**Comment by joel-ipsy** [comment]
+1

**Comment by silvolu** [comment]
This should be fixed if you update to CocoaPods 0.38.x.
Please reopen if you still have problems.

**Comment by jasperwanglin** [comment]
I'm still getting this error. CocoaPods 0.38.2.

**Comment by mgerdt** [comment]
+1

**Comment by silvolu** [comment]
I just tried with 0.39.0 and it works, can you try to update cocoapods or post the podfile you're using?

**Comment by ceoacai** [comment]
@mirzadelic did you solve this？ @silvolu I still have this issue when using gRPC

**Comment by mirzadelic** [comment]
Just use with 'use_frameworks' and:
'''
	pod 'Google'
	pod 'Google/CloudMessaging'
'''

**Comment by Jyaowen** [comment]
The 'Pods-' target has transitive dependencies that include static binaries: (/Pods/OpenSSL/lib/libcrypto.a  and  /Pods/OpenSSL/lib/libssl.a)
