### ISSUE TITLE
Can't open the project with Android Studio 2.1 - missing google-services.json

### ISSUE THREAD

**Issue by djabi** [googlesamples/google-services#221]
Error:Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it.
   Searched Location:
  /home/djabi/github/google-services/android/analytics/app/src/debug/google-services.json
  /home/djabi/github/google-services/android/analytics/app/google-services.json

**Comment by samtstern** [comment]
An explanation for why this is working as intended is in #220. Please continue the discussion there if you have more questions.
