### ISSUE TITLE
On non Play devices it is possible for Google Analytics to drop data

### ISSUE THREAD

**Issue by djabi** [googlesamples/google-services#223]
GoogleAnalytics has a receiver and service that are used to upload data in background. On Play devices the service is implemented inside Google Play services. On non-Play devices the service is implemented inside the app itself. For proper hand off between the receiver and the services the application needs wake lock permission. Without it it is possible that Android will terminate the application process after the receiver starting the service and before the service has received the start service request. To prevent this the application needs android.permission.WAKE_LOCK user permission in the application manifest. The example currently doesn't have that.

https://github.com/googlesamples/google-services/blob/master/android/analytics/app/src/main/AndroidManifest.xml#L6

**Comment by ianbarber** [comment]
Our primary support with these samples is for Google Play services devices, but you're complete correct - thanks for the note!
