### ISSUE TITLE
getIdToken() returns an expired token(JWT)

### ISSUE THREAD

**Issue by rakesh1988** [googlesamples/google-services#226]
Hi All,
I have been experimenting on GoogleSignInOptions and GoogleApiClient. My code is same as the once published in google documentations. When I request JWT via getIdToken(), I get an expired token. According to https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInApi.html#public-methods, silentSignIn method says that "If you use the ID token expiry time to determine your session lifetime, you should retrieve a refreshed ID token, by calling silentSignIn prior to each API call to your application server. " How do I make sure that I have a new token once the previous JWT is expired.

I have put all my thoughts on this SO question http://stackoverflow.com/questions/37363213/google-always-returns-expired-id-tokenjwt

I will be very happy if someone can comment on it

**Comment by rsteckler** [comment]
I'm getting this same behavior.  There aren't any answers in the SO thread, either.  @rakesh1988 and @ianbarber : Did you guys find a solution or just closing this because it's old?

**Comment by tprochazka** [comment]
I have the same problem for some users it return already invalid token and I can found how to solve it yet.

**Comment by dinuscxj** [comment]
I'm getting this same behavior.

**Comment by tprochazka** [comment]
I found only one workaround, remove the account from the device and add it back again.
Then some internal cache stored in the account will be deleted and new token is provided.

**Comment by LucaGabi** [comment]
:) next step would be to replace the phone ..
