### ISSUE TITLE
GoogleSignatureVerifier error: signature not valid when call  requestIdToken!

### ISSUE THREAD

**Issue by EdisonNguyen** [googlesamples/google-services#228]
Hello Google team,

I face with problem when trying to getIdToken for my app flow:

https://developers.google.com/identity/sign-in/android/backend-auth#send-the-id-token-to-your-server

Every thing fine except requestIdToken(getString(R.string.server_client_id)). Our app will return error like:

05-24 19:17:40.091: V/GoogleSignatureVerifier(14539): com.vgames.gungunonline signature not valid.  Found: 
05-24 19:17:40.091: V/GoogleSignatureVerifier(14539): MIIDXzCCAkegAwIBAgIEBNOpETANBgkqhkiG9w0BAQsFADBgMQswCQYDVQQGEwJ2aTEMMAoGA1UE
05-24 19:17:40.091: V/GoogleSignatureVerifier(14539): CBMDaGNtMQwwCgYDVQQHEwNoY20xDjAMBgNVBAoTBXZtb2dhMQwwCgYDVQQLEwNkZXYxFzAVBgNV

...

I saw that this problem posted in Google + stackoverflow from 13 May. Until now no good answer for us.

I think my problem the same with: http://stackoverflow.com/questions/37333220

Could you check and give me your advice.

I tested in: SignInActivity googlesamples checkout 22 - May.

Thanks,
Tài Hải

**Comment by samtstern** [comment]
@EdisonNguyen you can ignore the `GoogleSignatureVerifier` errors in logs.  That's something that was meant for internal consumption and we accidentally left the logging on in the public release.

Are you having any other issues with your sign in flow, or are you just worried about that error?

**Comment by thenewmr** [comment]
I saw this error today and found maps to longer work in our app.  Can't tell whether there's a connection or not.  We're using maps v2.

**Comment by ianbarber** [comment]
No connection to this error.
