### ISSUE TITLE
Cloud Messaging for Android Sample is failing.

### ISSUE THREAD

**Issue by indoty** [googlesamples/google-services#23]
The Android Quick sample doesn't build in Android Studio:
https://developers.google.com/cloud-messaging/android/start

It was working fine on the 7th July 2015.

I noticed that Gradle 2.5 was released on the 8th July 2015.

Now I get the following error in Android Studio when I try to sync the Project with the Gradle:

                    Plugin is too old, please update to a more recent version,
                    or set ANDROID_DAILY_OVERRIDE environment variable to
                    "57aab342f59bfc5424ffe646db1eba9f211c73d0"

**Comment by kroikie** [comment]
Moved android gradle plugin to 1.3.0-beta3. Should work as expected now.

**Comment by indoty** [comment]
This is what I find in the build.gradle file below, I've just downloaded the sample and tried to run it as is with no changes.  It's referring to plugin 1.3.0-beta3. 


Build.gradle

// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.0-beta3'
        classpath 'com.google.gms:google-services:1.3.0-beta1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

**Comment by kroikie** [comment]
Are you able to build it now?

**Comment by indoty** [comment]
No, I can build, I get an when trying to sync project with Gradle

**Comment by kroikie** [comment]
what error are you getting?

**Comment by indoty** [comment]
Hi, I've attached a screen shot.


![androiderror](https://cloud.githubusercontent.com/assets/12471536/8593979/157ba9c4-2680-11e5-8d13-18d4b61c6500.png)

**Comment by indoty** [comment]
I also see stuff like this in the idea.log:


2015-07-09 21:13:54,391 [  20469]   INFO - .project.GradleProjectResolver - Gradle project resolve error 
org.gradle.tooling.BuildException: Could not run build action using Gradle installation 'C:\Program Files\Android\Android Studio\gradle\gradle-2.2.1'.
	at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:57)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:57)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)

**Comment by indoty** [comment]
I've got a fresh installation of Android Studio and got the sample code from github.  Thanks for any help

**Comment by indoty** [comment]
OK, I got it working now:

Made the following change:

        classpath 'com.android.tools.build:gradle:1.1.3'

**Comment by RahulSDeshpande** [comment]
Whohooo..

Thank you @indoty & @kroikie..
I worked for me.
```
BUILD SUCCESSFUL
```

It was better I checked the **Issues** page first :+1: , rather than hunting Google or StackOverflow !!

Cheers All !! :dancer:
