### ISSUE TITLE
GCM push, device do not receive message for long time

### ISSUE THREAD

**Issue by D4n16l6** [googlesamples/google-services#232]
I have an application that is to receive push notifications for a short time and standby devices. My huawey with Android 4.3 receives notifications in time all things considered reasonable (0-240 minutes) when in standby, while the J5 Samsung with Android 5 employs much more even a day or more. I clearly updated the App because it would use the latest versions of play services (8.4 right now for me) and used the sample code provided by Google for its Android 5.1 and 6, but this did not produce any result. Do not place the code for the time being but if required prodigal me to. What I wonder is if the problem I have is something that others have and if there are solutions. I have tried using the AlarmManager to "wake" the device every four hours to reestablish a connection to the internet and repeat the token request to GCM GCM hoping that sending the message in the queue but it did not help. Use PHP to send the message and the message is marked as "high priority.". Thanks in advance.

**Comment by ianbarber** [comment]
Sorry for lack of answer. We don't have good visibility into what might be happening with deliver of messages. It can be to do with the cell network or anything that may prevent message delivery (firewalls etc.) but not sure we have much to offer here!
