### ISSUE TITLE
application:openURL:sourceApplication:annotation: is not getting called in iOS8

### ISSUE THREAD

**Issue by annamalairaj** [googlesamples/google-services#236]
I upgraded GoogleSignIn SDK from 2.4.0 to 4.0.0. App works fine in iOS9. But in iOS8.4(which I am currently testing in) after successful login it gets redirected to the app, but neither `application:openURL:sourceApplication:annotation:` nor `application:didFinishLaunchingWithOptions:` is getting called. Receiving warning as

> < FIRAnalytics/WARNING > Implementation of application:openURL:sourceApplication:annotation: not found. Please add the handler into your App Delegate. Class: CleverTapAppDelegateSurrogate`

But I have implemented the methods. Does anyone have any idea? I read the docs and nothing specific is mentioned. Am I missing something to support iOS8 as well?

```
#if __IPHONE_9_0

- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary *)options {

   return YES; 
}

#else

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {

   return YES;
}

#endif
```

Would someone direct me in the right way? Thanks in advance. By the by I am using Xcode version 7.3.

**Comment by ianbarber** [comment]
You probably want ifdef not just if in that # conditional. Try

    #if defined(__IPHONE_9_0)

**Comment by annamalairaj** [comment]
Let me try

**Comment by annamalairaj** [comment]
No luck. Still the same. Actually either of the method is called after successfully logged in Facebook. It occurs only in iOS <9.

**Comment by ianbarber** [comment]
Sorry for the lack of response here. I'll close now, but if still happening with latest releases please reopen.
