### ISSUE TITLE
Failed to resolve: com.google.android.gms:play-services-measurement:9.0.2

### ISSUE THREAD

**Issue by supreetuf** [googlesamples/google-services#237]
Getting this error after updating play services to 9.0.2

**Comment by samtstern** [comment]
Make sure you are using the `google-services` plugin at version `3.0.0` or higher.

**Comment by supreetuf** [comment]
updated it.. still getting the same error
i am using this in my project level gradle file
        `classpath 'com.google.gms:google-services:3.0.0'`
and these dependencies in my app level build gradle
    `compile 'com.google.android.gms:play-services-base:9.0.2'`
    `compile 'com.google.android.gms:play-services-ads:9.0.2'`
    `compile 'com.google.android.gms:play-services-measurement:9.0.2'`
    `compile 'com.google.android.gms:play-services-analytics:9.0.2'`
    `compile 'com.google.android.gms:play-services-gcm:9.0.2'`

**Comment by samtstern** [comment]
Ah ok.  `play-services-measurement` was not published after version 8.4.0.  You should remove it from your dependencies and replace it with `com.google.firebase:firebase-analytics:9.0.2` which has equivalent functionality.  If you were using the `AppMeasurement` class in your code anywhere, use `FirebaseAnalytics` instead, it should expose all of the same methods.
