### ISSUE TITLE
GoogleAppIndexing: Bitcode Support (again #2)

### ISSUE THREAD

**Issue by vinceis1337** [googlesamples/google-services#238]
Issue https://github.com/googlesamples/google-services/issues/95 was closed again, however I continue to recieve this error in GoogleAppIndexing version 2.0.3 and also Firebase/AppIndexing version 3.2.1.

```
ld: bitcode bundle could not be generated because '........path......Pods/GoogleAppIndexing/Frameworks/GoogleAppIndexing.framework/GoogleAppIndexing(GSDAppIndexing.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64
```

The Firebase error is nearly the same except the Pod is Firebase, of course.

**Comment by samtstern** [comment]
@vinceis1337 thanks for the report.  We've moved all discussions of Firebase App Indexing over to https://github.com/firebase/quickstart-ios so please re-open this issue over there and someone will be able to help you.
