### ISSUE TITLE
Android, SignInHubActivity can not be closed (auto restarts itself)

### ISSUE THREAD

**Issue by nbarishok** [googlesamples/google-services#241]
Nexus 9, Android 6.0.1

Issue while implementing Google Sign In

**Preconditions**
- com.google.gms:google-services:3.0.0
- com.google.android.gms:play-services-auth:9.0.2
- **No Google Account** on device

**Steps to reproduce**
1. Launch SignInHubActivity like this:
public void login(Fragment fragment) {
        Intent signInIntent = Auth.GoogleSignInApi.getSignInIntent(googleApiClient);
        fragment.startActivityForResult(signInIntent, RC_SIGN_IN);
    }
2. SignInHubActivity with "Checking info..." -> "Add your account" screen appears
3. Tap "back" button

**Expected behavior**
Previous screen is shown

**Actual behavior**
SignInHubActivity restarts itself or so, and "Checking info..." -> "Add your account" screen appears again

On other devices we have, SignInHubActivity returns result as expected.

**Comment by ianbarber** [comment]
Going to close this as I believe it should be resolved, but please reopen if still occurring.
