### ISSUE TITLE
GCM example code in ECLIPSE

### ISSUE THREAD

**Issue by GirijaHegde** [googlesamples/google-services#244]
Hi,
I am very new to Android studio and I don't want to build my entire project in android studio to just make GCM work. I tried this sample code in Android Studio and looks like it is working but please let me know how it is different from Eclipse code and why I am not getting Notification for the published message from AWS console. Can you please Provide Eclipse example code for the same as soon as possible.

**Comment by samtstern** [comment]
@GirijaHegde sorry but Eclipse is no longer officially supported by Google so we will not be providing any Eclipse sample code.  You should strongly consider taking the time to upgrade to Android Studio, it has many other benefits.
