### ISSUE TITLE
google-services.json config is supposed to be used?

### ISSUE THREAD

**Issue by mutablestudio** [googlesamples/google-services#246]
How come this project references newTracker(R.xml.global_tracker) when the documentation at developers.google.com/analytics states that:

"The Google Services plugin for Gradle parses configuration information from the google-services.json file". I have the google-services.json in my project, now how do I init the tracker with it?

**Comment by samtstern** [comment]
@mutablestudio the `com.google.gms:google-services` plugin mentioned in the guides uses the json file to populate XML files at build time, which is how you get `R.xml.global_tracker`.

See:
https://github.com/googlesamples/google-services/blob/master/android/analytics/build.gradle#L10
https://github.com/googlesamples/google-services/blob/master/android/analytics/app/build.gradle#L32
