### ISSUE TITLE
Update of Google Play Services on Emulator

### ISSUE THREAD

**Issue by osmaantahir** [googlesamples/google-services#247]
When i ran quickstart for GCM i got error on emulator NEXUS 5 (API 23) that google play services needs to be updated. how to update these on emulator so that i can run application.

**Comment by samtstern** [comment]
@osmaantahir sorry about this, we are currently working to get out emulator images that are compatible with the `9.2.0` libraries.  There were some last minute emulator issues that took longer than expected to work out.

Right now emulators support up to `9.0.2` libraries, and I will update this issue when there is an image supporting `9.2.0`.

**Comment by samtstern** [comment]
The latest emulators are now released, check your Android SDK manager for updates.  Thanks for your patience!
