### ISSUE TITLE
push notification in foreground and backgrand FCM 

### ISSUE THREAD

**Issue by diegogui1** [googlesamples/google-services#248]
Hello ,

some time ago published in

http://stackoverflow.com/questions/38020348/send-a-notification-background-firebase-android

a problem that I have with the push notification in foreground and backgrand FCM after you read the link sugueris me to look at my app android?

backgrand foreground and take different style.

Regards,

**Comment by samtstern** [comment]
Since this is about FCM it should be posted on the repo [firebase/quickstart-android](/firebase/quickstart-android).

Before you post a new issue there, I'd suggest reading this discussion:
https://github.com/firebase/quickstart-android/issues/4
