### ISSUE TITLE
[iOS] 'serverAuthCode' is always nil when using a simulator

### ISSUE THREAD

**Issue by aleclarson** [googlesamples/google-services#252]
Using the [GoogleSignin SDK for iOS](https://developers.google.com/identity/sign-in/ios/), I cannot seem to get a non-nil `serverAuthCode` when using a simulator. Device works as expected.

I've tested on both iOS 8.4 and iOS 9.3 without success.

```objc
GIDSignIn *signIn = [GIDSignIn sharedInstance];
signIn.delegate = self;
signIn.uiDelegate = self;

signIn.scopes = config[@"scopes"];
signIn.clientID = config[@"clientID"];
signIn.serverClientID = config[@"serverClientID"];

[signIn signInSilently];
```

**Comment by aleclarson** [comment]
It's not documented anywhere, but you will never receive a `serverAuthCode` when using `GIDSignIn#signInSilently`.

The reasoning is that you only need the `serverAuthCode` immediately after user consent. From then on, you can just refresh the server's access token using the refresh token. Thus, there is no need to ever receive a `serverAuthCode` when using `GIDSignIn#signInSilently`.

At least that's my guess. :)

**Comment by mr746866** [comment]
Can you please share the code to get the `serverAuthCode` after `signInSilently`?

**Comment by aleclarson** [comment]
@mr746866

Before calling `signInSilently`, you must first set: `signIn.serverClientID`

```objc
- (void)signIn:(GIDSignIn *)signIn
        didSignInForUser:(GIDGoogleUser *)user
        withError:(NSError *)error
{
  // Then you can access: user.serverAuthCode
}
```
