### ISSUE TITLE
Android : Not receiving GCM notification when app is inactive

### ISSUE THREAD

**Issue by midhunm45** [googlesamples/google-services#254]
I'm using this  demo app for GCM, added google-services.json file . I'm sending notification using post-man. And when the app is active and in background, I'm getting the notification, but not when the app is inactive. I heard that GcmReceiver automatically handles that, but not getting anything.Do I need to do anything else to achieve this.
Thank you.

**Comment by CongBaDo** [comment]
I faced the same issue too. In Android 5.X, I can not receive notification when the app is force kill. Any one have solution, please share it

**Comment by krupalagile** [comment]
http://stackoverflow.com/questions/35257410/how-to-customize-notification-display-and-tone-when-using-gcmreceiver-and-gcmlis/35368530#35368530

**Comment by ianbarber** [comment]
I would recommend upgrading to Firebase Cloud Messaging here, which simplifies the integration: https://firebase.google.com/docs/cloud-messaging/android/client
