### ISSUE TITLE
Do we need to start RegistrationIntentService every time we start the app

### ISSUE THREAD

**Issue by feresr** [googlesamples/google-services#256]
Describe your environment
- Device: Nexus 5
- OS version: Marshmallow
- SDK version: 23
- [Android] Google Play Services version: 9.4.0

Describe the problem:
#### Steps to reproduce:

This app tries to get a token every time it starts, by launching RegistrationIntentService.class on the `OnCreate` method of the activity.

Do we really need to do this? Can't we just store the token in the SharedPreferences and fetch it ONLY if it's missing. This would also prevent calling sendRegistrationToServer() multiple times. 

I'm referring to this particular piece of code: 

https://github.com/googlesamples/google-services/blob/master/android/gcm/app/src/main/java/gcm/play/android/samples/com/gcmquickstart/MainActivity.java#L73
#### Observed Results:
- Multiple tokens are fetched (and then sent to my server) upon application lifecycle
#### Expected Results:
- Just get the token once. I understand GCM will call InstanceIDListenerService#onTokenRefresh() whenever it needs to refresh it? Am I right?
#### Relevant Code:

```
public class MainActivity extends AppCompatActivity {

....
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

....
        // Registering BroadcastReceiver
        registerReceiver();

        if (checkPlayServices()) {
            // Start IntentService to register this application with GCM.
            Intent intent = new Intent(this, RegistrationIntentService.class);
            startService(intent);
        }
    }
```

**Comment by feresr** [comment]
There are more people asking the same question on StackOverflow

http://stackoverflow.com/questions/36229905/how-often-to-call-gcm-registrationintentservice

http://stackoverflow.com/questions/35405920/gcm-registrationintentservice-gettoken-at-each-app-startup/38886290#38886290

http://stackoverflow.com/questions/32164880/confused-about-gcm-token-updation-process/32165073#32165073

**Comment by ianbarber** [comment]
@kroikie - i don't think we do need to call it every time right? The share prefs idea sounds reasonable.

**Comment by samtstern** [comment]
This is an old issue so I am going to add a comment and then close it.  You can store the token in shared prefs as you suggested, just make sure to get a new one whenever you get a new Instance ID (which happens on a rarely-but-not-never basis).

Also these complexities are one good reason to move from the GCM client library to FCM, the FCM client library manages all of that on your behalf.
