### ISSUE TITLE
Unable to fetch GCM device token

### ISSUE THREAD

**Issue by pankajjain-ranosys** [googlesamples/google-services#259]
### Environment
- Device: Sony c5 ultra
- OS version: 5.1
- SDK version: 21
- [Android] Google Play Services version: 8298000
### Problem
- I am getting following error while getting the device token `An error occurred while either fetching the InstanceID token, sending the fetched token to the server or subscribing to the PubSub topic. Please try running the sample again.`
#### Steps to reproduce:
1. Get the Sample code [https://github.com/googlesamples/google-services/tree/master/android/gcm](url)
2. Get and Add your API key and Sender ID
3. Compile and run the sample
#### Observed Results:
- Getting Error in particular device but in other device it is working fine.
#### Expected Results:
- Should get the device token from GCM for the device

**Comment by ianbarber** [comment]
That is a realtively old version of Google Play Services - can you try updating the device to a newer one and see if that resolves the issue? 

Is there anything else in the log as well that might indicate the issue?
