### ISSUE TITLE
Plus.PeopleApi.getCurrentPerson(mgoogleapiclient) return null. 

### ISSUE THREAD

**Issue by binaykumarrana** [googlesamples/google-services#260]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.

### Step 2: Describe your environment

  * Device: _____
  * OS version: _____
  * SDK version: _____
  * [Android] Google Play Services version: _____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, log output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

Plus.PeopleApi.getCurrentPerson(mgoogleapiclient) returning null sudden. It was working fine and build was uploaded on play store. I am unable to figure out what's happening sudden. 

Thanks in advance 
Binay

**Comment by samtstern** [comment]
@binaykumarrana please use the issue template, it is there to help us understand your issue.  With the template blank and only the issue title filled out I can't guess what's going wrong.

Please fill out the template and re-open this issue if you still need help.
