### ISSUE TITLE
Nil login on iOS 10

### ISSUE THREAD

**Issue by abiaad** [googlesamples/google-services#261]
### Environment

  * Device: iPhoneSE Simulator
  * OS version: 10 GM
  * SDK version: 10 GM
  * Not tested on other SDKs
  
### Description:

When trying to log, nothing is happening but signIn delegate method is triggered.

#### Steps to reproduce:

  1. Download project and configure it
  2. Build and run
  3. Add breakpoint to delegate signIn method
  4. Tap on signIn
  5. No Safari window is displayed
  6. delegate signIn method is triggered with nil user and error code to -4

Did someone has this problem ? I tried to had clientID in AppDelegate but still the same issue.

**Comment by amaralpb** [comment]
Hello @abiaad were you able to resolve this issue, and if so could you explain how? We are experiencing the exact same problem using the Google Sign-In demo project (without having done any modifications to the code).

**Comment by ghousesgb** [comment]
Facing same here, got any solution?
