### ISSUE TITLE
SMS invitations not working > API 21

### ISSUE THREAD

**Issue by gordon7up** [googlesamples/google-services#264]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.

### Step 2: Describe your environment

  * Device: Samsung S7_____
  * OS version: __6.0___
  * SDK version: __23___
  * [Android] Google Play Services version: _8.4.0____
  
### Step 3: Describe the problem:
Email invitations work fine however links within SMS invites bring user to app store (even if app installed) deep links appear to be lost (AppInviteReferral.hasReferral() returns false).

This seems to be only on SMS invites as email links work with no problems. 

Also, SMS links on pre version21 seem to work (permissions issue?)

#### Steps to reproduce:

  1. ____Send SMS invite_
  2. ____Receiver clicks link_
  3. __Link brings user to play store___
  
#### Observed Results:

  * What happened?  This could be a description, log output, etc.
App does not detect any referral.
following message is common in logical:
XMLHttpRequest cannot load https://play.google.com/log?format=json. The 'Access-Control-Allow-Origin' header has a value 'http://play.google.com' that is not equal to the supplied origin...
  
#### Expected Results:
SMS invite deep link detected
  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by samtstern** [comment]
@gordon7up thanks for this report.  Could you provide an example of an SMS link and an email link?  You can just send an invitation of each type to yourself and copy the link here.  That would make this easier to investigate.

**Comment by gordon7up** [comment]
@samtstern looks like this is an issue with Samsungs messaging app, the app opens its own internal browser passing the link, this browser somehow seems to then lose the deep link and goes directly to the app store.
I changed the default SMS app from Samsungs messages to Hangouts and presto app-invites working fine.
I then tested app invites on Nexus device and SMS invite worked fine.

It looks like its an issue across Samsungs SMS app on Android 5 & 6.

Ive added a screen cap of SMS browser opening app-invites link, this the seems to open play store but without the deep link?

Let me know if you need anymore detail.
Thanks.
![device-2016-09-26-195920](https://cloud.githubusercontent.com/assets/13190370/18847874/cc3ba450-8423-11e6-98b4-85b836614f94.png)

**Comment by samtstern** [comment]
@gordon7up thanks for digging into that!  This is similar to what we have seen with Facebook messenger, which also has an internal browser and therefore drops some of the deep link data.

I will close this issue for now since we're already tracking it for Facebook, but I will make sure to add your info to our bug tracker because Samsung messenger is a big target to know about.
