### ISSUE TITLE
Get email user from FirebaseUser (Android)

### ISSUE THREAD

**Issue by phukhanhlee** [googlesamples/google-services#266]
I wan't to get email from FirebaseUser after login with GoogleSignInOptions
```java
void setupFireBase(){
        GoogleSignInOptions gso = new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                .requestIdToken(getString(R.string.default_web_client_id))
                .requestEmail()
                .build();
        mGoogleApiClient = new GoogleApiClient.Builder(this)
                .enableAutoManage(this, this)
                .addApi(Auth.GOOGLE_SIGN_IN_API, gso)
                .build();
   ......
    }
```

After login successfully and get current firebase user. I can get user Display name but i can't get email of user.

I had followed document : https://firebase.google.com/docs/auth/android/google-signin but i can't get right email from firebase account mAuth.getCurrentUser().getEmail() but it return null.

I had create 

I used firebase 9.4.0 and 9.6.0.

**Comment by samtstern** [comment]
@phukhanhlee a few things:

1. This should be filed on the repo [firebase/quickstart-android](/firebase/quickstart-android) so I am going to close it here.
2. When you go to the [Auth > Sign-In Methods](https://console.firebase.google.com/project/_/authentication/providers) page of your project in the Firebase console. do you have **One account per email address** on or off?  If you allow multiple accounts per email address, you will get `null` for `FirebaseUser.getEmail()`.

**Comment by Adityavns** [comment]
How do i get the email if i have One account per email address on ?

**Comment by pradhulstha** [comment]
There is no other option for you to get the Email from the user. What I did is, request for the user's email address in your next activity and saved it in the Firebase to retrieve it later.

**Comment by Adityavns** [comment]
Thanks for the advice, 
This will not work if we enable allow multiple accounts per email address in firebase console.

**Comment by pradhulstha** [comment]
Yes That's true. You can enable one user per Email Address or use ERROR_CREDENTIAL_ALREADY_IN_USE exception while signing the user.

2nd Option: Save the email address along with user information in Firebase and retrieve later.

**Comment by Adityavns** [comment]
If i use one user per Email Address, i have to insist the user to use the same login method he/she used earlier which i don't to do.
If i want to save email address , i will have to ask the user to enter it manually . Which clearly is not a good idea after he/she used their social account which clearly have an email attached.

**Comment by pradhulstha** [comment]
But, if you use the first Solution I gave you. Which will give you the Email Address related to the user that is currently signed in.
