### ISSUE TITLE
Swift 3: ViewController does not conform to protocol GIDSignInDelegate

### ISSUE THREAD

**Issue by bennettl** [googlesamples/google-services#267]
### Describe your environment

Swift 3.0
Xcode 8
GoogleSignIn 4.0.0
### Describe the problem:

Xcode keeps telling me my view controller does not conform to protocol, when I literally copy and paste the required function into my view controller. It's saying that I'm missing the method that I clearly have in my view controller (double checked method name, parameter types, etc.)
#### Steps to reproduce:
1. Upgraded to Swift 3.0, Xcode 8
2. Make View controller conform to protocol GIDSignInDelegate
3. Place the method in view controller:

`public func sign(_ signIn: GIDSignIn!, didSignInFor user: GIDGoogleUser!, withError error: Error!) {}`

or 
`func sign(_ signIn: GIDSignIn!, didSignInFor user: GIDGoogleUser!, withError error: Error!) {}`
#### Observed Results:

![screen shot 2016-10-03 at 11 42 21 pm](https://cloud.githubusercontent.com/assets/1672224/19064703/cb6e73cc-89c3-11e6-9675-9d2015453d6e.png)
#### Expected Results:

My app to build successfully because I followed the protocol.

**Comment by ianbarber** [comment]
That's an odd one! Looks like the type of Error is getting inferred wrong - I see UIViewController.Error which is odd, as it should be an NSError.

You might be able to force it - try declaring the protocol as Swift.Error (or maybe GoogleSignIn.Error).

**Comment by happiehappie** [comment]
But will there ever be an updated example for swift 3?

**Comment by jaswinderwadali** [comment]
Add two method for swift 3.0 

```
   func sign(_ signIn: GIDSignIn!, didSignInFor user: GIDGoogleUser!, withError error: Error!) {
      
    }
    func sign(_ signIn: GIDSignIn!, didDisconnectWith user: GIDGoogleUser!, withError error: Error!) {
        
    }

```

**Comment by mahesh-brainvire** [comment]
I am getting same error

**Comment by happiehappie** [comment]
Guess this issue is dead XD

**Comment by maneesh888** [comment]
I am not expecting such silly issues from apple/google in 21st century, someone please help me on this issue. Thanks

**Comment by evelynklassen** [comment]
I'm getting the same error. Has anyone managed to solve it?

**Comment by happiehappie** [comment]
Try check the documentation again. It seems to be updated.

**Comment by evelynklassen** [comment]
I checked the documentation, but I'm still facing the same error.

The documentation says to use:
`func signIn(signIn: GIDSignIn!, didSignInForUser user: GIDGoogleUser!,
  withError error: NSError!)`
But the protocol is:
`public func sign(_ signIn: GIDSignIn!, didSignInFor user: GIDGoogleUser!, withError error: Error!)`.

My environment:
Xcode 8.2.1
Swift 3.0.2
GoogleSignIn 4.0.1

**Comment by edurd** [comment]
@evelynklasse You just saved my day with that UPDATE, thanks!

**Comment by samtstern** [comment]
Looks like @evelynklassen solved this a while ago and we forgot to close it.

**Comment by dmobisoft** [comment]
I found the error. I had a model with the name "Error", it was probably conflicting with GoogleSignIn. I had remove Error class and it's working.
