### ISSUE TITLE
Reopen #261: Nil login on iOS 10

### ISSUE THREAD

**Issue by amaralpb** [googlesamples/google-services#268]
Hello, I'd like to reopen #261 because I and at least one other person are experiencing the same issue. I have pasted the body of the issue below for reference:

"Device: iPhoneSE Simulator
OS version: 10 GM
SDK version: 10 GM
Not tested on other SDKs
Description:

When trying to log, nothing is happening but signIn delegate method is triggered.

Steps to reproduce:

Download project and configure it
Build and run
Add breakpoint to delegate signIn method
Tap on signIn
No Safari window is displayed
delegate signIn method is triggered with nil user and error code to -4
Did someone has this problem ? I tried to had clientID in AppDelegate but still the same issue."

Thanks,
--Peter

**Comment by ianbarber** [comment]
Interesting. There have been some keychain issues on the simulator recently - does the same thing happen on a real device or is it confined to the simulator?

**Comment by amaralpb** [comment]
Hi @ianbarber, we've only attempted on the simulator so far. Was there a method documented somewhere to resolve the keychain issue on the simulator?

**Comment by ianbarber** [comment]
Try adding an entitlement (any will do - I have been turning on shared keychain, but apparently any resolve it)

**Comment by amaralpb** [comment]
Thanks @ianbarber , enabling shared keychain worked for us on both the simulator and our real test device!
