### ISSUE TITLE
android sign-in develop_error

### ISSUE THREAD

**Issue by mavisli** [googlesamples/google-services#273]
Device : Android - SamSung -  5.0.2

The problem is that I couldn't use integrated Google Sign-In for Android. 
I'm sure my code was as the same as the guide. 
And server_client_id (WebApplication) was set.

But when i try to sign in, GoogleSignInResult always got error :  resut=DEVELOP_ERROR, revolution=null.

I tried many solutions from stackoverflow, but none works!
I was crazy! Could u help me with this issue?

**Comment by crazycodepeng** [comment]
I am sorry. I can not help you。
But you can go here to ask questions

http://stackoverflow.com/questions/ask/advice?

我还没遇到过这个问题。不过你可以去这个网站去提问，哪里会有很多人帮你解答。

**Comment by mavisli** [comment]
@crazycodepeng 
啊，十分感谢。我打包以后就解决了，应该还是sha1不匹配的问题。 💗
