### ISSUE TITLE
[CR Android] Set path to json file from gradle and/or from in app

### ISSUE THREAD

**Issue by originx** [googlesamples/google-services#277]
* Device: xx
  * OS version: xx
  * SDK version: 9.8.0
  * [Android] Google Play Services version: 9.8.0
  
### Step 3: Describe the problem:

We have multiple flavor dimensions which should point to separate Firebase projects & environments.
Sadly the way json files are set via flavors/dimensions really clutters our file structure. It would be really helpful for us if we could set the environments from the gradle build process and/ or even better from the code.

Use case:
Debug   com.app.firebase.debug <-- Firebase Test project
Beta       com.app.firebase  <-- Firebase Test project
Prod       com.app.firebase  <-- Firebase prod project

Of course imagine you have 3-4 countries and the complexity of json files maintenance gets even bigger.
Also this would resolve the breakage of builds where flavors do not use FCM but fail due to missing json file.

Thanks

**Comment by samtstern** [comment]
@originx it wouldn't be possible to set from code since all of the configuration from the json file happens even before the project Java code is compiled (happens during gradle configuration).

I am going to close this issue since it does not have to do with this quickstart repo, but I will forward your feedback to the team.

Also could you describe how having "3-4 countries" would complicate things?  Are you using one Firebase project for each country?

**Comment by originx** [comment]
Thank you for the response,
This is oversimplified example of multiple dimensions that we have issues with:
 ```
flavorDimensions 'payed', 'country', 'api'
bleeding {
    dimension 'api'
    minSdkVersion 21
}
compat {
    dimension 'api'
    minSdkVersion 16
}
payed {
    dimension 'payed'
}
free {
    dimension 'payed'
}
germany {
    dimension 'country'
}
 italy {
    dimension 'country'
    ....
}
 mexico {
    dimension 'country'
    ....
}
 unitedStates {
    dimension 'country'
    ....
}
```

You would end up with flavors:
```
debug
release
main
germany
mexico
...
freeItalyCompat
freeItalyBleeding
freeGermany
freeGermanyCompat
freeGermanyBleeding
freeMexico...
payedGermanyCompat
payedGermanyBleeding
....
```

We have 2 Firebase projects, reason for this is to avoid accidentally pushing a "hello world notification" from DEV, QA or anyone to millions of users on Production
**TEST firebase project**
  -debug builds **com.package.app.debug**
  -release builds /for QA, Beta testers **com.package.app**
**PROD firebase project**
  -live production **com.package.app**

This means beta and prod package names overlap, have same package name and the only thing they differ in is environment endpoints and configs.

Problems we have:
-we need to put a json config file in empty flavor folders so we can compile properly(**even for flavors that SHOULD not include/use Firebase**), you need a dummy JSON file
-we would need an extra dimension for production, internal test so we can put json files in those extra folders, the complexity of the project structure complexity would be **increased immensely**

**What would be good to have**:
Ability to configure file locations via gradle build configs, for example in flavor definitions:

```
// override this with -PisProduction=true to create publishable release builds
ext.isProduction = project.hasProperty("isProduction") ? ext.isProduction.toBoolean() : false

germany {
    if(isProduction){
     //noFirebase=true  used if flavor should not have firebase at all
       firebaseJsonFile = "../firebaseGermanyProd"
      }else{
           firebaseJsonFile = "../firebaseGermany"
      }
}
```

This would remove the overhead of unneeded files immensely and also you could disable firebase for flavors that are not needed

Since we have an enterprise project this would really help us control it more and keep it cleaner.

I will open a feature request on the following site with this content, just wanted to put it here for reference also:
https://firebase.google.com/support/contact/bugs-features/

**Comment by samtstern** [comment]
If you only have two JSON files, what happens if you just put them in `app/src/free` and `app/src/payed` and then don't put them in all those other folders?  I believe that should work, and then for example `freeGermany` would use the one in `free` and `payedGermany` would use the one in `payed`.

**Comment by originx** [comment]
Please see comment, it does not work: https://github.com/googlesamples/google-services/issues/54#issuecomment-204587543

for that issue, but in the end suggestion to place it so its:

germany {
    if(isProduction){
     //noFirebase=true  used if flavor should not have firebase at all
       firebaseJsonFile = "../firebaseGermanyProd"
      }else{
           firebaseJsonFile = "../firebaseGermany"
      }
}

would resolve everyones issues I believe and it is cleaner since more control is on the dev side

**Comment by mgj** [comment]
@samtstern this does not work, you get  an error about not being able to find google-services.json

**Comment by mgj** [comment]
This works:

```
def getCurrentFlavor() {
    Gradle gradle = getGradle()
    String  tskReqStr = gradle.getStartParameter().getTaskRequests().toString()

    Pattern pattern;

    if( tskReqStr.contains( "assemble" ) )
        pattern = Pattern.compile("assemble(\\w+)(Release|Debug)")
    else
        pattern = Pattern.compile("generate(\\w+)(Release|Debug)")

    Matcher matcher = pattern.matcher( tskReqStr )

    if( matcher.find() )
        return matcher.group(1).toLowerCase()
    else
    {
        println "NO MATCH FOUND"
        return "";
    }
}

productFlavors {
        beta {
            dimension 'releasetype'
            applicationIdSuffix 'beta'

            def currentFlavor = getCurrentFlavor()
            println "Flavor: " + currentFlavor

            if(currentFlavor.contains("beta")) {
                println "Using Beta google-service.json"
                copy {
                    from 'src/beta/'
                    include '*.json'
                    into '.'
                }
            }
        }
        prod {
            dimension 'releasetype'
            def currentFlavor = getCurrentFlavor()
            println "Flavor: " + currentFlavor

            if(currentFlavor.contains("prod")) {
                println "Using Production google-service.json"
                copy {
                    from 'src/prod/'
                    include '*.json'
                    into '.'
                }
            }
        }
```
