### ISSUE TITLE
GIDGoogleUser serverAuthCode nil

### ISSUE THREAD

**Issue by Alexandeer** [googlesamples/google-services#279]
### My environment:
Xcode 8.1
Device: iPad 9.3.5 | iOS Simulator SE 10.1
Using GoogleSignIn (4.0.1), GTMOAuth2 (1.1.4), Google (3.0.3)
  
### My problem:

I used this guide to configure my system:
https://developers.google.com/identity/sign-in/ios/sign-in

I'm trying to configure the application using the guide:
https://developers.google.com/identity/sign-in/ios/offline-access

I am not getting the code that was to come to me in user.serverAuthCode parameter.
 From doc: 
> 
> After the user is signed in, retrieve the one-time authorization code:
> ```
> - (void)signIn:(GIDSignIn *)signIn didSignInForUser:(GIDGoogleUser *)user
>     withError:(NSError *)error {
>   // Perform any operations on signed in user here.
>   // user.serverAuthCode now has a server authorization code!
> }
> ```

And

> one-time authorization

I tested it for different users (by new and returning). The "code" did not come to me.

#### Reproduce:

Just follow the official guide mentioned above.
  
#### Observed Results:

 user.serverAuthCode == nil
  
#### Expected Results:

I'll get the key ))

#### P.S. 
Everything else works fine. No errors and no warnings. I need exactly this property. And other authentication methods currently are not suitable for me.

**Comment by emarthinsen** [comment]
I'm having exactly the same problem. The code sample in the offline-access page doesn't mesh well with the code in the sign-in documentation. Still looking for a solution myself.

**Comment by emarthinsen** [comment]
I just got it working. The catch is that the server auth code will only be sent the first time the user logs in. The user must have just seen the confirmation screen. On all subsequent logins, no server auth code will be sent. I went to https://security.google.com/settings/security/permissions and removed the credentials for my app, then the login worked and I got a server auth code.

**Comment by Alexandeer** [comment]
I've tried it, but it does not work for me. 
As I wrote. I tried this with a specially created new user.

**Comment by Alexandeer** [comment]
I helped re-installation and manual configuration. Not sure what the problem was, but it was on my side.
