### ISSUE TITLE
Google App Invites, how to check invitation status from sender side.

### ISSUE THREAD

**Issue by vladimir-belous** [googlesamples/google-services#28]
How to check invitation from sender side. I've requirement to grant sender when invitation is succeed
 (user has installed app).
I see 
AppInvite.AppInviteApi.updateInvitationOnInstall(mGoogleApiClient, invitationId);
But no information how to get the status.

Thanks!

**Comment by samtstern** [comment]
@vladimir-belous currently there is no way to check on the status of an individual invitation.  I'll mark this as a feature request, thanks!

**Comment by vladimir-belous** [comment]
@samtstern could you give due date when it will be implemented?

**Comment by samtstern** [comment]
@vladimir-belous Sorry I can only give the feedback to the App Invites team, can't make any promises!

**Comment by mantic87ja** [comment]
If this (must have feature in my opinion) is not yet implemented, Is there a way to check if invitation receiver email address isn't fake? I also have task to grand sender when invitation is successful, and when I test this for fake email, I still get response as it is regular receiver, so users can use this situation in inappropriate way.
