### ISSUE TITLE
unexpected play-services-measurement added

### ISSUE THREAD

**Issue by chaudharisuresh997** [googlesamples/google-services#281]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.

### Step 2: Describe your environment

  * Device: ____dell _
  * OS version: _____windows7
  * SDK version: _____21
  * [Android] Google Play Services version: _____9.8.0
  
### Step 3: Describe the problem:
even though i am adding only google-play-services-ads it is automatically importing google-play-measurement also
#### Steps to reproduce:

  1. _____add   compile 'com.google.android.gms:play-services-ads:9.8.0' in module specific gradle
  2. _____try to sync it
  3. _____now you will get error Failed to resolve: google-play-services-measurement:9.8.0
    This is unexpected if i need only google-play-services-ads why it is adding google-play-services-measurement in it.
  
#### Observed Results:

  * What happened?  This could be a description, log output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:This is unexpected if i need only google-play-services-ads why it is adding google-play-services-measurement in it.

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by chaudharisuresh997** [comment]
Gradle is making life even measurable

**Comment by samtstern** [comment]
@chaudharisuresh997 can you paste your entire `build.gradle` file here?  I am suspicious of the error message as there has never been anything called `google-play-services-measurement`.  We did have `play-services-measurement` at one time.

**Comment by ianbarber** [comment]
Could be an old google-services plugin version - make sure you're referencing 3.0.0

**Comment by chaudharisuresh997** [comment]
how to verify google play services version

**Comment by samtstern** [comment]
I think @ianbarber is referring to the version of the `com.google.gms:google-services` plugin in your gradle file. Make sure you have `com.google.gms:google-services:3.0.0`

**Comment by samtstern** [comment]
@chaudharisuresh997 closing this issue since it's been a while since the last update.  Re-open if you think the solution above is not correct.
