### ISSUE TITLE
Unable to configure global_tracker.xml as it's a generated file

### ISSUE THREAD

**Issue by idish** [googlesamples/google-services#282]
The official tutorial for setting google analytics totally contradicts itself as I cannot add anything to the generated(!!) xml file.

Given that the `google-services.json` generates the `global_tracker.xml` file, I can't add my custom
properties to that file such as `ga_reportUncaughtExceptions` to `true`.

The simple solution will be to obviously to create my own tracker xml to modify custom attributes, 
But then:

1. I will have to copy again the ga-tracking-id from the google-services.json instead of it being generated
2. There will be no real need for the `google-services.json `file, right?

**Comment by samtstern** [comment]
The workaround you've suggested is correct.  If you want to use custom properties it's better just to put the tracking ID in yourself and ignore the `google-services.json` file.

The purpose of the `json` file is to make setup simple for beginning users, as we used to get many many reports of people not sure where to put their tracking ID.  For an advanced user like yourself, this solution can sometimes get in your way.

**Comment by samtstern** [comment]
Closing issue for lack of recent Activity, thanks for raising it!
