### ISSUE TITLE
I don't see file google-services in project

### ISSUE THREAD

**Issue by akashjpro** [googlesamples/google-services#285]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.

### Step 2: Describe your environment

  * Device: _____
  * OS version: _____
  * SDK version: _____
  * [Android] Google Play Services version: _____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, log output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by samtstern** [comment]
@akashjpro I am going to close this as there's no information provided (your first comment is just the template left blank).

If you can describe the problem a bit better please re-open and I'll be happy to help.
