### ISSUE TITLE
Unable to get GCM token

### ISSUE THREAD

**Issue by happiehappie** [googlesamples/google-services#286]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.

### Step 2: Describe your environment

  * Device: iPhone 6S Plus iOS 10.2
  * SDK version: Latest with pod update
  
### Step 3: Describe the problem:

I tried following exactly in the sample but I get this in my log.

2016-12-30 03:11:08.585: GCM | GCM library version 1.1.4
2016-12-30 03:11:08.669: GCM | GCM registration is not ready with auth credentials
Could not connect to GCM: The operation couldn’t be completed. (com.google.gcm error 501.)
af442b82bffdf3bc1c1a30189be3edd77c9fe73e0b486b1fad58bdb535a1ea85
2016-12-30 03:11:25.255376 WeddingLah[6326:1609423] XPC connection interrupted
Registration to GCM failed with error: Optional("The operation couldn’t be completed. (com.google.iid error 0.)")
af442b82bffdf3bc1c1a30189be3edd77c9fe73e0b486b1fad58bdb535a1ea85
Registration to GCM failed with error: Optional("The operation couldn’t be completed. (com.google.iid error 0.)")

Things that I tried
Sanbox = true
regenerate cert and upload them
specify dev team and profile
Does anyone still has any suggestion apart from the 2 closed issue?

**Comment by samtstern** [comment]
Closing this issue due to age (it's been a while since the last update).  If you still want to discuss, feel free to re-open.
