### ISSUE TITLE
Are iOS app extensions actually supported by Sigin lib?

### ISSUE THREAD

**Issue by tererecool** [googlesamples/google-services#291]
We were intensively trying to make the code, that already works in the app itself, work in our app extension (document provider) without any luck. With the dropbox SDK it was not a problem, do you actually support app extensions in the Sigin lib, so that when the user sign in in the app it should stay signed in also in the app extension? I could not find any example/documentation specific for app extensions.

**Comment by witZack** [comment]
Same. Trying so hard to get this going and can't

**Comment by samtstern** [comment]
Hi all.  Apologies for the lack of response!  Since this issue is so old I am going to close it.  It looks like someone has found a workaround that's relevant though;
https://stackoverflow.com/questions/39139160/retrieve-google-user-from-ios-extension/39295203#39295203
