### ISSUE TITLE
Can't distinguish between sign-in failures due to network problems or user cancellations

### ISSUE THREAD

**Issue by tpesce** [googlesamples/google-services#293]
I'm seeing this issue in an app I am developing, and I have been able to reproduce it in the SignInActivity sample.

Device 1:

Alcatel OneTouch Pixi 7
Android 5.0.2
SDK 25
com.google.gms:google-services:3.0.0

Device 2:

Android Emulator
Android 5.0.2
SDK 25
com.google.gms:google-services:3.0.0

When the device is online, everything works as expected. However, when the device is effectively offline, the status of the GoogleSignInResult from sign-in operations is 12501 (SIGN_IN_CANCELLED).

Steps to reproduce:

1. Put the device in airplane mode
2. Set a breakpoint in SignInActivity.handleSignInResult() in the else clause (around line 126)
3. Debug the app from Android Studio
4. Select the "SignInActivity" option, then tap the Sign In button

The breakpoint is triggered twice: once as a result of the silent sign-in, and once as a result of the interactive sign-in. The first time the status code is set as expected (SIGN_IN_REQUIRED), but the second time the status code is SIGN_IN_CANCELLED.

Because of this, failures due to network connectivity issues are masked as user cancellations and are difficult to handle appropriately.

**Comment by samtstern** [comment]
@tpesce thanks for that feedback, that's a good point.  Since this issue tracker is for sample bugs and not bugs/feature requests in the underlying SDKs I am going to forward this feedback to the team and then close the issue.

In the meantime, I can only suggest the unsatisfying solution of checking for network access before launching the sign in flow.

**Comment by tpesce** [comment]
@samtstern Thanks, and understood. Is there somewhere I can report the issue for the underlying SDK? I looked, and I couldn't find anything other than StackOverflow.

**Comment by samtstern** [comment]
No there is no official issue tracker for Play services, so you did the
right thing by reporting it here with a detailed explanation.
