### ISSUE TITLE
Problem that the refresh token is not returned in backend

### ISSUE THREAD

**Issue by JSpiner** [googlesamples/google-services#295]
Hi there

We are creating an integrated calendar-based recommand service. I received a serverAuthCode, idToken in my Android application and sent it to my server. I changed the serverauthcode to accesstoken to keep the calendar synchronized on the server. Through this process, synchronization was successfully performed. But after the accesstoken expired, I could not get a refreshtoken to refresh accesstoken. Like below

```
{
  "access_token": "<accesstoken>",
  "token_type": "Bearer",
  "expires_in": 3600,
  "id_token": "<idtoken>"
} // <- refresh token is missing!!
```
According to [this document](https://developers.google.com/identity/protocols/OAuth2WebServer), I need to send `access_type=offline` to receive the refreshtoken when create a serverauthcode(in application). In this situation, I'm using com.google.android.gms.common.api.GoogleApiClient library(following [Firebase Example](https://firebase.google.com/docs/auth/android/google-signin?hl=ko) ). However, there is no method to set `access_type`.

So, I can't receive refreshtoken using googleserviceapi. But, we had a lot of different try. We found a way, we always have.

Among many scopes, 'PLUS_ME' and 'PLUS_LOGIN' scopes require offline permission. (found in [here](http://stackoverflow.com/questions/33544240/how-to-remove-the-have-offline-access-permission-on-android-using-oauth) )

I added these scopes, and now refreshtoken appeared.
https://github.com/CalyFactory/caly-android/commit/a1bf0adcda0dc15444ef305ed3b9d51b1195b4d6

In conclusion, googleapiclient needs to add a method to change the access_type. Otherwise, I have to add an useless scope unconditionally. Below is my development environment. I wish you to fix this problem as soon as possible.

project gradle
```gradle
...
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'

        classpath 'com.google.gms:google-services:3.0.0'
    }
...
```

app gradle
```gradle
...
android {    
    compileSdkVersion 23
    buildToolsVersion "23.0.2"
    defaultConfig {
        applicationId "io.caly.calyandroid"
        minSdkVersion 15
        targetSdkVersion 23
...
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:design:23.2.1'

    //external libs
    compile 'com.google.android.gms:play-services-auth:10.0.1'
    compile 'com.google.firebase:firebase-messaging:10.0.1'
...
}

apply plugin: 'com.google.gms.google-services'
```

Android - LoginActivity
```java
    private void init(){
        GoogleSignInOptions gso =
                new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                        .requestServerAuthCode(getString(R.string.google_client_id))
                        .requestIdToken(getString(R.string.google_client_id))
                        .requestScopes(
                                new Scope("https://www.googleapis.com/auth/calendar"),
                                new Scope("https://www.googleapis.com/auth/userinfo.email"),
                                new Scope("https://www.googleapis.com/auth/calendar.readonly"),
                                new Scope(Scopes.PLUS_ME),
                                new Scope(Scopes.PLUS_LOGIN)
                        ).build();

        mGoogleApiClient = new GoogleApiClient.Builder(this)
                .enableAutoManage(this , onGoogleConnectionFailedListener)
                .addApi(Auth.GOOGLE_SIGN_IN_API, gso)
                .build();

    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        if (requestCode == codeSignIn) {
            GoogleSignInResult result = Auth.GoogleSignInApi.getSignInResultFromIntent(data);

            Log.d(TAG, "handleSignInResult:" + result.isSuccess());
            Log.d(TAG, "handleSignInResult:" + result.getStatus().getStatus());


            if (result.isSuccess()) {
                GoogleSignInAccount acct = result.getSignInAccount();
                Log.d(TAG, acct.getDisplayName());
                Log.d(TAG, "id token : " + acct.getIdToken());
                Log.i(TAG, "serverauthcode : " + acct.getServerAuthCode());
                Log.i(TAG, "id : " + acct.getId());
                Log.d(TAG, "email : " + acct.getEmail());

                procLoginGoogle(acct.getServerAuthCode());

            } else {
                Toast.makeText(
                        getBaseContext(),
                        getString(R.string.toast_msg_login_fail),
                        Toast.LENGTH_LONG
                ).show();
            }
        }
    }
```

before add scope

```
{
  "access_token": "<accesstoken>",
  "token_type": "Bearer",
  "expires_in": 3600,
  "id_token": "<idtoken>"
} // <- refresh token is missing!!
```

after add scope

```
{
  "access_token": "<accesstoken>",
  "token_type": "Bearer",
  "expires_in": 3600,
  "id_token": "<idtoken>",
  "refresh_token": "<refreshtoken>"
} // <- refresh token is showing!!
```

**Comment by Marutian** [comment]
Do not merge this commit. This code include virus code.

**Comment by SlZeroth** [comment]
I have same problem....
+1

**Comment by samtstern** [comment]
When you call `requestServerAuthCode(String)` you could instead call `requestServerAuthCode(String, true)` which forces the request to included a `refresh_token` when it succeeds:

https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInOptions.Builder.html#requestServerAuthCode(java.lang.String, boolean)

Note that you should not to this every time, but only when you have lost the original refresh token.

**Comment by mspanesar145** [comment]
> When you call `requestServerAuthCode(String)` you could instead call `requestServerAuthCode(String, true)` which forces the request to included a `refresh_token` when it succeeds:
> 
> https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInOptions.Builder.html#requestServerAuthCode(java.lang.String, boolean)
> 
> Note that you should not to this every time, but only when you have lost the original refresh token.

Woww. You are a life saver @samtstern . I was string to achieve this from 1 week.

**Comment by Dhaval2404** [comment]
> When you call `requestServerAuthCode(String)` you could instead call `requestServerAuthCode(String, true)` which forces the request to included a `refresh_token` when it succeeds:
> 
> https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInOptions.Builder.html#requestServerAuthCode(java.lang.String, boolean)
> 
> Note that you should not to this every time, but only when you have lost the original refresh token.

Thanks a lot @samtstern. You saved my day. Working on this from last 2 weeks.
