### ISSUE TITLE
Google sign in iOS require password

### ISSUE THREAD

**Issue by JustACodeMonkey** [googlesamples/google-services#296]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.

### Step 2: Describe your environment

  * Device: _iPad_
  * OS version: _9+_
  * SDK version: _4.0.1_
  * [Android] Google Play Services version: _____
  
### Step 3: Describe the problem:

Our school has approximately 38,000 iPad devices, shared between staff (~17,000) and students (~165,000). We have two apps that leverage our Google Apps for education accounts and must, therefore, use Google Sign in. Up until a couple of weeks ago, I was able to use the gapi auth2 javascript sign in process in WKWebView, but that is no longer supported and the apps are now required to use the actual iOS sign in method. Is there a way to force the user to enter a password? The way is stands now, any user can access any other user's account that has logged in before them because the login information is stored in Safari and a password isn't required to re-login. I'm OK with other users being able to view the previous users, but allowing them to sign in as the other users is a massive security issue.

#### Steps to reproduce:

  1. Sign into the app on a shared device using Google Sign In
  2. Sign out of the app on a shared device (GIDSignIn.sharedInstance().signOut())
  3. Sign in again...and access any user's account who has accessed the app on the shared device without a password
  
#### Observed Results:

I can access any user's account on the device who has previously signed in.
  
#### Expected Results:

I shouldn't be able to access the account of any of the other users on the shared device.
  
#### Relevant Code:

    GIDSignIn.sharedInstance().signIn() 

and 

    GIDSignIn.sharedInstance().signOut()

**Comment by ToddKerpelman** [comment]
Unfortunately, you'll need to also have the user sign out of their Google account from within Safari to truly have them signed out from the device. 

You can help make this happen, though, by opening up an SFSafariViewController that directs the user to "https://accounts.google.com/Logout" -- Try doing right after you make the call to signOut() and that will make sure the user completes the sign-out process.

**Comment by nehloo** [comment]
1. Define "GIDSignIn":

    [GIDSignIn sharedInstance].uiDelegate = self;
    [[GIDSignIn sharedInstance] setScopes:@[@"https://www.googleapis.com/auth/youtube"]];
.................................

2. When the user wants to sign in and taps a button, first display the "logout" view, very briefly:

    SFSafariViewController *logoutViewController = [[SFSafariViewController alloc] initWithURL:[NSURL URLWithString:@"https://www.google.com/accounts/Logout"]];
    logoutViewController.delegate = self;
    logoutViewController.modalTransitionStyle = UIModalTransitionStyleCrossDissolve;
    logoutViewController.modalPresentationStyle = UIModalPresentationFormSheet;
    [self presentViewController:logoutViewController animated:YES completion:nil];
.................................

3. Dismiss the "logout" view after it loads:

- (void)safariViewController:(SFSafariViewController *)controller didCompleteInitialLoad:(BOOL)didLoadSuccessfully {
    [controller dismissViewControllerAnimated:NO completion:^{
        [[GIDSignIn sharedInstance] signIn];
    }];
}
.................................

4. Present the "GIDSignIn" view, and it should now ask the user for a password, for any of the accounts they're signed in with:

- (void)signIn:(GIDSignIn *)signIn presentViewController:(UIViewController *)viewController {
    viewController.modalTransitionStyle = UIModalTransitionStyleCrossDissolve;
    viewController.modalPresentationStyle = UIModalPresentationFormSheet;
    [self presentViewController:viewController animated:YES completion:nil];
}

**Comment by PDSBGreg** [comment]
Thanks for the solution.

**Comment by samtstern** [comment]
Due to the age of the issue as well as the commentary provided by @ToddKerpelman  and the workaround provided by @nehloo I am going to close this issue.   Thanks all!
