### ISSUE TITLE
GCM wrong sample code : Getting error 501

### ISSUE THREAD

**Issue by peterpaulis** [googlesamples/google-services#298]
The code for the GCM is wrong

see
http://stackoverflow.com/questions/33375229/ios-gcm-error-code-501/42511805#42511805

my answer
http://stackoverflow.com/a/42511805/533422

**Comment by samtstern** [comment]
@peterpaulis it's been a long time since this issue was posted, I apologize that we never responded.  I hope you got the help you need on StackOverflow!  Closing due to old age.
