### ISSUE TITLE
Android Studio 1.3 RC3. Google Play services out of date. Requires 7571000 but found 6774470

### ISSUE THREAD

**Issue by ksraja** [googlesamples/google-services#30]
I ran this sample with below AVD config and I have listed down SDK tools.
But I get an error saying "Google Play services out of date. Requires 7571000 but found 6774470."
I understand that it could be an issue with emulator not catching up the latest version. But how do I run this sample with an emulator.

![avd](https://cloud.githubusercontent.com/assets/1333000/8797005/b2aa1390-2f4d-11e5-82f7-4366254855d2.png)
![sdk tools](https://cloud.githubusercontent.com/assets/1333000/8797008/b7a53bfe-2f4d-11e5-861c-21817a0fdc0e.png)
![sdk platforms](https://cloud.githubusercontent.com/assets/1333000/8797009/b7b8b44a-2f4d-11e5-9bd7-349dd0fd81da.png)

**Comment by kroikie** [comment]
Try using an emulator running API 21 or 19. These API versions include the updated version of Google Play Services. The sample should run as expected on these API levels.

**Comment by kroikie** [comment]
Closing issue, no response.
