### ISSUE TITLE
welcomesee

### ISSUE THREAD

**Issue by ahmedbhai301** [googlesamples/google-services#300]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.

### Step 2: Describe your environment

  * Device: _____
  * OS version: _____
  * SDK version: _____
  * [Android] Google Play Services version: _____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, log output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by samtstern** [comment]
@ahmedbhai301 looks like this may have been opened by accident, closing!
