### ISSUE TITLE
Google Sign in fails with Play Services 10.2.XX on older devices

### ISSUE THREAD

**Issue by easycheese** [googlesamples/google-services#301]
* Device: Motorola Xoom 
  * OS version: 4.1.2
  * SDK version: 10.2.0
  * [Android] Google Play Services version: 10.2.91 & 10.2.98
  
Also reproducible on & Samsung Galaxy Tab 10.1 (4.0.4)

A recent update to Google Play Services is causing older devices to fail signing in to Firebase using Google signin credentials.  

Sign in worked perfectly on the older devices until recently with no changes to the app which leads me to believe that Google Play Services is the cause.  Issue started ~3-4 weeks ago and is still present (I'm not sure which version the issue appeared).  This is reproducible on the sign in demo app

Google Play Services Version: 10.2.98 (032-146496160)
Android version 4.1.2 (Build JZO54K)

I went back and installed some old Google Play Services APKs (Courtesy of APK Mirror).  Here is what I found:

10.2.91 (032-144333517): Fails
10.0.84 (032-137749526): Works

#### Steps to reproduce:

  1. Follow steps here: https://developers.google.com/identity/sign-in/android/start
  2.  Disable androidTestCompile 'com.android.support.test.uiautomator:uiautomator-v18:2.1.2'
  3.  Lower minSDK to 16
  4.  Install, run, try to sign in
  5.  Observe failure to sign in

Install Google play services 10.0.84 and attempt the same, sign in succeeds.

**Comment by samtstern** [comment]
@easycheese can you provide some logs from the failure case?  Need to know exactly what the error is.

**Comment by easycheese** [comment]
@samtstern 

There were no errors reported in the logs, all I could see was the following:

03-07 19:39:48.200 4181-4217/com.google.samples.quickstart.signin V/FA: Processing queued up service tasks: 1
03-07 19:39:53.290 4181-4217/com.google.samples.quickstart.signin V/FA: Inactivity, disconnecting from the service
03-07 19:40:06.400 4181-4227/com.google.samples.quickstart.signin W/InstanceID/Rpc: No response
03-07 19:40:06.410 4181-4227/com.google.samples.quickstart.signin D/FirebaseInstanceId: background sync failed: TIMEOUT, retry in 10

and then:

03-07 19:41:23.160 4181-5655/com.google.samples.quickstart.signin W/InstanceID/Rpc: No response
03-07 19:41:23.160 4181-5655/com.google.samples.quickstart.signin D/FirebaseInstanceId: background sync failed: TIMEOUT, retry in 20s


At one point in the past, I saw:

3-03 19:41:05.380 24057-24090/? I/Auth: [GoogleAuthUtil] GoogleAuthUtil
03-03 19:41:05.380 20280-20280/? D/Zygote: Process 24092 terminated by signal (4)
03-03 19:41:05.450 20412-20431/? D/dalvikvm: GC_FOR_ALLOC freed 1546K, 18% free 12400K/15111K, paused 84ms, total 84ms
03-03 19:41:05.460 20412-20618/? I/ActivityManager: Process com.google.process.gapps (pid 24092) has died.
03-03 19:41:05.460 20412-20618/? W/ActivityManager: Scheduling restart of crashed service com.google.android.gms/.auth.account.be.legacy.GoogleAccountDataService in 5000ms
03-03 19:41:05.470 20412-20618/? W/ActivityManager: Scheduling restart of crashed service com.google.android.gms/.auth.GetToken in 120091ms

Bug report attached.


[bugreport.txt](https://github.com/googlesamples/google-services/files/826364/bugreport.txt)

**Comment by samtstern** [comment]
@easycheese thank you for the bug report, that will be very helpful.  I have sent that over to the Google Sign In team and they will take a look.

Since I don't believe this is a widespread issue (yours is the only report) and there's nothing I can do in this sample repository to fix it, I am going to close this issue.  However I will make sure to come back and comment if I get any update or figure out what's going on, and please feel free to leave more comments if you find more information.
