### ISSUE TITLE
Cannot assign value of type 'AppDelegate' to type 'GIDSignInDelegate!'

### ISSUE THREAD

**Issue by RamandeepGosal** [googlesamples/google-services#304]
### Cannot assign value of type 'AppDelegate' to type 'GIDSignInDelegate!'

  * I have added both -
       #import <Google/SignIn.h>
       #import <Google/Analytics.h>
    in the Bridging header file.
  * I have installed the google SDK from cocoapods '/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods.rb'
  * This is the AppDelegate declaration - 
class AppDelegate: UIResponder, UIApplicationDelegate, GIDSignInUIDelegate {

### Step 2: Describe your environment

  * xcode 8
  * iOS 10
  
#### Observed Results:

  * Compiler Error - Cannot assign value of type 'AppDelegate' to type 'GIDSignInDelegate!'
  
#### Relevant Code:

  ```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
    // Override point for customization after application launch.
    self.initialize()
    IQKeyboardManager.sharedManager().enable = true
    TimeSyncManager.sharedInstance.syncTimeWithServer(withNotifcationOption: false)
    AppScreenManager.sharedInstance.setUpInitialScreen()
    SDKApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)
    //setUpGoogleSDK()
    
    var configureError: NSError?
    GGLContext.sharedInstance().configureWithError(&configureError)
    assert(configureError == nil, "Error configuring Google services: \(configureError)")
    
    GIDSignIn.sharedInstance().delegate = self      //<<--------Error at this Point
    
    application.registerForRemoteNotifications()
    UNUserNotificationCenter.current().requestAuthorization(options: [.alert, .sound, .badge]) {
      (granted, error) in
      //Parse errors and track state
    }
    return true
  }
  ```

**Comment by ianbarber** [comment]
You need to declare the protocol GIDSignInDelegate on your class, its separate from GIDSignInUIDelegate.
