### ISSUE TITLE
Using google-services.json in other module

### ISSUE THREAD

**Issue by SoNep** [googlesamples/google-services#306]
I wand to move google-services to separate module how I can do that?
google-services.json has package name of main module.

**Comment by samtstern** [comment]
@SoNep can you explain your use case a little?  It generally shouldn't matter which module the plugin is in, and you should always use the package name of your **app** module even if you're using the Google/Firebase code from a library module.

**Comment by SoNep** [comment]
Hi  in my app I have few modules.
and I want to use google-services in separate module(library) not in main app module.
But google-services.json should specify package,  and google-services module will have another package name.
for example nz.co.example.app; for main module and nz.co.example.modules.googleservices; for google-services module.
An I cant use generated google-services.json in other modules.
Do you have any solution for that?

**Comment by samtstern** [comment]
When you say "I want to use google-services in separate module(library) not in main app module." what do you mean exactly?  What google-services SDKs are you trying to use?

**Comment by SoNep** [comment]
For example I want to create module which don't know anything about other app and working only with messangers and notifications.

**Comment by samtstern** [comment]
@SoNep since it's been a long time since the last update, I am going to close this issue.

I'd suggest reading this doc:
https://developers.google.com/android/guides/google-services-plugin

It will tell you how the `google-services` gradle plugin works and may help you figure out how to emulate its behavior in a library module.
