### ISSUE TITLE
[GoogleAccountDataServiceImpl] getToken() -> BAD_AUTHENTICATION

### ISSUE THREAD

**Issue by joonhocho** [googlesamples/google-services#313]
Reopening this issue, https://github.com/googlesamples/google-services/issues/253, as I am experiencing the same error.

**Comment by samtstern** [comment]
@joonhocho I will re-open #253

**Comment by cviacmob** [comment]
Am Facing same issue

**Comment by jshiwam** [comment]
Any solutions yet, please update

**Comment by thiagoicarros** [comment]
Same issue here
