### ISSUE TITLE
Error after integrating GoogleSignIn in app through Pod.  Error:- Apple Mach-O Linker (ld) Error Group, clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by parasmesanjay** [googlesamples/google-services#316]
* Device: ____5S_
  * OS version: _____10.2
  * SDK version: _____latest
  * [Android] Google Play Services version: _____
  
### Step 3: Describe the problem:
Apple Mach-O Linker (ld) Error Group,
clang: error: linker command failed with exit code 1 (use -v to see invocation)

these error comes after install the pod of GoogleSignIn and FireBase.

#### Expected Results:

  * What did you expect to happen?
expect! run app with google signin.

**Comment by parasmesanjay** [comment]
please help me.
facing htis problem from last three days. didn't find any solution.

**Comment by ianbarber** [comment]
Can you post your pod file? If you're using pod GoogleSignIn, try pod "Google/SignIn" (e.g. sign in subspec of Google pod).

**Comment by samtstern** [comment]
Closing this old issue due to a lack of responses, I hope you figured it out!

**Comment by gilshaan** [comment]
please help me too.
facing htis problem from last three days. didn't find any solution
