### ISSUE TITLE
Issue with device registration.

### ISSUE THREAD

**Issue by fafzal** [googlesamples/google-services#32]
Hi,

I am having an issue while registering a device on GCM. I follow the steps from [GCM](https://developers.google.com/cloud-messaging/android/start) but the device keep displaying a busy icon with a message (Generating InstanceID toke ) and never register it. 

![screen shot 2015-07-23 at 18 16 12](https://cloud.githubusercontent.com/assets/7127832/8855715/fcf2feec-3166-11e5-9b45-e78914a2b01b.png)

**Comment by kroikie** [comment]
Hi @fafzal it looks like you are using a simulator if you are what version of android is running on it? Should be 4.2.2 or higher to include Google Play Services.

**Comment by fafzal** [comment]
Hi kroikie,

Thanks for the reply, yes I am using a simulator. I don't see any error message on logcat console, I am using Android 5.1 (lollipop).

**Comment by kroikie** [comment]
Can the simulator access the internet otherwise?

**Comment by fafzal** [comment]
Yes it's do access the internet. I only see this error message on logcat console.

07-23 22:05:11.601    2041-2041/gcm.play.android.samples.com.gcmquickstart E/SettingsRedirect﹕ Can't redirect to app settings for Google Play services

**Comment by kroikie** [comment]
HI @fafzal, there is an issue with the latest version of Google Play Services not being available on the emulator. I have flagged this issue with the emulator team and I will update here when I have more information.

If you can, use a real device till the correct version of Play Services can be made available to the emulator.

**Comment by kroikie** [comment]
@fafzal an appropriate version of Google Play Services is available on emulators running API version 21 or 19. If you make a Google API AVD with API version 21 or 19 the sample should work as expected. In the emulator check in Settings > Apps > Google Play Services that the version is 7.5.*
