### ISSUE TITLE
SomeTimes Push Notification Not Receiving In The App

### ISSUE THREAD

**Issue by ananth10** [googlesamples/google-services#329]
I am facing the issue in my android app. That I have configured GCM in my application.  App receiving the notification most of time. but sometime app did not receive notification from GCM server.  What is the reason for this issue? , and sometime app receives notification after some time. Can you please anyone help to fix this issue?

**Comment by samtstern** [comment]
@ananth10 sorry we never responded to this, it slipped past me.  There's not enough information here to debug, and I doubt the issue has to do with the code in this repo.

I'd suggest moving from GCM to FCM and then talking to [Firebase Support](https://firebase.google.com/support/) if you have more issues.

**Comment by ananth10** [comment]
@samtstern Thank you.
