### ISSUE TITLE
Plugin is too old, please update

### ISSUE THREAD

**Issue by pratamawijaya** [googlesamples/google-services#33]
Hi, I have an issue when building analytics

![screen shot 2015-07-24 at 10 21 50 am](https://cloud.githubusercontent.com/assets/2455823/8866994/d634eebe-31ed-11e5-9da5-860f488a4ba8.png)

here are my app/build.gradle
https://gist.github.com/pratamawijaya/91afa9f00c776d2c7c11

root build.gradle
https://gist.github.com/pratamawijaya/7ba87bdec7bce5f81f14

my Android Studio version 1.2.2

any ideas how to solve these ?

**Comment by lolobosse** [comment]
Same here

**Comment by lolobosse** [comment]
Change the line `com.android.tools.build:gradle:1.3.0-beta3` to `classpath 'com.android.tools.build:gradle:1.2.3'`

**Comment by Vitorspk** [comment]
try to back the version of gradle to 1.2.3

**Comment by kroikie** [comment]
Moving to version 1.3.0-beta4 should work.

**Comment by silvolu** [comment]
@kroikie I sent a pull request to update our code to use the latest stable version of the plugin, otherwise we're going to have a similar issue opened after every release of the beta plugin.
