### ISSUE TITLE
Android - Google Sign-in getDisplayName() giving me E-Mail instead of Display name on new account add

### ISSUE THREAD

**Issue by sudarshanthite** [googlesamples/google-services#333]
Android - Google Sign-in getDisplayName() giving me E-Mail instead of Display name on new account add while login.

  * Device: Moto e2 
  * OS version: 6.0
  * SDK version: API 23.
  * [Android] Google Play Services version: 11.0.2
  
I am using the following code,

```java
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    PrefUtil.setTaskBarColored(this, R.color.treasure_black);
    setContentView(R.layout.activity_login);
    ButterKnife.bind(this);
    loginHandler = new LoginHandler(this);
    GoogleSignInOptions gso = new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestEmail()
            .requestProfile()
            .build();

    mGoogleApiClient = new GoogleApiClient.Builder(this)
            .enableAutoManage(this, this)
            .addApi(Auth.GOOGLE_SIGN_IN_API, gso)
            .addApi(AppIndex.API).build();
}
@OnClick(R.id.btn_login)
    public void OnLoginButtonClick() {
        Intent signInIntent = Auth.GoogleSignInApi.getSignInIntent(mGoogleApiClient);
        startActivityForResult(signInIntent, RC_SIGN_IN);
        DialogClass.showDialog(this, "Signing In");
    }

@Override
public void onActivityResult(int requestCode, int resultCode, Intent data) {
    super.onActivityResult(requestCode, resultCode, data);

    if (requestCode == RC_SIGN_IN) {
        GoogleSignInResult result = Auth.GoogleSignInApi.getSignInResultFromIntent(data);
        handleSignInResult(result);

    } else {
        DialogClass.dismissDialog(this);
    }
}

private void handleSignInResult(GoogleSignInResult result) {

    if (result.isSuccess()) {
        GoogleSignInAccount acct = result.getSignInAccount();


        userName = acct.getDisplayName();
        Log.i("userName",userName);
        email = acct.getEmail();
        Uri url=null;
        if(acct.getPhotoUrl()!=null){
            url = acct.getPhotoUrl();

        }
        String imageUrl=null;
        if(url!=null && (!TextUtils.isEmpty(url.toString()))){
            imageUrl=url.toString();
            PrefUtil.putString(Constant.PreferenceKey.USER_IMAGE,imageUrl);

        }
        LoginRequestModel loginRequestModel = new LoginRequestModel(email, userName, imageUrl);
        loginHandler.getUserDetails(loginRequestModel);
        signOut();

    } else {
        DialogClass.dismissDialog(this);
    }
}
```  

Now, when I try to Sign-in into my app, if I use a pre-configured account by selecting it in the AccountChooser dialog, it works perfectly.

However, if in the AccountChooser dialog, I use the "Add account" option of the Account Chooser and add a new account, it gives me E-Mail in userName = acct.getDisplayName() instead of the users Name, and gives me null in url = acct.getPhotoUrl()

But If I logout of my app and use the same account by choosing the SAME account via account chooser, it works perfectly, and I cannot figure out why.

Any help will be appreciated.

Thanks.

**Comment by sudarshanthite** [comment]
Hi, 
After adding the 
requestIdToken('my server client id'); in GoogleSignInOptions i am getting the name, image and email id when adding new account while login, following is the  updated GoogleSignInOptions code replace your server client id with 'my server client id' string.

GoogleSignInOptions gso = new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                .requestEmail()
                .requestProfile()
                .requestIdToken('my server client id')
                .build();

Thanks.

**Comment by samtstern** [comment]
@sudarshanthite thanks for following up!

**Comment by Sainathhiwale** [comment]
Hi sudarshanthite ,
I have some special solution for you that i used in my project
 ` private void handleSignInResult(GoogleSignInResult result) {
        if (result.isSuccess()){
            GoogleSignInAccount account = result.getSignInAccount();
            EmailTextView.setText(account.getEmail());
            UserNameTextview.setText(account.getGivenName());
            Glide.with(this).load(account.getPhotoUrl()).into(PhotoImageview);


        }`
 getGivenName() is use to the given name (first name) of this person.  getFamilyName() is use to the family name (last name) of this person.display
