### ISSUE TITLE
RestApiActivity doesn't work properly

### ISSUE THREAD

**Issue by lyon1119** [googlesamples/google-services#335]
* Device: Pixel XL
  * OS version: 7.1.2
  
#### Steps to reproduce:

  1. Launch RestApiActivity
  2. Click "Sign in"
  3. People API return 400
  
#### Observed Results:

I found the following log. It looks like People API was changed.

08-31 16:48:26.249	20869	21115	W	RestApiActivity	    "message" : "personFields mask is required. Please specify one or more valid paths. Valid paths are documented at https://developers.google.com/people/api/rest/v1/people/get.",
  
#### Expected Results:

It should work.
  
#### Possible solution
I try to upgrade People API version to 'com.google.apis:google-api-services-people:v1-rev139-1.22.0' and add some related code. The patch is in the attachment
[patch.txt](https://github.com/googlesamples/google-services/files/1266643/patch.txt)

.

**Comment by kohanian** [comment]
lyon's solution worked for me as well.

**Comment by samtstern** [comment]
@lyon1119 @kohanian thanks for this, does either of you want to submit a PR to fix it?

**Comment by samtstern** [comment]
Closed via PR, thanks!
