### ISSUE TITLE
ios - GoogleSignIn library no call `signInWillDispatch:error:` before start SFAuthenticationSession authorization

### ISSUE THREAD

**Issue by seaburg** [googlesamples/google-services#336]
Hi!

Step 2: Describe your environment:
OS version: iOS 11
SDK version: iOS 10 and 11
Library version: 4.10

Step 3: Describe the problem:

GoogleSignIn library does not call `[id<GIDSignInUIDelegate> signInWillDispatch:error:]` method before start SFAuthenticationSession authorization

**Comment by microdevil** [comment]
Solved on library version 4.11

**Comment by seaburg** [comment]
Thanks!
