### ISSUE TITLE
Google Login not working in cordova plugin

### ISSUE THREAD

**Issue by sudarshanthite** [googlesamples/google-services#338]
Environment

  * Device: Any Android _____
  * OS version: Any Android OS Version _____
  * SDK version:  Api level 25+_____
  * [Android] Google Play Services version:  11+_____
  
Problem : 

With the use of this google login library code  i have created  .AAR file, When i use this .AAR file in any android project google login works fine but  when i create the Cordova phonegap plugin with using this .AAR which has your google login library code integrated that time google login  dose not work and it gives me the request and response code '0' at onActivityResult.

Cordova related description :
When i run the cordova phonegap app using terminal in wich i use .AAR of google login integrated that time google login dose not work.
but when i import the particular android platform from the cordova phonegap app project into to the android studio and run the project then google login works fine.  

So can you please check issue.

 Steps to reproduce:

  1. Create the .AAR with help of this library code
  2. Create the cordova phonegap plugin.
  3. Add the .AAR in that phonegap plugin.
  4. Create the Cordova phonegap project.
  5. Add the created  phonegap plugin to the created phonegap project.
  6. Run the phonegap project.
  

Thanks
Sudarshan thite.

**Comment by samtstern** [comment]
@sudarshanthite apologies for the late response here.  We can't really answer in-depth cordova questions in this repository, these issues should be related to the code presented or reports of bugs in the SDK itself.

I hope you found help for this elsewhere!
