### ISSUE TITLE
How to show YouTube login channel list by Sign-In API?

### ISSUE THREAD

**Issue by lomoya90** [googlesamples/google-services#343]
**## When I use Sign-In API, my login UI looks like this:**
![img_20171127_190735](https://user-images.githubusercontent.com/6427266/33263995-c2acb680-d3a6-11e7-901f-0a50daae03fc.jpg)
## **but, I want it to look like:** 
![img_20171127_190840](https://user-images.githubusercontent.com/6427266/33264016-d9a9deda-d3a6-11e7-8b09-011b94681bb8.jpg)

**Comment by samtstern** [comment]
@lomoya90 I don't quite understand the request, but further customization of that screen is not currently possible.  That screen will only show Google accounts on the device, limited by what you pass to `GoogleSignInOptions`.
