### ISSUE TITLE
Can't load "https://myaccount.google.com" via ajax after successful Integrating of Google Sign-In button into my server

### ISSUE THREAD

**Issue by AngelTs** [googlesamples/google-services#354]
The login into my google account is successful, i see my data in the console, but after that I can't load the page "https://myaccount.google.com" via AJAX (POST or GET)?
The error is:
XMLHttpRequest cannot load https://myaccount.google.com/security. Response for preflight is invalid (redirect)

Note: I can load this page only with window.location via javascript!

**Comment by samtstern** [comment]
@AngelTs I don't think this issue belongs here.  This repository has Android and iOS samples, not web.  Try StackOverflow or another forum!
