### ISSUE TITLE
iOS 'GoogleSignIn' pod - Select account screen does not show up again

### ISSUE THREAD

**Issue by bes** [googlesamples/google-services#357]
### Step 1: Are you in the right place?

I believe I am in the right place, however there is a [StackOverflow question](https://stackoverflow.com/questions/49256119/sign-in-with-google-prevents-the-user-to-sign-in-again-with-different-account) tracking this as well (not written by me, but +1'd by me)

### Step 2: Describe your environment

  * Device: iPad (iOS 10, 11), iPhone (iOS 10, 11), iOS iPhone emulator
  * OS version: iOS 10, 11
  * SDK version: iOS 11 SDK / pod 'GoogleSignIn', '= 4.1.2'
  
### Step 3: Describe the problem:

After selecting a Google account once, the user cannot select an account again, unless the user goes into Safari and chooses to sign out (or add more accounts) there.

This issue persists regardless of if the user selects the `Sign out` or `Disconnect` button in the Sample (or for that matter in any app that uses the iOS GoogleSignIn SDK 4.1.2.

#### Steps to reproduce:

  1. Have an app that signs in using GoogleSignIn SDK, e.g. `google-services/ios/signin` of this repository (Objective-C version, but the same happens with Swift)
  2. Press sign in button
  3. The select google account web view is shown - select a user
  4. Sign out or disconnect, does not matter
  5. Sign in again 
  6. =ERROR= The user is NOT prompted to select an account, but immediately signed in.
  
#### Observed Results:

As you can see from the video (captured with the latest current version of `google-services/ios/signin` from this repository), it is not possible to choose a user, once the choice has been made.

![can_not_select_user](https://user-images.githubusercontent.com/85731/37512007-24660214-2901-11e8-887a-20868f96481e.gif)
  
#### Expected Results:

After calling `[[GIDSignIn sharedInstance] signOut];` or `GIDSignIn.sharedInstance().signOut()` the user should be able to select a new google account.
  
#### Relevant Code:

The code in this repository.

Thank you!

**Comment by DanSessions** [comment]
I'm also seeing this behaviour. Was it introduced in 4.1.0 with the use of SFAuthenticationSession?

**Comment by s9027059** [comment]
Have the same issue here with SDK v4.0.2 and v4.1.2, this caused user can't switch account within our App.

**Comment by s9027059** [comment]
Login process should redirect to a page with existed login account (if any) or Use another account options after tapped GIDSignInButton, but now that page is gone once you have signed in succeed.
There are 2 workarounds can bring that page back for now:

1.  Clear Website Data of Safari in settings
2. Install another App need Google account and log in with new account (e.g. Gmail, Google drive...)

**Comment by Cokodude** [comment]
Having the same issue on 4.1.1 and updating to 4.1.2 did not help. 

A workaround of opening a logout page (https://accounts.google.com/Logout) from SFSafariViewController before signing in seems to work in iOS 10, but not iOS 11... possibly due to the SDK using SFAuthenticationSession. Will have to downgrade to 4.0.1 and see if workaround works for both iOS versions there.

**Comment by abhimuralidharan** [comment]
Facing the same issue. What is the fix? signout and disconnect does nothing. Any older versions of the sdk helps?

**Comment by netmaid** [comment]
I'm also facing this problem. Help me.

**Comment by abhimuralidharan** [comment]
This issue is fixed I believe.

**Comment by Cokodude** [comment]
The issue is not yet fixed for me on v4.1.2. If the user is logged in to only one account in Safari, the account selector is not presented and the SDK automatically signs in to the account that's logged in in Safari.

**Comment by aarsland** [comment]
Experiences the same behaviour - have tried v.4.0.0, 4.0.2, 4.1.1 and 4.1.2. Any workarounds?

**Comment by s9027059** [comment]
New workaround here: SDK v4.0.1 + opening a logout page (https://accounts.google.com/Logout) from SFSafariViewController (@Cokodude mentioned)

**Comment by mhazy** [comment]
The logout page workaround will not work for iOS 11.x due to how SFAuthenticationSession works

**Comment by MariaKulkova** [comment]
There are many Authentication URI parameters. One of them is "prompt" which could have a "select_account" value. It helped me to resolve the same issue for Auth0 service Google integration. Maybe could be useful for your issue.
See docs here: https://developers.google.com/identity/protocols/OpenIDConnect#authenticationuriparameters

**Comment by KrishnaChaitanyaAmjuri** [comment]
When the user logs out, if we call `GIDSignIn.sharedInstance()?.signOut()`. Next time, then the email selection screen will appear.

It works for us

**Comment by acenspades** [comment]
Hello
I am getting the same results as explained above by OP.  
I'm using [[GIDSignIn sharedInstance].signOut]; and [[GIDSignIn sharedInstance].disconnect].

I installed the Google SDK using Cocoapods but is there a way to tell which version of the Google SDK i have? I'm assuming Cocoapods installed the latest version.  Supposedly, the latest version 5.0 fixed the logout issue.  

Thanks
