### ISSUE TITLE
R.xml.global_tracker  :  cannot resolve symbol 'xml'?

### ISSUE THREAD

**Issue by JackJin2014** [googlesamples/google-services#36]
hi:
    i clone this demo : google-services/android/analytics/    and when i build this demo  ,     in AnalyticsApplication.java  @ line 40 show: "R.xml.global_tracker  :  cannot resolve symbol 'xml'?" 
 how to fix it? thx

**Comment by kroikie** [comment]
Looks like you are missing the configuration file, [check step 2 here][1]

[1]: https://developers.google.com/analytics/devguides/collection/android/v4/start

**Comment by kroikie** [comment]
Closing this issue, no response.

**Comment by narrow001** [comment]
Added the configuration file. Then to having the same error.

**Comment by silvolu** [comment]
Does the package name that you have provided to get the configuration file match the package name that you are using when building your app?

**Comment by brendler** [comment]
I found this page while also having the same problem. The reply by @silvolu helped me fix the issue. I had renamed the app package and had to recreate a new configuration file for analytics. Thanks!

**Comment by staz1000** [comment]
I just had this issue despite having the config file. The important step is to clean the project once the file is added

**Comment by leocadiotine** [comment]
Is it possible to use muiltiple application IDs (e.g. using applicationIdSuffix) with Google Analytics? When I set an applicationIdSuffix to a build variant, this error happens, and I can't put multiple versions of the config file.

**Comment by bigD666** [comment]
I don't under stand these emails

**Comment by johanvs** [comment]
The problem is that when we use applicationIdSuffix, the package name of the app change, and then Google Analytics doesn't work with the "google-services.json" config file.
I have the same problem.

**Comment by samtstern** [comment]
@johanvs this is essentially the same issue as #54, please see that discussion for some possible fixes.

**Comment by johanvs** [comment]
Thanks @samtstern. Yes and there is a workaround in the end of the discussion.

**Comment by samtstern** [comment]
See #54 for an update.

**Comment by squm** [comment]
same issue

**Comment by oguzhangedik** [comment]
I had that issue. In my case, i had configured google-services.json badly. Because before, i added google-services.json file for google cloud messaging service and then i had to modified google-services.json file for google analytics service..  So you should be careful about these parameters :

- You should be sure about "tracking_id"
- Set "status" : 2 which is in "analytics_service".
- Set "status" : 1 which is in "appinvite_service".
- Set "status" : 1 which is in "ads_service".

restart Android Studio and rebuild gradle.

**Comment by abelcallejo** [comment]
Its 2019, I'm having this issue. When I create such xml file, it then becomes duplicate. Making it another error.

**Comment by nielsenvancura** [comment]
make sure your tracker xml is placed in /res/xml not in /res/values
