### ISSUE TITLE
Unable to receive notification

### ISSUE THREAD

**Issue by itsjaye** [googlesamples/google-services#37]
I did all the steps on the guide but the notification did not appear on the device (i am not using emulator). There is also nothing on the logcat that shows that the GCM message was received.
Here's the message from the terminal:
:gcmsender:run                                                               
{"message_id":4808486419477175595}
Check your device/emulator for notification or logcat for confirmation of the receipt of the GCM message.

**Comment by kroikie** [comment]
Did the app display the "Token retrieved and sent to server" message?

**Comment by itsjaye** [comment]
Yes, it did.

**Comment by kroikie** [comment]
What device are you using?

**Comment by itsjaye** [comment]
I am using android 4.4.2.

**Comment by kroikie** [comment]
Device?

**Comment by itsjaye** [comment]
It's Starmobile UP HD. It's not that popular OEM but has Google play services/ playstore on it. Okay, I will try this on a different device. I will also try this on AVD.

**Comment by itsjaye** [comment]
Hi! I tried another device (Samsung SM-G313Hz) and it worked. Thanks for the suggestion. Something is really wrong with my first device.

**Comment by kroikie** [comment]
Glad to hear you got it working.
