### ISSUE TITLE
com.google.android.gms.com mon. API. ApiException: 10

### ISSUE THREAD

**Issue by YongHuiLuo** [googlesamples/google-services#373]
My project was originally a Google Drive login using the REST API, and I have applied for the Client ID. Now you want to use the Sign in SDK for login, get the code through the requestServerAuthCode, and when you create a new credential, the error **"failed: create the Oauth client"** is prompted. Program is running at **"com.google.android.gms.com mon. API. ApiException: 10"** error, please help to solve, thank you very much

**Comment by samtstern** [comment]
@YongHuiLuo there's not enough information here to debug, and I am not sure it's relevant to this sample repository.  Maybe try StackOverflow to get help with your app.
