### ISSUE TITLE
Canceling a Sign in leads to GoogleSignInStatusCodes.ERROR

### ISSUE THREAD

**Issue by awenger** [googlesamples/google-services#374]
### Step 1: Are you in the right place?

A better place would be a official bug tracker for the play services...
Luckily the problem is reproducible in the Sample App

### Step 2: Describe your environment

  * Device: Pixel 2
  * OS version: 8.1.0
  * SDK version: 27
https://github.com/googlesamples/google-services/blob/3f8dadb779ecf1cd49935accde20e498f895dd08/android/signin/app/build.gradle#L4
  * [Android] Google Play Services version: 15.0.1
https://github.com/googlesamples/google-services/blob/3f8dadb779ecf1cd49935accde20e498f895dd08/android/signin/app/build.gradle#L39
  
### Step 3: Describe the problem:
Canceling the account chooser in the SignInActivity (https://github.com/googlesamples/google-services/blob/3f8dadb779ecf1cd49935accde20e498f895dd08/android/signin/app/src/main/java/com/google/samples/quickstart/signin/SignInActivity.java) leads to a `GoogleSignInStatusCodes.ERROR` instead of `GoogleSignInStatusCodes.SIGN_IN_CANCELLED` status Code
#### Steps to reproduce:

  1. Open the "SignInActivity"
  2. Click the "Sign In" button
  3. Cancel the chooser by clicking the background
  
#### Observed Results:

The returned status code is GoogleSignInStatusCodes.ERROR (13)
#### Expected Results:

It should return a status code with GoogleSignInStatusCodes.SIGN_IN_CANCELLED (12501)  
#### Relevant Code:

I changed this line https://github.com/googlesamples/google-services/blob/3f8dadb779ecf1cd49935accde20e498f895dd08/android/signin/app/src/main/java/com/google/samples/quickstart/signin/SignInActivity.java#L105 to :
  ```
    switch (e.getStatusCode()) {
        case GoogleSignInStatusCodes.CANCELED:
            Log.w(TAG, "CANCELED");
            break;
        case GoogleSignInStatusCodes.NETWORK_ERROR:
            Log.w(TAG, "NETWORK_ERROR");
            break;
        case GoogleSignInStatusCodes.SIGN_IN_CANCELLED:
            Log.w(TAG, "SIGN_IN_CANCELLED");
            break;
        case GoogleSignInStatusCodes.ERROR:
            Log.w(TAG, "ERROR");
            break;
    }
    Log.w(TAG, "signInResult:failed code=" + e.getStatusCode());
  ```
after canceling the account chooser:
```
ERROR
signInResult:failed code=13
```

**Comment by jeanRibeiro** [comment]
I'm also having the same problem

**Comment by awenger** [comment]
@samtstern is there any better way to report this issue?

**Comment by samtstern** [comment]
@awenger apologies for the slow response here. I can confirm that with this sample app I also get code 13 (`ERROR`).  I will report this as a bug:
https://developers.google.com/android/reference/com/google/android/gms/common/api/CommonStatusCodes.html#ERROR

**Comment by awenger** [comment]
@samtstern no worries, I didn't expect any fast response, this is still the sample project repository. However since I can't access your bug report, are there any updates on this? Any workaround we could use to prevent this? Any eta of a fix? Will it be fixed?
This bug affects the ux of our app quite a bit and I would like to plan my strategy to fix/circumvent this.

**Comment by SammyOdenhoven** [comment]
Having this problem as well.

**Comment by samtstern** [comment]
Nothing to report yet, I will let you know when I have new information.  Thanks for your patience!

**Comment by samtstern** [comment]
Ok an update here:

- This is a definite regression, and the true fix for this will come in a future release of the Google Play services **app** which will be updated over the air.  Those updates take a long time though (~months).  When this happens your app will magically start working again, even if you change no code.
- We have a workaround that we can release as part of the Google Play services **sdk**.  This will make the `SIGN_IN_CANCELLED` error code appear when it should.  This workaround SDK update can be released in the short term.  I will update this thread when it happens, and you can update your apps.

**Comment by samtstern** [comment]
Version `16.0.0` of `play-services-auth` has been released and should fix this issue, thanks all!
