### ISSUE TITLE
AppInvites example permission error

### ISSUE THREAD

**Issue by evang2015** [googlesamples/google-services#39]
Hi there, I am having a problem with the latest version of Google AppInvites for IOS. I was using the previous version last month and it worked before. But somehow the new version did not work anymore or Google had changed something recently on the AppInvites backend.

I have installed Google's default AppInvitesExample.xcodeproj from: pod try Google
I have configured the bundle ID and reverse client id and got the correct GoogleService-Info.plist file.
Then I executed the xcworkspace and run the xcode project in iphone simulator.
Google Signin is working as I can see my name "Signed in as xxx".
But when I click the button "INVITE FRIENDS" the appinvite dialog appeared for a while but it automatically closes. After that, I will get the error "The operation couldn't be completed. (The caller does not have permission)

Can anybody help ? Thanks !

![appinviteerror](https://cloud.githubusercontent.com/assets/13758748/9216231/50767f40-40e8-11e5-9ef6-f988584abfc1.png)

**Comment by ianbarber** [comment]
Is there any more detail logged in the console in XCode when you see this error?

**Comment by frogermcs** [comment]
+1

There is no additional info in console. 

NSError returned from delegate:

Error Domain=com.google.gpp.invite Code=-400 "The operation couldn’t be completed. (The caller does not have permission)" UserInfo=0x170271f40 {NSLocalizedDescription=The operation couldn’t be completed. (The caller does not have permission)}

It seems that error can be connected with suggestion loading (not sure).

To reproduce this issue just just change bundle ID of example app, make all needed configuration and launch it on device. Problem is non-deterministic and it seems that after a few minutes/hours it works as is should (suggested contacts are presented, and window doesn't close).

**Comment by gguuss** [comment]
Did you manually configure the sample or generate a GoogleServices-info.plist from https://developers.google.com/mobile/add?

**Comment by ianbarber** [comment]
Closing as AppInvites has now moved to Firebase!
