### ISSUE TITLE
GoogleSignInAccount' 'getIdToken()' always return error message 'com.google.android.gms.common.api.ApiException: 10'

### ISSUE THREAD

**Issue by colodinalexandru** [googlesamples/google-services#412]
* Device: Any
  * OS version: Any
  * SDK version: Any
  * [Android] Google Play Services version: Any

Using Class 'GoogleSignInAccount' with Method 'getIdToken()' always return the following Error Message 'com.google.android.gms.common.api.ApiException: 10' also, checking Method 'onActivityResult' I receive 'resultCode = 0'

This issue appeared after July 2 2019. Before this date, everything worked smooth.

Tried different ways to avoid this issues, however, no luck:

- Tried to use different package names.

- Tried to use different fingerprints in Release and Debug mode.

- Also, tried to use different Google Developer Accounts.

No matter what I try to do, always receive the same error message
Please let me know if someone experienced this issue and know a solution

**Comment by antranvn** [comment]
I also have this issue always:
handleSignInResult: com.google.android.gms.common.api.ApiException: 10:

I added SHA1, package name to Google Console

I use one gmail account for firebase and another gmail account in Google Console, is it issue?

**Comment by shakram02** [comment]
Checkout #360

**Comment by antranvn** [comment]
@shakram02 
Thanks, but i checked it before comment.
@colodinalexandru: have you resolved it ?

**Comment by colodinalexandru** [comment]
Hi, @antranvn. No , I not rezolved it with standar login , try to use firebase

**Comment by antranvn** [comment]
It means you can login google by firebase ?

**Comment by colodinalexandru** [comment]
Yes, sir , with firebase google login works, without firebase is not working.

**Comment by mmeza-developer** [comment]
Hi Folks, i have same problem, but i solved it with [#360 ](url), you must use android studio to ganerate the SHA-1 hash

**Comment by Daniel-Redfern** [comment]
I am having the same problem.  #360 did not solve it for me.  The SignInActivity and SignInActivityWithDrive work, and when I run SignInActivityWithDrive I get the oAuth consent screen I set up for the project associated with the credentials I created in the developer console, so I *think* I've set that up with the right SHA-1 and package.  I get the exception running IdTokenActivity. I have copied the client id directly out of the developer console and pasted it into my strings.xlm in my project.  It is resolving correctly when I look at it in the debugger.  I am not using Firebase.
