### ISSUE TITLE
Impossible to implement token revocation when user removed his Google account

### ISSUE THREAD

**Issue by UgVaDevLabs** [googlesamples/google-services#414]
Documentation https://developers.google.com/identity/sign-in/android/v1/disconnect says "If the user deletes their account, you must delete the information that your app obtained from the Google APIs." However AFAIK there is no possible way to do this because even if user removes his Google account "GoogleSignIn.getLastSignedInAccount" still returns his account. Ideally it should return null. I have opened another issue asking about this behaviour but apparently it was closed. https://github.com/googlesamples/google-services/issues/410 So I am reopening a new one with the same question. How do I revoke google access token if user has removed his account

### Step 2: Describe your environment

  * Device: Any
  * OS version: Any
  * SDK version: Any
  * [Android] Google Play Services version: Any

**Comment by samtstern** [comment]
@UgVaDevLabs that guidance is not about when a user deletes the Google account from their device, it is about when the user deletes their account on your service.  At that point you should clean up all user data that you previously retrieved from Google APIs and stored.

This is the type of operation that should be done server-side if possible, as that's where you should be storing access and refresh tokens (if you store them at all).
