### ISSUE TITLE
camel naming convention is not corrected parsed by plugin when searching google-services.json

### ISSUE THREAD

**Issue by ccyr119** [googlesamples/google-services#415]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
yes

### Step 2: Describe your environment

  * Device:  compile step
  * OS version: compile step
  * SDK version: compile step
  * [Android] Google Play Services version: 4.3.0
  
### Step 3: Describe the problem:
camel naming convention is not corrected parsed by plugin when searching google-services.json

#### Steps to reproduce:

  1. name a product flavor with camel naming convension, like: idPlay
  2. follow the instruction of https://developers.google.com/android/guides/google-services-plugin
  3. compile project
  
#### Observed Results:

  * What happened?  This could be a description, log output, etc.
ERROR: File google-services.json is missing. The Google Services Plugin cannot function without it. 
 Searched Location: 
src\idPlay_obb_umeng\google-services.json
src\debug\google-services.json
src\idPlay_obb_umengDebug\google-services.json
src\id\google-services.json
src\idDebug\google-services.json
src\idPlay_obb_umeng\debug\google-services.json
src\debug\idPlay_obb_umeng\google-services.json
src\id\debug\google-services.json
src\id\play_obb_umeng\google-services.json
src\id\play_obb_umengDebug\google-services.json
src\id\play_obb_umeng\debug\google-services.json
google-services.json
  
#### Expected Results:

  * What did you expect to happen?
should search "src\idPlay\google-services.json" not "src\id\google-services.json"
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by samtstern** [comment]
@ccyr119 could you file an issue on this repository?
https://github.com/google/play-services-plugins

That's actually where the plugin code lives.  I would transfer the issue myself but GitHub doesn't allow transfers across organizations.

Also it would be helpful to show your `build.gradle` file so we can see where the flavors and variants come from.
