### ISSUE TITLE
Execution failed for task ':app:prepareDebugAndroidTestDependencies'.

### ISSUE THREAD

**Issue by slayer35** [googlesamples/google-services#42]
I update google play services ,and did all steps in tutorial but still get this errors.

Error:(56, 62) error: cannot find symbol variable gcm_defaultSenderId
(RegistrationIntentService.java)
and also another error 

Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by andresrivas1506** [comment]
Error:(51, 66) error: cannot find symbol variable gcm_defaultSenderId
