### ISSUE TITLE
Connecting to Google Fit Consent Screen Denying one of multi permissions will not connect

### ISSUE THREAD

**Issue by Karringgton** [googlesamples/google-services#423]
### Step 1: Are you in the right place?

Appears to be a feature issue, not an app issue.

### Step 2: Describe your environment

  * Device: Pixel3a, Samsung S8+, and more
  * OS version: reproduced on Android 9 and Android 10, might be more
  * SDK version: 28
  * [Android] Google Play Services version: Gradle uses 16.0.1 for fitness and auth
  

### Step 3: Describe the problem:

My app is trying to connect to Google Fit. The user is prompted to pick a Google Account and once picked, the "Consent Screen" shows up requiring users to accept or deny each permission. There are separate screens for each permission. Once the user has gone through each permission pop up to accept or deny, a main screen appears that shows a list of all the permissions with check marks next to the ones that the user had allowed. If the user denies one or more of the permissions, it usually closes the pop up, shows a spinner, and then restarts the consent screen pop ups to force the user to go through each permission pop up and then continues to the main pop up of the whole list of permissions. 

#### Steps to reproduce:

  1. Have an app call GoogleSignIn.requestPermissions() with the fitnessOptions seen below which prompts the user to pick a Google Account.
  2. Pick a Google Account to use. This then prompts the user to accept specific permissions.
  3. Go through all 7 permission screen pop ups by allowing some but denying some.
  4. After all 7 permissions pop up screens are completed, the user is taken to the last screen which shows a list of all the permissions allowed and denied via check boxes. Have at least one option denied. Hit Accept.
  
#### Observed Results:

The pop up disappears, a spinner appears, and it goes back to step #3 where the permissions pop up (1 out of 7) shows with the option to accept or deny. 
  
#### Expected Results:

The pop up disappears and Google Fit should be connected and have only the allowed permissions accepted.
  
#### Relevant Code:

public final static FitnessOptions fitnessOptions = FitnessOptions.builder()
            .addDataType(DataType.TYPE_STEP_COUNT_DELTA, FitnessOptions.ACCESS_READ)
            .addDataType(DataType.AGGREGATE_STEP_COUNT_DELTA, FitnessOptions.ACCESS_READ)
            .addDataType(DataType.TYPE_HEART_RATE_BPM, FitnessOptions.ACCESS_READ)
            .addDataType(DataType.TYPE_NUTRITION, FitnessOptions.ACCESS_READ)
            .addDataType(HealthDataTypes.TYPE_BLOOD_PRESSURE, FitnessOptions.ACCESS_READ)
            .addDataType(HealthDataTypes.TYPE_OXYGEN_SATURATION, FitnessOptions.ACCESS_READ)
            .addDataType(HealthDataTypes.TYPE_BLOOD_GLUCOSE, FitnessOptions.ACCESS_READ)
            .addDataType(HealthDataTypes.TYPE_MENSTRUATION, FitnessOptions.ACCESS_READ)
            .build();

if (!GoogleSignIn.hasPermissions(getLastSignedInAccount(getActivityBase()), fitnessOptions)) {
                    GoogleSignIn.requestPermissions(
                            this,
                            GOOGLE_FIT_PERMISSIONS_REQUEST_CODE,
                            getLastSignedInAccount(getActivityBase()),
                            fitnessOptions);
                }

**Comment by samtstern** [comment]
@Karringgton thanks for the report.  This seems like a really specific Google Fit issue and I don't think I can help you.

I would suggest filing an issue here:
https://github.com/android/fit-samples

And mention @codingjeremy in the issue, hopefully that will get this in front of the right people

**Comment by ksvenky** [comment]
@Karringgton We are also facing the same issue you mentioned. Please let us know if you were able to find a solution for that. Eagerly waiting for your response.

**Comment by shiva317-gti** [comment]
@Karringgton me too facing same issue in google fit consent screen in ionic cordova application, Im using cordova-plugin-health to fetch health data from google fit. 
Please let us know, if you need more information.

**Comment by kdongare** [comment]
@Karringgton I am also facing the same issue in google fit consent screen.
Please let me know, if you need more information or did you find any solution to it?

@codingjeremy any updates on this?
