### ISSUE TITLE
iOS 13 - Google Sign In not working

### ISSUE THREAD

**Issue by coanag** [googlesamples/google-services#424]
Recently i found and error when trying to update my app at iOS 13.
Ive implement Google Sign in and i am getting error at : 

    func sign(_ signIn: GIDSignIn!, didSignInFor user: GIDGoogleUser!,
              withError error: Error!) {
        if let error = error {
            if (error as NSError).code == GIDSignInErrorCode.hasNoAuthInKeychain.rawValue {
                print("The user has not signed in before or they have since signed out.")
            } else {
                        ERROR IN THIS LINE >>>>>>>>>   print("\(error.localizedDescription)")
            }
            return
        }
}

The error produced is :  "org.openid.appauth.general error -3."
I have noticed that on devices with ios 12, everything its ok.
Im using the SDK version (not pods).

Any suggestions?
 

Device: iPhone 11 Pro
OS version: 13
Lang: Swift 5

**Comment by thillsman** [comment]
Same here. (We use the Cocoapod.)

Googling leads me to thinking that AppAuth needs to be bumped to 1.2.0 in the GIDSignIn pod.

**Comment by wyon1314** [comment]
I am the same here.
The error produced is : "org.openid.appauth.general error -3."

**Comment by ATMLGG** [comment]
Same here.
Xcode10 iOS13 is ok.
Xcode11 iOS13 crash at signIn.

**Comment by ATMLGG** [comment]
I fix this issue by using 4.4.0 in Xcode 11, iOS13. The latest version 5.0.0 still has the problem.

**Comment by coanag** [comment]
Use sdk v5.0.1 and its fixed.
