### ISSUE TITLE
Remove UIWebview API  from ios implementation

### ISSUE THREAD

**Issue by hbarylskyi** [googlesamples/google-services#454]
* Device: all iOS devices
  *  SDK version: 5.0.2
  * OS version: 13.4.1

### Step 3: Describe the problem:

Seems like  GoogleSignIn  pod  is  still using UIWebview  API. I'm working on react-native app which  uses https://github.com/react-native-community/google-signin. This  library  is using GoogleSignIn SDK. AppStore  does not accept iOS apps  using  UIWebview  anymore. 

Could you transfer the  SDK  to  WKWebView?

Information regarding GoogleSignIn  using UIWebview is taken  from  here: https://github.com/react-native-community/google-signin/issues/851.

#### Steps to reproduce:

  1. Try to upload an app using GoogleSignIn  to the  AppStore.
  
#### Observed Results:

  Binary gets rejected by AppStore.
  
#### Expected Results:

The app  to  get  an update.

**Comment by ydv0121** [comment]
+1

**Comment by mayur43s** [comment]
This is happening as I'm still seeing the use of `UIWebView` and the app is getting rejected on App Store here's the terminal output with `pod update` 
```
Installing AppAuth (1.3.0)
Installing GTMAppAuth (1.0.0)
Installing GTMSessionFetcher 1.4.0 (source changed to `https://cdn.cocoapods.org/` from `trunk`)
Installing GoogleSignIn 5.0.2 (was 4.4.0 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
```
Now when I do `grep -r "UIWeb" .` It gives this output:
```
./Pods/AppAuth/Source/AppAuth.h:    for the auth request. `UIWebView` and `WKWebView` are explicitly *not*
./Pods/AppAuth/README.md:for the auth request. `UIWebView` and `WKWebView` are explicitly *not*
./Pods/GoogleSignIn/CHANGELOG.md:- Supports sign-in via UIWebView rather than app switching to a browser,```

**Comment by pseudocolor** [comment]
+1 on this

**Comment by akinncar** [comment]
+1

**Comment by ashu090990** [comment]
I am using Google Sign-In in my App and the app is getting rejected on App Store, received mail with following message 

ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. 

I use "grep -r UIWebView ." command in project Terminal and getting Google Sign-In related files using UIWebView.

**Comment by vonovak** [comment]
@samtstern you seem to be active around this repo, can you confirm that you're still using `UIWebView`? Thank you!

**Comment by akinncar** [comment]
I solved this issue in my project updating my SDK 4.4.0 to 5.0.0.

Ussing "grep -r UIWebView ." command at therminal, returns some files with contents UIWebView only comments at the code or binary files. My RN versions is 0.59.9, and this version contains UIWebView in React lib.

The I do:

<b>Remove four files on Xcode<br>
{PROJECT_NAME}/Libraries/React.xcodeproj/React/Views</b>

```
RCTWebView.h

RCTWebView.m

RCTWebViewManager.h

RCTWebViewManager.m
```

<b>Remove two lines on Xcode<br>
Pods/Development Pode/React/Support Files/React-umbrella.h</b>

```
#import "React/RCTWebView.h"

#import "React/RCTWebViewManager.h"
```



By update Google SDK, I needed update react-native-google-signin 1.2.2 to 2.1.1, code is very similar.

**Comment by samtstern** [comment]
Hey all.  Google Sign In versions 4 and earlier are compiled with references to UIWebView, which Apple has been discouraging the use of.  It looks like they've just begun rejecting apps that include these references, although I'm not sure exactly what the policy is.  The solution is to **upgrade to the latest Google Sign In SDK (Version 5)** which does not make use of UIWebView.

If you are using React Native you may be getting UIWebView references from RN, which is unrelated to Google Sign In:
https://github.com/facebook/react-native/issues/26255

**Comment by mayur43s** [comment]
@samtstern I'm getting that issue with GoogleSignIn (5.0.2) so it's still not solved.

**Comment by vonovak** [comment]
@mayur43s I'm guessing you're using some other dependency that uses UIWebView, then.

**Comment by mayur43s** [comment]
@vonovak Can you please see my comment above. `grep -r "UIWeb" .` clearly shows that GoogleSignIn is using a reference to UIWebview along with other dependent pods.

**Comment by hbarylskyi** [comment]
I’m also thinking that GoogleSignIn still has UIWebView. If I remember correctly, I was able to upload a build only after I removed googlesignin dependency. I’ll try to check this again today to be 100% sure.

**Comment by vonovak** [comment]
@mayur43s those references do not point to code usage but only to comments, and my understanding is that apple checks the application code after you upload the ipa, where there should be no comments included.

**Comment by ydv0121** [comment]
> Hey all. Google Sign In versions 4 and earlier are compiled with references to UIWebView, which Apple has been discouraging the use of. It looks like they've just begun rejecting apps that include these references, although I'm not sure exactly what the policy is. The solution is to **upgrade to the latest Google Sign In SDK (Version 5)** which does not make use of UIWebView.
> 
> If you are using React Native you may be getting UIWebView references from RN, which is unrelated to Google Sign In:
> [facebook/react-native#26255](https://github.com/facebook/react-native/issues/26255)

issue from Google SDK when i use Google SIgn in SDK (5.0.2) which is latest.my app was rejected by the apple.
if i remove google SDK then my build successfully uploaded.

**Comment by mayur43s** [comment]
@vonovak But the app is getting rejected due to reference even although that's not in code. @ydv0121 yes when you remove it the app gets submitted successfully but when you use that pod the build gets rejected.

**Comment by ydv0121** [comment]
> @vonovak But the app is getting rejected due to reference even although that's not in code. @ydv0121 yes when you remove it the app gets submitted successfully but when you use that pod the build gets rejected.

yes so is it confirm issue from the google signin SDK?

**Comment by mayur43s** [comment]
> > @vonovak But the app is getting rejected due to reference even although that's not in code. @ydv0121 yes when you remove it the app gets submitted successfully but when you use that pod the build gets rejected.
> 
> yes so is it confirm issue from the google signin SDK?

Yes but @vonovak & @samtstern doesn't believe us.

**Comment by samtstern** [comment]
I will see if we can get the word `UIWebView` removed from the pod's `CHANGELOG.md` even though I don't think that should be ending up in the `ipa` file.

**Comment by hbarylskyi** [comment]
I reinstalled @react-native-community/google-sign-in, latest version, ran pod install, archived and the app and it was accepted.

**Comment by mayur43s** [comment]
@samtstern Yes but that word is being used some other dependency files as well:
```
./Pods/AppAuth/Source/AppAuth.h:    for the auth request. `UIWebView` and `WKWebView` are explicitly *not*
./Pods/AppAuth/README.md:for the auth request. `UIWebView` and `WKWebView` are explicitly *not*
./Pods/GoogleSignIn/CHANGELOG.md:- Supports sign-in via UIWebView rather than app switching to a browser,
```

**Comment by samtstern** [comment]
Thanks @mayur43s 

I can definitely see how `AppAuth.h` is causing an issue ... that is code that would be inside the app.  But I can't see how `README.md` and `CHANGELOG.md` from pods would be causing an issue.

Does anyone have more information from Apple about their rejection?  Can you prove it's coming from a reference in a file within GoogleSignIn?

**Comment by hbarylskyi** [comment]
@samtstern see my comment  above
