### ISSUE TITLE
The problem with the use of the authorization to Google for a subscription to Youtube channel

### ISSUE THREAD

**Issue by Kalligraf** [googlesamples/google-services#48]
Good afternoon
I use your example SignIn for authorization to Google and getting a token for subscription to the channel Youtube.
To do this, use the following function:

    -(void) subscription{
  
        NSString *channelId = @«MyChannelId»;
        NSString *api_Key = @«MY_IOS_API_KEY»;
    
        AFHTTPRequestSerializer *requestSerializer = [AFJSONRequestSerializer serializer];
    
        NSString *URLString = [NSString stringWithFormat:@"https://www.googleapis.com/youtube/v3/subscriptions?part=snippet&key=%@", api_Key];
        AFHTTPRequestOperationManager *manager = [AFHTTPRequestOperationManager manager];

        NSString *authValue = [NSString stringWithFormat:@"Bearer %@", [GIDSignIn sharedInstance].currentUser.authentication.accessToken];
        NSLog(@"Access Token: %@", [GIDSignIn sharedInstance].currentUser.authentication.accessToken);
    
        [requestSerializer setValue: authValue forHTTPHeaderField:@"Authorization"];
    
        [requestSerializer setValue:@"application/json" forHTTPHeaderField:@"Content-Type"];
    manager.requestSerializer = requestSerializer;
        NSDictionary *parameters = @{@"snippet":@{
                                             @"resourceId":@{
                                                     @"channelId":channelId,
                                                     @"kind":@"youtube#channel"
                                                 }
                                         }
                                 };
        [manager POST:URLString parameters:parameters success:^(AFHTTPRequestOperation *operation, id responseObject) {
            NSLog(@«OK:»);
        } failure:^(AFHTTPRequestOperation *operation, NSError *error) {
            NSLog(@«Faild:»);
    }];

And then transmits the values obtained in:

    -(void) receiveToggleAuthUINotification:(NSNotification *) notification {
    
        if ([[notification name] isEqualToString:@"ToggleAuthUINotification"]) {
            [self subscriptionBtn];   
        }
    }

I got the following error from the failure block:

    error =     {
        code = 403;
        errors =         (
                        {
                domain = usageLimits;
                extendedHelp = "https://console.developers.google.com";
                message = "There is a per-IP or per-Referer restriction configured on your API key and the request does not match these restrictions. Please use the Google Developers Console to update your API key configuration if request from this IP or referer should be allowed.";
                reason = ipRefererBlocked;
            }
        );
        message = "There is a per-IP or per-Referer restriction configured on your API key and the request does not match these restrictions. Please use the Google Developers Console to update your API key configuration if request from this IP or referer should be allowed.";
    };

**Comment by ianbarber** [comment]
Looks like its giving you the message in the error:

"There is a per-IP or per-Referer restriction configured on your API key and the request does not match these restrictions. Please use the Google Developers Console to update your API key configuration if request from this IP or referer should be allowed."

That implies you have created a server API key, while what you want is an ios client API key. However, in this case you have an auth token, so you can probably not include the API key in the URL at all (it wont hurt to include it if they're from the same project, but the user auth is sufficient). 

Make sure you are requesting the YouTube scope as part of sign in as well!

**Comment by Kalligraf** [comment]
Hi, Ianbarber!
Thanks for fast answer! I'm requesting the YouTube scope here:

    - (void)viewDidLoad {
        [super viewDidLoad];

        [GIDSignIn sharedInstance].uiDelegate = self;
        [GIDSignIn sharedInstance].scopes = @[@"https://www.googleapis.com/auth/youtube" ];
    
        [[NSNotificationCenter defaultCenter]
         addObserver:self
         selector:@selector(receiveToggleAuthUINotification:)
         name:@"ToggleAuthUINotification"
         object:nil];
    }
Is it right?

**Comment by ianbarber** [comment]
that looks good. As long as this happens before the user presses the sign in button for the first time, and being that its viewdidload I presume so!
