### ISSUE TITLE
Can not register token with GCM

### ISSUE THREAD

**Issue by smallg** [googlesamples/google-services#49]
![image](https://cloud.githubusercontent.com/assets/225962/9463584/295f784a-4b50-11e5-90d3-b54beadab46a.png)
I copy example code in my project, and run it.
catch some error like pic.

How to fix it?

**Comment by silvolu** [comment]
@smallg have you installed the pods?

**Comment by smallg** [comment]
yes i use pod install to add Google/CloudMessaging @silvolu

**Comment by smallg** [comment]
![snip20150826_29](https://cloud.githubusercontent.com/assets/225962/9483136/db095628-4bce-11e5-8898-ef036c9976ec.png)

**Comment by smallg** [comment]
I think i am already fixed it. modify Other Link Flag value to "$(inherited)"

**Comment by silvolu** [comment]
@smallg great! I tried to reproduce it but I couldn't, so I was trying to figure out what to do next :)
