### ISSUE TITLE
App Invites restrict number

### ISSUE THREAD

**Issue by cgomezmendez** [googlesamples/google-services#5]
I can't find a way in the samples or api to restrict the number of invites one user can send via the intent, one only can have the number of invitations sents after the intent is done, there isn't a method to tell the intent that only allow the user to send x number of invitations?

**Comment by samtstern** [comment]
There is currently no way to restrict the number of invites one user can send.  Could you explain a little more why you'd like this feature?  I will provide your answer as feedback to the team.

**Comment by cgomezmendez** [comment]
I want to be able to control the flow of people installing my application, like OnePlusOne invites system, example leaving only 5 invites per user to send, that would provide a manageable grow.

**Comment by samtstern** [comment]
That's an interesting use case, thanks!  I'm going to close this issue, I will forward that on.
