### ISSUE TITLE
GoogleSignInResult returns null GoogleSignInAccount in production

### ISSUE THREAD

**Issue by amitkumargaurav** [googlesamples/google-services#502]
I am following SignInActivity to integrate google authentication in my app. It is working fine in debug apks, but when released, it is failing every time.

I have registered both debug and relese SHA-1 key on cloud platform.

my code snippet for reference-

    private void someMethid(){        
      String languageURL = "https://www.googleapis.com/auth/profile.language.read";
      String genderURL = "https://www.googleapis.com/auth/user.gender.read";
      String birthdayURL = "https://www.googleapis.com/auth/user.birthday.read";
      GoogleSignInOptions option = new 
      GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestEmail()
            .requestScopes(
                    new Scope(languageURL),
                    new Scope(genderURL),
                    new Scope(birthdayURL)
            )
            .build();
      client = GoogleSignIn.getClient(this, option);
      signIn();
    }

    private void signIn() {
      Intent signInIntent = client.getSignInIntent();
      startActivityForResult(signInIntent, RC_SIGN_IN);
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
      super.onActivityResult(requestCode, resultCode, data);

      if (requestCode == RC_SIGN_IN) {

        Task<GoogleSignInAccount> task = GoogleSignIn.getSignedInAccountFromIntent(data);
        handleSignInResult(task);
      }
    }

    private void handleSignInResult(Task<GoogleSignInAccount> completedTask) {
      GoogleSignInAccount acct = null;
      try {
        acct = completedTask.getResult(ApiException.class);
        if (acct != null) {
            fetchData(acct);
        }
        else {
            showDialogMessage("Email verification failed", "failed to get Google account information", false);
            client.revokeAccess();
            client.signOut();
        }
      } catch (ApiException e) {
        e.printStackTrace();
        showDialogMessage("Email verification failed", "failed to get Google account information", false);
        client.revokeAccess();
        client.signOut();
      }

gradle config 
defaultConfig {
        minSdkVersion 16
        targetSdkVersion 29
        multiDexEnabled true
    }

The SignIn prompt opens, does ask for google account, but does not ask for permissions of the requested scopes and retuns null for GoogleSignInAccount.

**Comment by saurabhdtu** [comment]
Any update on this? @amitkumargaurav @tjohns @domesticmouse @tiembo @nowsprinting

**Comment by domesticmouse** [comment]
Given the project commit history, I'd reach out to @samtstern and @ulukaya for updates on this project.

**Comment by amitkumargaurav** [comment]
https://stackoverflow.com/questions/66766528/googlesigninresult-returns-null-googlesigninaccount-in-production

After Uploading to play store, Play store generate its own SH1 which we have to replace in second key in google console.

**Comment by saurabhdtu** [comment]
@amitkumargaurav This I have already done. The problem that I am facing is that in the release app, the google signin is successful. But on killing the app and after a cold start, the lastSignedInAccount function returns null.
