### ISSUE TITLE
https://github.com/googlesamples/google-services/tree/master/android/analytics does not compile.

### ISSUE THREAD

**Issue by HakAl** [googlesamples/google-services#53]
This sample app doesn't compile. The R.xml.global_tracker file does not exist.
The getting started guide here: https://developers.google.com/analytics/devguides/collection/android/v4/start
actually won't accept my app name because the title contains an '&', so I can't even generate a configuration file for an app that is live in the Play Store. 
There's so much conflicting information that I have no idea how to even get started with Analytics. I've been using Tag Manager which I had similar problems with, but managed to get working somehow. Now I want to enable campaign tracking and maybe demographic info and am stuck once again.

**Comment by silvolu** [comment]
@HakAl if the package name that you use to get a configuration file for your app matches the package name that you are using in the source code of your app, then the R.xml.global_tracker file is automatically generated by the google-services gradle plugin.
Regarding the name of the app, it doesn't strictly need to match the title of the app; if you can find a string that allows you to identify the app even if it doesn't contain the '&', then you should be fine.

**Comment by HakAl** [comment]
@silvolu Thanks for the prompt response!
So I have 3 build flavors with debug and release variants for each. This results in 6 package names. Is there a recommended way to handle this? Or an example you could point me to? I assume my app won't compile because I entered the release build variant as the package name rather than my dev flavor. In the mean time, I guess I'll setup a dev.debug google-services.json and see if that compiles.

**Comment by HakAl** [comment]
@silvolu So, yeah. I switched to my production release variant and the .global_tracker file is generated (surprised?). Thanks again. I suppose I shouldn't be tracking anything except my production build. It would be nice to be able to work in dev though.

**Comment by silvolu** [comment]
@HakAl check #54 for some discussion about it.
