### ISSUE TITLE
error: cannot find symbol variable gcm_defaultSenderId

### ISSUE THREAD

**Issue by andresrivas1506** [googlesamples/google-services#56]
someone help me with this error please

Error:(51, 66) error: cannot find symbol variable gcm_defaultSenderId

**Comment by samtstern** [comment]
@andresrivas1506 have you done the following:

1) Gone through the flow at https://developers.google.com/mobile/add and enabled GCM
2) Gotten a `google-services.json` file and put it in the correct place

The `google-services gradle` plugin uses that json file to generate XML resources, one of which is `gcm_defaultSenderId`.

**Comment by andresrivas1506** [comment]
following this guide [guide](https://developers.google.com/cloud-messaging/android/client?configured=true), I downloaded the **google-services.json** file and pasted it in the **app** folder
```sh
$ mv path-to-download/google-services.json app/
```
Then I clicked the button **"Sync Project with Gradle Files"**, **"Run"** and I get this error
```
Error:(51, 66) error: cannot find symbol variable gcm_defaultSenderId
```

**Comment by kroikie** [comment]
At what point are you getting this error, during sync or run. After sync/building (no need to run) you should have a generated values.xml file in app/generated/res/google-services/debug/values/values.xml. That file contains the gcm_defaultSenderId variable. Do you have this generated file?

**Comment by andresrivas1506** [comment]
The error occurs during the **Run** and I dont hace a  **app/generated/res/google-services/debug/values/values.xml** generated after **Sync**

**Comment by kroikie** [comment]
If you do a clean build then you should at that point get "cannot find symbol" or similar error. Since you don't have the generated values.xml file then I think the google-services plugin is not executing as it should with your google-services.json. Is it the same after you Build > Rebuild Project?

**Comment by ianbarber** [comment]
Also worth looking at the gradle output to see if there are any warnings from the google-services plugin.

**Comment by andresrivas1506** [comment]
I updated the files (fetch/merge), I did Build > Rebuild Project and the error is solved

I noticed that changes were made recently in this [commit](https://github.com/googlesamples/google-services/commit/7c84b2db95c5113b13ca0f7baeae4a41b98ee8c4)

Thank you!

**Comment by ianbarber** [comment]
Yay, thanks for updating the thread!
