### ISSUE TITLE
l always get AUTHENTICATION_FAILED? can you please help me 

### ISSUE THREAD

**Issue by klower** [googlesamples/google-services#57]
<manifest package="com.cik.gcmpush"
          xmlns:android="http://schemas.android.com/apk/res/android">
    
    <uses-permission android:name="android.permission.INTERNET" />

    <permission
        android:name="com.cik.gcmpush.permission.C2D_MESSAGE"
        android:protectionLevel="signature"/>

    <uses-permission android:name="com.cik.gcmpush.permission.C2D_MESSAGE"/>

    
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE"/>

    
    <uses-permission android:name="android.permission.VIBRATE"/>
    

    
    <uses-permission android:name="android.permission.WAKE_LOCK"/>

    

  
        <receiver
            android:name="com.google.android.gms.gcm.GcmReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
                <category android:name="com.cik.gcmpush"/>
            </intent-filter>
        </receiver>
        

        
        <service
            android:name="com.cik.gcmpush.MyGcmListenerService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
            </intent-filter>
        </service>
        
        
        <service
            android:name="com.cik.gcmpush.MyInstanceIDListenerService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.android.gms.iid.InstanceID"/>
            </intent-filter>
        </service>
        
        <service
            android:name="com.cik.gcmpush.RegistrationIntentService"
            android:exported="false">
        </service>

---And l have regestered my app 

Server API Key
AIzaSyDM9Irfo0Iv6PtWxfHN**************
Sender ID:*************

**Comment by kroikie** [comment]
Do you know if the InstanceID token is retrieved successfully?

**Comment by klower** [comment]
no， after l called instanceID.getToken ,l got exception:
 try {
            // [START register_for_gcm]
            // Initially this call goes out to the network to retrieve the token, subsequent calls
            // are local.
            // [START get_token]
            InstanceID instanceID = InstanceID.getInstance(this);
            String token = instanceID.getToken(getString(R.string.gcm_defaultSenderId),
                    GoogleCloudMessaging.INSTANCE_ID_SCOPE, null);
            // [END get_token]
            Log.i(TAG, "GCM Registration Token: " + token);

            // TODO: Implement this method to send any registration to your app's servers.
            sendRegistrationToServer(token);

            // Subscribe to topic channels
            subscribeTopics(token);

            // You should store a boolean that indicates whether the generated token has been
            // sent to your server. If the boolean is false, send the token to your server,
            // otherwise your server should have already received the token.
            sharedPreferences.edit().putBoolean(QuickstartPreferences.SENT_TOKEN_TO_SERVER, true).apply();
            // [END register_for_gcm]
        } catch (Exception e) {
            Log.d(TAG, "Failed to complete token refresh", e);
            // If an exception happens while fetching the new token or updating our registration data
            // on a third-party server, this ensures that we'll attempt the update at a later time.
            sharedPreferences.edit().putBoolean(QuickstartPreferences.SENT_TOKEN_TO_SERVER, false).apply();
        }

**Comment by kroikie** [comment]
Could you include the details of the exception?

**Comment by klower** [comment]
09-02 15:49:24.916  29138-29162/com.cik.gcmpush D/RegIntentService﹕ Failed to complete token refresh
    java.io.IOException: AUTHENTICATION_FAILED
            at com.google.android.gms.iid.zzc.zzb(Unknown Source)
            at com.google.android.gms.iid.zzc.zza(Unknown Source)
            at com.google.android.gms.iid.InstanceID.zzc(Unknown Source)
            at com.google.android.gms.iid.InstanceID.getToken(Unknown Source)
            at com.cik.gcmpush.RegistrationIntentService.onHandleIntent(RegistrationIntentService.java:51)
            at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by silvolu** [comment]
@klower please use [this form](https://support.google.com/code/contact/gcm_dev_support) to get support for your issue. The form will allow you to send your project credentials along with a detailed description of the issue.

**Comment by brenohq** [comment]
same issue here
