### ISSUE TITLE
java.io.IOException: INVALID_PARAMETERS Error

### ISSUE THREAD

**Issue by shireen-obtainit** [googlesamples/google-services#61]
Hii,
I am new in Android app development. I am working on GCM notification. I have followed all the steps mentioned in https://developers.google.com/cloud-messaging/android/start. But getting error java.io.IOException: INVALID_PARAMETERS Error in RegistrationIntentService.java file at line 57.
  String token = instanceID.getToken(getString(R.string.gcm_defaultSenderId), GoogleCloudMessaging.INSTANCE_ID_SCOPE, null);
Can you support me to solve this error?????

**Comment by kroikie** [comment]
What device are you using? Also could you try the sample on another device or in an emulator that has Google Play Services and see if you get a different result?

**Comment by shireen-obtainit** [comment]
Hii,
I tried running the project using Genymotion Emulator it give error as
Google play services is not available.But when I am running project using real device it is giving error as java.io.IOException: INVALID_PARAMETERS. Any clue about this?

**Comment by kroikie** [comment]
I'd suggest trying with one of the emulators in Android Studio, you can create an emulator that has the Google APIs (Google Play Services). INVALID_PARAMETERS would suggest that your sender id is not being recognized. Could you log your sender id and check that is is not null or otherwise incorrect?

**Comment by samtstern** [comment]
@shireen-obtainit going to close this issue for lack of activity.  If you are still getting this problem, please re-open and we'll be happy to keep looking at it.
