### ISSUE TITLE
AppInvites “Install” link doesn't open the app

### ISSUE THREAD

**Issue by frogermcs** [googlesamples/google-services#65]
This issue is related to my question on StackOverflow:
http://stackoverflow.com/questions/32494505/appinvites-install-link-doesnt-open-the-app

In short seems that deeplinking doesn't always work as it should. Sometimes instead of opening sample app it suggests to open Google Play Store (or website). On Marshamallow it causes endless loop (statusbar blinks and logs return 401s).

**Comment by samtstern** [comment]
Thank you for this report and for bringing it to GitHub (I missed it on StackOverflow).  I will create a bug internally and follow up with the right engineers to see if they know what is going on.

**Comment by samtstern** [comment]
@frogermcs could you plug in your device, run the following `adb` commands, and then capture a new `logcat` log during a run of the app that has the problem:

```
adb logcat -c
adb shell setprop log.tag.Volley VERBOSE
adb shell setprop log.tag.httpclient.wire.header VERBOSE
adb shell setprop log.tag.httpclient.wire.content VERBOSE
adb shell setprop log.tag.GLSUser VERBOSE                                                                  
adb shell setprop log.tag.GLSActivity VERBOSE
```

**Comment by frogermcs** [comment]
Cannot reproduce it now. Seems that something was changed on play services (or somewhere else) because for example now I can see progress bar after install link was clicked. I'll let you know when error comes back.
