### ISSUE TITLE
SignExample sample app doesn't appear to cleanly compile with xcode7 & ios9 SDK

### ISSUE THREAD

**Issue by petersibley** [googlesamples/google-services#69]

**Comment by kroikie** [comment]
It may be due to bitcode option that is on by default. More information about the compile error would be helpful.

**Comment by petersibley** [comment]
Yup it was bit code being turned on by default.

**Comment by petersibley** [comment]
I added ENABLE_BITCODE = NO; to the xcode proj and upgraded swift and fixed a build break where swift was using println not print.

**Comment by silvolu** [comment]
@petersibley we were waiting for the release of the stable version of xcode7 to update the samples, and I'm working on it right now.

**Comment by silvolu** [comment]
@gguuss has just committed ac32ecaea5016f66e3fb2a75b17d74ec69ea30de to fix this.
