### ISSUE TITLE
appindexing version 2.0.1 doens't support bitcode

### ISSUE THREAD

**Issue by mltk96** [googlesamples/google-services#75]
after updating Xcode to 7.0.1 i can't compile my project with bitcode support. i'm getting the next error:

ld: bitcode bundle could not be generated because '/.../GoogleAppIndexing/Frameworks/GoogleAppIndexing.framework/GoogleAppIndexing(GSDDeepLink.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7

**Comment by silvolu** [comment]
If you're not building for watchOS, bitcode is not required but just recommended, so you can just it off. We will add bitcode support in the next releases, but I don't know yet when exactly.

**Comment by willlarche** [comment]
Any news on this?

**Comment by yoman07** [comment]
Any news?

**Comment by kroikie** [comment]
App-indexing currently does not support bitcode. This is a known issue and
the team is working on a fix.

**Comment by mltk96** [comment]
any updates? it's been almost a year since i've originally opened that issue.
It's quite ridiculous that out of the 20+ frameworks i'm using, your's is the only one who doesn't support bitcode.
