### ISSUE TITLE
IOS crash in [self.inviteDialog open] for all targets except one

### ISSUE THREAD

**Issue by DimaKorol** [googlesamples/google-services#76]
I implemented AppInvite in pod ('Google/AppInvite', '~> 1.0.2') and following app guides. I have in app more then one target and some of them has different bundle identifier.
I solved it with config instances on didFinishLaunchingWithOptions in this way:
    NSError* configureError;
    [[GGLContext sharedInstance] configureWithError:&configureError];
    NSAssert(!configureError, @"Error configuring Google services: %@", configureError);

    [[GAI sharedInstance] trackerWithTrackingId:googleTrackerId];
    [GIDSignIn sharedInstance].clientID = googleClientId;
    [GINInvite setAPIKey:googleApiKey];
    [GINInvite setGoogleAnalyticsTrackingId:googleTrackerId];
    GINInviteTargetApplication *targetToAndroid = [[GINInviteTargetApplication alloc] init];
    targetToAndroid.androidClientID = googleOtherAppClientId;
    [GINInvite setDefaultOtherPlatformsTargetApplication:targetToAndroid];
    [GINInvite applicationDidFinishLaunching]; 

but correctly works only with one target (first one in target list). For other I have such flow:
-try to open invite dialog [self.inviteDialog open];
-sign in if [[GIDSignIn sharedInstance] signInSilently] didn't do that
-then try to show invite dialog [self.inviteDialog open]; again
-get a crash

Thread : Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x249eb137 __exceptionPreprocess
1  libobjc.A.dylib                0x32d28c77 objc_exception_throw
2  CoreFoundation                 0x24906655 -[__NSDictionaryM setObject:forKey:]
3  ThaiJoop Pro                   0x0051e311 +[NSBundle(GPPAdditions) gpp_setBundle:forName:]
4  ThaiJoop Pro                   0x004f651b -[GINInviteBuilderImpl initializeBundles]
5  ThaiJoop Pro                   0x004f608b -[GINInviteBuilderImpl open]
6  ThaiJoop Pro                   0x001b6c67 -[TJFreeTokensController showInviteFriends] (TJFreeTokensController.m:155)
7  ThaiJoop Pro                   0x001b6581 -[TJFreeTokensController tableView:didSelectRowAtIndexPath:] (TJFreeTokensController.m:99)
8  UIKit                          0x2813c113 -[UITableView _selectRowAtIndexPath:animated:scrollPosition:notifyDelegate:]
9  UIKit                          0x281eae0b -[UITableView _userSelectRowAtPendingSelectionIndexPath:]
10 UIKit                          0x280a06f9 _applyBlockToCFArrayCopiedToStack
11 UIKit                          0x2801af37 _afterCACommitHandler
12 CoreFoundation                 0x249b126d __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
13 CoreFoundation                 0x249ae951 __CFRunLoopDoObservers
14 CoreFoundation                 0x249aed53 __CFRunLoopRun
15 CoreFoundation                 0x248fa9a1 CFRunLoopRunSpecific
16 CoreFoundation                 0x248fa7b3 CFRunLoopRunInMode
17 GraphicsServices               0x2c0aa1a9 GSEventRunModal
18 UIKit                          0x28085695 UIApplicationMain
19 ThaiJoop Pro                   0x00225af5 main (main.m:18)
20 libdyld.dylib                  0x332d0aaf start

also I noticed that sign in screen doesn't have cancel button for one target 
![simulator screen shot sep 30 2015 19 09 17](https://cloud.githubusercontent.com/assets/6595058/10198850/9795b2a8-67a6-11e5-870a-fff6241d78b7.png)
 and has for anther 
![simulator screen shot sep 30 2015 19 07 56](https://cloud.githubusercontent.com/assets/6595058/10198843/8e198a7e-67a6-11e5-8b3f-5e5b526c5734.png)

**Comment by ianbarber** [comment]
The exception is not great, but the different bundle ID is likely to be at the heart of this. A client ID (used for sign in) is associated with just one bundle ID. What you'll need to do is to add new clients with the appropriate bundle IDs through https://developers.google.com/mobile/add  and save the GoogleServices-Info.plist for each in a different folder (maybe named after the bundle ID). Then add each GoogleServices-Info.plist to the target with the matching bundle ID.

**Comment by DimaKorol** [comment]
Yes, I've already tried to add two separate GoogleServices-Info.plist files in different folders and associated with different target, but it didn't help. By this reason I decided to use one .plist file and set client Id from code in app start (as I wrote above):

**Comment by ianbarber** [comment]
Closing as AppInvites has now moved to Firebase Invites.
