### ISSUE TITLE
New version of GoogleSignIn for iOS conflict with protobuf-objc

### ISSUE THREAD

**Issue by kientux** [googlesamples/google-services#78]
New version of GoogleSignIn (from v2.2.0 I think) has a new dependency GoogleInterchangeUtilities, which contains static library for [Google Protocol Buffers](https://developers.google.com/protocol-buffers/). That make it impossible to use with [protobuf-objc](http://protobuf.io/#objc) (ProtocolBuffers for Objective-C) - causes **"Undefined symbol for architect xxx"** when compile.

GoogleInterchangeUtilities has no public headers for the static lib so I can't use it neither. I have to use older (v2.1.0) GoogleSignIn.

**Comment by silvolu** [comment]
@kientux I tried with [this pod](https://cocoapods.org/pods/Protobuf-objc), and I can't reproduce.

**Comment by kientux** [comment]
@silvolu yes I just tried with that pod and there is no conflict. But that pod is not well maintained and seems so old, it causes many errors when compiled with my generated protobuf class. I previously use GoogleSignIn with [this pod](https://cocoapods.org/pods/protocolbuffers). Maybe I will ask its owner if he can do anything about this, and use v2.1.0 of Google SignIn for now.

**Comment by silvolu** [comment]
@kientux I checked that one because it thad the same spelling as the one you mentioned when opening the issue :) Thanks!
