### ISSUE TITLE
Trying to sign in crashes and gives me: ''Your app is missing support for the following URL schemes'

### ISSUE THREAD

**Issue by vu0tran** [googlesamples/google-services#81]
I'm running the following code versions on iOS 9:
```
Installing Google (1.1.0)
Installing GoogleAppUtilities (1.0.0)
Installing GoogleAuthUtilities (1.0.1)
Installing GoogleInterchangeUtilities (1.0.0)
Installing GoogleNetworkingUtilities (1.0.0)
Installing GoogleSignIn (2.3.1)
Installing GoogleSymbolUtilities (1.0.0)
Installing GoogleUtilities (1.1.0)
```
Here is the crash
```
 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Your app is missing support for the following URL schemes: com.googleusercontent.apps.514797035410-uksdcup8ju2g0frgqq3f88ieqnvmr2t9'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000106d32f65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010aa48deb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000106d32e9d +[NSException raise:format:] + 205
	3   SlideMail                           0x0000000104d2d678 -[GIDSignIn signInWithOptions:] + 326
	4   SlideMail                           0x0000000104d319b8 -[GIDSignInButton pressed] + 331
	5   UIKit                               0x00000001086681fa -[UIApplication sendAction:to:from:forEvent:] + 92
	6   SlideMail                           0x0000000104b3792f -[UIApplication(EventInterceptor) heap_sendAction:to:from:forEvent:] + 337
	7   UIKit                               0x00000001087cc504 -[UIControl sendAction:to:forEvent:] + 67
	8   UIKit                               0x00000001087cc7d0 -[UIControl _sendActionsForEvents:withEvent:] + 311
	9   UIKit                               0x00000001087cb906 -[UIControl touchesEnded:withEvent:] + 601
	10  UIKit                               0x00000001086d2aa3 -[UIWindow _sendTouchesForEvent:] + 835
	11  UIKit                               0x00000001086d3691 -[UIWindow sendEvent:] + 865
	12  UIKit                               0x0000000108685752 -[UIApplication sendEvent:] + 263
	13  SlideMail                           0x0000000104b377b1 -[UIApplication(EventInterceptor) heap_sendEvent:] + 435
	14  UIKit                               0x0000000108660fcc _UIApplicationHandleEventQueue + 6693
	15  CoreFoundation                      0x0000000106c5f0a1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	16  CoreFoundation                      0x0000000106c54fcc __CFRunLoopDoSources0 + 556
	17  CoreFoundation                      0x0000000106c54483 __CFRunLoopRun + 867
	18  CoreFoundation                      0x0000000106c53e98 CFRunLoopRunSpecific + 488
	19  GraphicsServices                    0x000000010be0ead2 GSEventRunModal + 161
	20  UIKit                               0x0000000108666676 UIApplicationMain + 171
	21  SlideMail                           0x00000001048bcb22 main + 162
	22  libdyld.dylib                       0x000000010b88592d start + 1
	23  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

I added the following to my .plist and it's still crashing.

```
    <key>LSApplicationQueriesSchemes</key>
    <array>
        <string>com.googleusercontent.apps.514797035410-uksdcup8ju2g0frgqq3f88ieqnvmr2t9</string>
    </array>
```

**Comment by masbenx** [comment]
i got the same trouble

**Comment by pratamawijaya** [comment]
up up

**Comment by vu0tran** [comment]
D'oh. Forgot to add the URL schemes shown at the bottom of the tutorial:

https://developers.google.com/identity/sign-in/ios/start-integrating

**Comment by fabiofai** [comment]
I have the same problem, but I am not using that scheme

**Comment by johnn82** [comment]
I've faced the same problem. My mistake was to use the "Client ID" created in the google developer console when creating the "Web Application" login credentials and assuming they are the same to be used in iOS. You need to use the client ID in the GoogleService-Info.plist which is different!

**Comment by mwaqas01** [comment]
I had the same issue and resolve it by performing below steps:

**Add custom URL schemes to your Xcode project:**
1)Open your project configuration: double-click the project name in the left tree view. Select your app from the TARGETS section, then select the Info tab, and expand the URL Types section.
Click the + button, and add a URL scheme for your reversed client ID. To find this value, open the **GoogleService-Info.plist** configuration file, and look for the **REVERSED_CLIENT_ID** key. Copy the value of that key, and paste it into the URL Schemes box on the configuration page. Leave the other fields blank.
When completed, save the file and rebuild the project.

For more detail visit 
https://firebase.google.com/docs/auth/ios/google-signin

**Comment by elbuenyuz** [comment]
what if i already have a **GoogleService-Info.plist** s for fBSDKLogin , and know am trying to make it work with GoogleSignIn??

**Comment by gajjartejas** [comment]
I think this could solve your problem: 
![screen shot 2017-02-08 at 5 21 13 pm](https://cloud.githubusercontent.com/assets/14052969/22736283/627be290-ee23-11e6-8ea1-b1487db0884d.png)

**Comment by Sweetog** [comment]
@elbuenyuz Great question, I just took a shot in the dark to get Facebook Auth and Google Auth working in the same app and it actually worked, you add **two** URL Schemes, both with the same value for the  REVERSED_CLIENT_ID key in the GoogleService-Info.plist (that URL value I will call RCURL).

- Facebook SDK: [Facebook AppId]**,**[RCURL]
- Google SDK: [BundleIdentifier]**,**[RCURL]

Noticed how I put that comma in bold, the url scheme entry is a key value pair and ends up in Info.plist in a particular key/value format. Here is a screenshot to help:
![screen shot 2017-05-21 at 6 06 56 pm copy](https://cloud.githubusercontent.com/assets/53242/26289068/2341d296-3e51-11e7-8fd7-dcf6f472b779.png)

**Comment by DSTOLF** [comment]
If anybody else had this error even after setting the URL Type on Info tab, GOOGLE_SIGNIN_URL_SCHEME on Build Settings tab and adding GoogleService-Info.plist to your project, here's a tip: when you add the plist file to your project, be sure to add to ALL freaking targets like the docs tell you to... 

I had cloned a project from github and it had tvOS targets... since I'm not doing anything for apple tv, I didn't bother to check those combo boxes, nor remove those tvOS targets... and got this error on iphone simulator, which I thought was completely unrelated... it drove me crazy for two days...

**Comment by patelhari** [comment]
@Sweetog it's working fine...
Thank You.

**Comment by RicardoBarroso** [comment]
If perhaps meanwhile you change your App ID and you have your API key restricted to that, don't forget to update it!
My mistake was that even that I had created a new App ID restricted to my new App ID, I had not updated it on the app URL scheme.

**Comment by swapniltoo** [comment]
My issue was solved by adding this lines in "viewDidAppear"
        GIDSignIn* signIn = [GIDSignIn sharedInstance];
       [GlobalObj sharedInstance].delegate=self;
        signIn.shouldFetchBasicProfile = YES;
        signIn.clientID= @"XXXXXXXXXXXXX";
        signIn.scopes = @[ @"profile", @"email" ];
        signIn.delegate = self;
        signIn.uiDelegate = self;

**Comment by Mitesh-Mewada** [comment]
Add **MAIN** info.plist add new URL type 
![screenshot 2018-10-04 at 11 17 16 am](https://user-images.githubusercontent.com/37366524/46455172-6ca56c80-c7c7-11e8-99c1-d998f31a1be8.png)

**Comment by shengrenjin** [comment]
I have this problem too, and I have solved it . 
The key in developer background your apply all in used in IOS , you can look at the example 

 clientID  = "xxxxx-xxxx.apps.googleusercontent.com"
 url schemes  = "com.googleusercontent.apps.xxxx-xxxxxx

**Comment by MartinhoMCM** [comment]
The solution for this problem is:

 1. First you need to open you Xcode project run open ios/Runner.xcworkspace

 2. In Xcode project find GoogleServiceInfo.plist, click and copy REVERSED_CLIENT_ID (right side)
  
<img width="744" alt="Screenshot 2020-01-09 at 14 08 34" src="https://user-images.githubusercontent.com/20285732/72071212-9236f500-32eb-11ea-8a47-b680d57a4a3a.png">


 3. Go to Runner -> Info-> URL Types and click to + .

 4. Past the  REVERSED_CLIENT_ID in URL SCHEME

<img width="1257" alt="Screenshot 2020-01-07 at 13 28 24" src="https://user-images.githubusercontent.com/20285732/72071235-9c58f380-32eb-11ea-922e-c9b86fd6a212.png">

**Comment by mclean25** [comment]
> The solution for this problem is:
> 
>     1. First you need to open you Xcode project run open ios/Runner.xcworkspace
> 
>     2. In Xcode project find GoogleServiceInfo.plist, click and copy REVERSED_CLIENT_ID (right side)
> 
> 
> <img alt="Screenshot 2020-01-09 at 14 08 34" width="744" src="https://user-images.githubusercontent.com/20285732/72071212-9236f500-32eb-11ea-8a47-b680d57a4a3a.png">
> 
>     1. Go to Runner -> Info-> URL Types and click to + .
> 
>     2. Past the  REVERSED_CLIENT_ID in URL SCHEME
> 
> 
> <img alt="Screenshot 2020-01-09 at 14 16 40" width="668" src="https://user-images.githubusercontent.com/20285732/72071344-dd510800-32eb-11ea-956d-9f399bc9d01a.png">

This worked for me on Flutter as well 👍

**Comment by abowassm** [comment]
What should I do? Can you modify the support?

**Comment by junaid5546** [comment]
in my case i did'nt configure the firebase.

**Comment by CyrusZei** [comment]
what worked for me was to change the `webClientId` key to `clientID`

**Comment by emtt** [comment]
For me I have to add these value of URL Scheme in the "Property List" not in "Code" mode of info.plist.

Why? After two hours I don't care.

**Comment by bogdanbgd7** [comment]
<img width="634" alt="Screenshot 2021-01-15 at 12 45 28" src="https://user-images.githubusercontent.com/43911633/104723624-d2675980-572f-11eb-9f05-2bd42f45a200.png">

In my case, I forgot to add Items for both Google and Facebook OAuth.

**Comment by mcAnastasiou** [comment]
I have already added Firebase cloud messaging. I downloaded the GoogleService-info.plist, which is needed for the Cloudmessaging. I added the google sign in for ios without using the firebase. I added the reversed client id, but i get an error that "your app is missing support for the following URL schemes"... The urlScheme is the reverse client id used by firebase and not the google sign in. How can i handle this?

**Comment by dhanrajY** [comment]
> The solution for this problem is:
> 
> 1. First you need to open you Xcode project run open ios/Runner.xcworkspace
> 2. In Xcode project find GoogleServiceInfo.plist, click and copy REVERSED_CLIENT_ID (right side)
> 
> <img alt="Screenshot 2020-01-09 at 14 08 34" width="744" src="https://user-images.githubusercontent.com/20285732/72071212-9236f500-32eb-11ea-8a47-b680d57a4a3a.png">
> 
> 3. Go to Runner -> Info-> URL Types and click to + .
> 4. Past the  REVERSED_CLIENT_ID in URL SCHEME
> 
> <img alt="Screenshot 2020-01-09 at 14 16 40" width="668" src="https://user-images.githubusercontent.com/20285732/72071344-dd510800-32eb-11ea-956d-9f399bc9d01a.png">

Right! but i had issue after trying this also so make sure webClientId or iosClientId should be ClientId

```
GoogleSignin.configure({
      webClientId:"#id.apps.googleusercontent.com",
      ClientId: '#id.apps.googleusercontent.com',
      offlineAccess: false
    }
```

**Comment by akram-chopdawg** [comment]
i also faced the same, followed all the methods once i click save (i just open it for url and client id and forgot to save it agin) in google console and rebuild its work

**Comment by FuadEfendi** [comment]
I had this issue for iOS, using Android Studio, so that any X-Code-related explicit troubleshooting steps are not applicable.

What I did is this:

```
    flutter create cscexams --org ca.tokenizer
    cd cscexams
    firebase login
    dart pub global activate flutterfire_cli
    flutterfire configure
```

After that, develop application, including Google Authentication (enable it in Google Console); Android works just fine, but iOS crashes with exact same message.

Explicitly adding  this section to `ios/Runner/Info.plist` fixed the issue:

```
		<key>CFBundleURLTypes</key>
		<array>
			<dict>
				<key>CFBundleTypeRole</key>
				<string>Editor</string>
				<key>CFBundleURLSchemes</key>
				<array>
					<!-- Copied from GoogleService-Info.plist key REVERSED_CLIENT_ID -->
					<string>com.googleusercontent.apps.123456-REPLACE_ME</string>
				</array>
			</dict>
		</array>
```

Unfortunately, `flutterfire configure` command doesn't do it for us.

**Comment by alefwd** [comment]
@FuadEfendi thank you so much worked like a charm! I experienced the same when trying to login with Google Sign In and Firebase from iOS

**Comment by favourO** [comment]
Thanks man

**Comment by CodeGradientsProjects** [comment]
thanks [mwaqas01](https://github.com/mwaqas01)  what need to do further delete the app from simulator or device and then again run the the app it then worked for me. ❤️

**Comment by enny007** [comment]
@FuadEfendi You are a life saver, your approach worked for me. Thank you and God bless you.
