### ISSUE TITLE
how does the app deal with iOS 9's `-application:handleURL:options:` callback?

### ISSUE THREAD

**Issue by jtihon** [googlesamples/google-services#88]
Greetings,
I added `-application:handleURL:options:` to my appDelegate and then sign-in broke. I realized I hadn't hooked up `GIDSignIn`'s `-handleURL:sourceApplication:annotation:`. However, when I did that it still was broken.

I've taken it out for the time being, but it'd be nice to know how to work around this.

**Comment by ianbarber** [comment]
Where did you call handleURL on GIDSignIn? In the appdelegate application:handleURL:options: or handleURL:sourceApplication:annotation?

**Comment by ianbarber** [comment]
Did a quick bit of checking - as long as you unpack the options, you should be fine: 

  @available(iOS 9.0, *)
  func application(app: UIApplication, openURL url: NSURL, options: [String : AnyObject]) -> Bool {
    return GIDSignIn.sharedInstance().handleURL(url,
      sourceApplication: options[UIApplicationOpenURLOptionsSourceApplicationKey] as! String?,
      annotation: options[UIApplicationOpenURLOptionsAnnotationKey])
  }

I'll add this to the sample! Thanks!
