### ISSUE TITLE
Typo in app indexing

### ISSUE THREAD

**Issue by ThrowDice** [googlesamples/google-services#9]
final Uri APP_URI = Uri.parse("android-app://com.google.developers.app-indexing.quickstart/http/example.com/articles/" + articleId);

should be

final Uri APP_URI = Uri.parse("android-app://com.google.developers.app_indexing.quickstart/http/example.com/articles/" + articleId);

'-' should be changed to '_'

**Comment by narphorium** [comment]
That part of the URI is the app ID. You can see the app ID defined with an underscore here: https://github.com/googlesamples/google-services/blob/master/android/app-indexing/app/build.gradle

**Comment by ianbarber** [comment]
I think the issue is the use of a - rather than the underscore https://github.com/googlesamples/google-services/blob/master/android/app-indexing/app/src/main/java/com/google/developers/app_indexing/quickstart/MainActivity.java#L71
