### ISSUE TITLE
Plus.PeopleApi.getCurrentPerson(mGoogleApiClient) returns null

### ISSUE THREAD

**Issue by MangeshKadam** [googlesamples/google-services#90]
I have followed all the documentation for sigin and used the sample code as mentioned. But I am getting null value for Plus.PeopleApi.getCurrentPerson(mGoogleApiClient) whereas Plus.AccountApi.getAccountName(mGoogleApiClient); returns proper email ID I am signed in with. Any help will be appreciated.

**Comment by samtstern** [comment]
This normally happens when you make a mistake when following the steps at https://developers.google.com/mobile/add

Make sure you use the same package name from your `build.gradle` file and you have the correct debug keystore SHA1.

**Comment by MangeshKadam** [comment]
Hi, 
I have followed the steps as mentioned in doc. Strange issue is I tried same apk with different device with different login its giving all the required details. Still trying to find why its not working with my account.

**Comment by samtstern** [comment]
You could try clearing data on the Google Play Services app (Settings > Apps > Google Play Services) to see if that resolves the account-specific issue.

**Comment by renanferrari** [comment]
I had this same issue and solved it clearing the Play Services cache, as suggested by @samtstern

**Comment by akki777** [comment]
It returns null when your google account does not have google plus enabled.
