### ISSUE TITLE
iOS GCM Example compilation error - missing Icon@2x.png

### ISSUE THREAD

**Issue by yakubbaev** [googlesamples/google-services#93]
error: /var/folders/l0/02vph8kx28vd5lzl41zp4bn40000gn/T/CocoaPods/Try/Google/Samples/shared/Icon@2x.png: No such file or directory

**Comment by yakubbaev** [comment]
Fixed by removing Icon@2x.png reference from Shared group in Xcode.

**Comment by ianbarber** [comment]
Thanks! Think that one is resolved now.
