### ISSUE TITLE
Android signin google-play-services-8.3.0 google-services.json missing ERROR!!

### ISSUE THREAD

**Issue by RashidMeridian** [googlesamples/google-services#94]
While using the signin app using google-play-services-8.3.0 i get the error as

 Error:Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing from module root folder. The Google Services Plugin cannot function without it.

**Comment by RoneyThomas** [comment]
https://stackoverflow.com/questions/33556780/errorexecution-failed-for-task-appprocessdebuggoogleservices-please-fix/33558478#33558478
