### ISSUE TITLE
What about full bitcode support?

### ISSUE THREAD

**Issue by psegalen** [googlesamples/google-services#95]
Hi,
When I try to implement Google App Indexing on an app that already has a WatchKit extension, I can run it but I can't archive it since the SDK doesn't seem to to have full bitcode support.
Does anyone know when this support will be available please?
Thanks.

**Comment by uknowmeright** [comment]
I had to turn off Bitcode as well for just a standard integration in my app to even receive a registration token. Kind of inconvenient. This should at least be added to the guide as a possible issue for the developer.

**Comment by aventurella** [comment]
I agree, this should at least be noted in the documentation. I just ran into this as well.

**Comment by ianbarber** [comment]
Full bitcode support is still in progress, but I think we are (largely) unblocked on our internal build system, so we should see progress sometimes soon! Several libraries have been rebuilt with bitcode support already.

**Comment by brunobar79** [comment]
Any news this?

**Comment by grizzly** [comment]
New build available on Cocoapods, but still without bitcode support.

**Comment by ianbarber** [comment]
I think we should be there with the latest pod release! Let us know if there are problems.

**Comment by stema** [comment]
Hmm my Xcode says its not. Can anybody proof that?

**Comment by ianbarber** [comment]
Ah yeah, it looks like some pods are not yet updated - so the bitcode support is only partial. Sorry all.

**Comment by ianbarber** [comment]
Hopefull this should (finally) be in!
